plugins {
	id 'svws.gradle.node.plugin'
}

def CLIENT_SECRET = "not set"

apply from: ('../subproject-plugin.gradle')
apply from: 'custom-tasks.gradle'

/**
 * Konfiguration für das Subpackage bzw. die Tests
 */
ext {
	SVWS_SERVERMODE = "dev"

	// Docker Konfiguration
	APP_CONTAINER_NAME = "svws-server-enm-tests${rootProject.ext.CONTAINER_NAME_SUFFIX}"
	ENM_CONTAINER_NAME = "enm-server-enm-tests${rootProject.ext.CONTAINER_NAME_SUFFIX}"
	DB_CONTAINER_NAME = "db-enm-tests${rootProject.ext.CONTAINER_NAME_SUFFIX}"

	APP_IMAGE_NAME = "svws-server-enm-tests${rootProject.ext.CONTAINER_NAME_SUFFIX}"
	ENM_IMAGE_NAME = "enm-server-enm-tests${rootProject.ext.CONTAINER_NAME_SUFFIX}"
	DB_SERVICE_NAME = "db-enm-tests${rootProject.ext.CONTAINER_NAME_SUFFIX}"

	// Auch für Docker. Forwarded Ports, werden nur bei lokal genutzten Container verwendet
	FORWARDED_DB_PORT = 3333
	FORWARDED_APP_PORT = 5050

	// Liste der Datenbanken die für die Tests genutzt / geseedet werden sollen
	TARGET_TEST_DATABASES = ['ENM02A']
}

/**
 * Führt die Vitest Task setupTests mit entsprechenden Umgebungsvariablen aus
 */
tasks.register('runSetupTest', NpmRun) {
	description = "Führt die Vitest Task setupTests mit entsprechenden Umgebungsvariablen aus"

	environment NODE_TLS_REJECT_UNAUTHORIZED: 0

	ignoreExitValue = true
	outputs.upToDateWhen { false }

	def APP_CONTAINER_NAME = APP_CONTAINER_NAME
	def ENM_CONTAINER_NAME = ENM_CONTAINER_NAME
	def FORWARDED_APP_PORT = FORWARDED_APP_PORT

	// Die Ziel-url vom Container mit der Application
	environment VITE_ENM_FOR_SVWS_targetHost: "https://$ENM_CONTAINER_NAME"

	if (System.getenv('CI_SERVER')) {
		environment VITE_APP_targetHost: "https://$APP_CONTAINER_NAME:8443"
		environment VITE_ENM_targetHost: "https://$ENM_CONTAINER_NAME:443"
	} else {
		environment VITE_APP_targetHost: "https://localhost:$FORWARDED_APP_PORT"
		environment VITE_ENM_targetHost: "https://localhost"
	}

	args = ['test:setup']
}

/**
 * Liest das Client Secret aus dem laufenden ENM Server aus sodass dies für die Testfälle zur verfügung steht
 */
tasks.register('extractClientSecret', Exec) {
	description = "Liest das Client Secret aus dem laufenden ENM Server aus sodass dies für die Testfälle zur verfügung steht"
	mustRunAfter(runSetupTest)

	executable 'docker'
	def ENM_CONTAINER_NAME = project.ext.ENM_CONTAINER_NAME;
	doFirst {
		mkdir file("$projectDir/build/tempdocker/clientsecret")
		args 'cp', "${ENM_CONTAINER_NAME}:/var/www/html/db/client.sec", "build/tempdocker/clientsecret"
	}

	doLast {
		def captured = file("build/tempdocker/clientsecret/client.sec").text
		ext.fileContentVariable = captured
		CLIENT_SECRET = "${captured}"
	}
}


/**
 * Führt die Vitest Task SyncTests mit entsprechenden Umgebungsvariablen aus
 */
tasks.register('runSyncTest', NpmRun) {
	description = "Führt die Vitest Task SyncTests mit entsprechenden Umgebungsvariablen aus"
	mustRunAfter(extractClientSecret)

	environment NODE_TLS_REJECT_UNAUTHORIZED: 0

	ignoreExitValue = true
	outputs.upToDateWhen { false }

	def ENM_CONTAINER_NAME = project.ext.ENM_CONTAINER_NAME
	def APP_CONTAINER_NAME = project.ext.APP_CONTAINER_NAME
	def FORWARDED_APP_PORT = project.ext.FORWARDED_APP_PORT

	doFirst {
		// Die Ziel-url vom Container mit der Application
		environment VITE_ENM_FOR_SVWS_targetHost: "https://$ENM_CONTAINER_NAME"
		environment VITE_CLIENT_SECRET: "${CLIENT_SECRET}"
		if (System.getenv('CI_SERVER')) {
			environment VITE_APP_targetHost: "https://$APP_CONTAINER_NAME:8443"
			environment VITE_ENM_targetHost: "https://$ENM_CONTAINER_NAME:443"
		} else {
			environment VITE_APP_targetHost: "https://localhost:$FORWARDED_APP_PORT"
			environment VITE_ENM_targetHost: "https://localhost"
		}

		args = ['test:sync']
	}
}

/**
 * Führt die Vitest Task afterSetup mit entsprechenden Umgebungsvariablen aus
 */
tasks.register('runTestsAfterSetup', NpmRun) {
	description = "Führt die Vitest Task afterSetup mit entsprechenden Umgebungsvariablen aus"
	mustRunAfter("runSyncTest")

	environment NODE_TLS_REJECT_UNAUTHORIZED: 0

	ignoreExitValue = true
	outputs.upToDateWhen { false }

	def ENM_CONTAINER_NAME = project.ext.ENM_CONTAINER_NAME
	def APP_CONTAINER_NAME = project.ext.APP_CONTAINER_NAME
	def FORWARDED_APP_PORT = project.ext.FORWARDED_APP_PORT

	// Die Ziel-url vom Container mit der Application
	if (System.getenv('CI_SERVER')) {
		environment VITE_APP_targetHost: "https://$APP_CONTAINER_NAME:8443"
		environment VITE_ENM_targetHost: "https://$ENM_CONTAINER_NAME:443"
	} else {
		environment VITE_APP_targetHost: "https://localhost:$FORWARDED_APP_PORT"
		environment VITE_ENM_targetHost: "https://localhost"
	}

	args = ['test:afterSetup']
}

/**
 * Starten der Integrationstests gegen die Docker Umgebung
 */
tasks.register('testAgainstDockerEnv') {
	description = 'Startet die Integrationstests gegen die Docker Umgebung'
	group = 'testing'
	dependsOn ':svws-webclient:core:assemble'
	dependsOn ':svws-webclient:client:assemble'
	dependsOn 'starteDockerContainerMitTestUmgebung'
	dependsOn 'starteDockerContainerMitTestUmgebungENM'

	finalizedBy("runSetupTest")
	finalizedBy("extractClientSecret")
	finalizedBy("runSyncTest")
	finalizedBy("runTestsAfterSetup")

	if (!rootProject.ext.CONFIG.keepContainerAfterTestRun) {
		finalizedBy "removeTestEnvironmentEntryPoint"
	}
	finalizedBy "removeENMBuildArtifacts"
}

tasks.register('removeENMBuildArtifacts', Delete) {
	mustRunAfter 'removeTestEnvironmentEntryPoint'

	delete './build/tempdocker/enm'
	delete './build/tempdocker/clientsecret'
}
