package de.svws_nrw.module.reporting.utils;

public class SignaturUtils {

	private static final String DUMMY_SIGNATUR = "{\"cms\":\"MIIEOAYJKoZIhvcNAQcCoIIEKTCCBCUCAQExDTALBglghkgBZQMEAgEwCwYJKoZIhvcNAQcBoIICeTCCAnUwggIcoAMCAQIC"
			+ "CECyKKsXed2+MAoGCCqGSM49BAMCMIGgMQswCQYDVQQGEwJERTEMMAoGA1UECAwDTlJXMRQwEgYDVQQHDAtEw7xzc2VsZG9yZjEzMDEGA1UECgwqVEVTVCBNU0IgTlJXIENBIGbDvHIgRG"
			+ "lnaXRhbGUgU2NodWxzdGVtcGVsMTgwNgYDVQQDDC9URVNUIE1TQiBOUlcgUm9vdCBDQSBmw7xyIERpZ2l0YWxlIFNjaHVsc3RlbXBlbDAeFw0yNjA0MjAxMTQyMDFaFw0yNzA0MjAxMTQy"
			+ "MDFaMIGMMQswCQYDVQQGEwJERTEMMAoGA1UECAwDTlJXMQ8wDQYDVQQKDAYxMDAwMTIxSTBHBgNVBAMMQFN0w6RkdC4gR2VtZWluc2NoYWZ0c2dydW5kc2NodWxlIEFtIEZyaWVkZW5zcG"
			+ "FyayAtIFByaW1hcnN0dWZlIC0xEzARBgNVBAcMCkxldmVya3VzZW4wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR70r6Fn+Jwq09YoxW65ho3IATPkHA3lTUO9CTS5V2YaHtQ3W+fE0ac"
			+ "j/g3GF6YgOe0r0pl8GwF7N43h6kQ2M6To1IwUDAOBgNVHQ8BAf8EBAMCBsAwHQYDVR0OBBYEFHvum70Huqph2woHYWLmIiO2hvo1MB8GA1UdIwQYMBaAFC6Tg2ChQoyP1ucThIwPpAbbGu"
			+ "m5MAoGCCqGSM49BAMCA0cAMEQCICLYIQs8q/8E0eRqL5+HAVdxjjaEvWYQJDCevosZTcFLAiARYxjRj3jZ7xOLX2SyxSYo4W/5DgZH82kx0+9bZ6WiTDGCAYUwggGBAgEBMIGtMIGgMQsw"
			+ "CQYDVQQGEwJERTEMMAoGA1UECAwDTlJXMRQwEgYDVQQHDAtEw7xzc2VsZG9yZjEzMDEGA1UECgwqVEVTVCBNU0IgTlJXIENBIGbDvHIgRGlnaXRhbGUgU2NodWxzdGVtcGVsMTgwNgYDVQ"
			+ "QDDC9URVNUIE1TQiBOUlcgUm9vdCBDQSBmw7xyIERpZ2l0YWxlIFNjaHVsc3RlbXBlbAIIQLIoqxd53b4wCwYJYIZIAWUDBAIBoGkwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkq"
			+ "hkiG9w0BCQUxDxcNMjYwNTIzMjA0MTU4WjAvBgkqhkiG9w0BCQQxIgQgcKwrNrwMV8ssGOiAqF7adNmAdvT16iMsyYQYjQlqE6gwCgYIKoZIzj0EAwIESDBGAiEA3UxYCqYAH07vhGFJxK"
			+ "TyZfCVcpcpPpvDVylu2s+BpVECIQCQtZgp/Oc39pkKncLgLXGMp9T54hHNYyz0bkYf836Sog==\"}";

	/**
	 * Gibt die dummy-Signatur zurück. Wird später durch den echten Sigantur-Service-Aufruf bei IT.NRW ersetzt.
	 *
	 * @return die dummy-Signatur
	 */
	public final String sign() {
		return DUMMY_SIGNATUR;
	}
}
