CREATE DATABASE ${MariaDB_DATABASE};
CREATE USER ${MariaDB_USER} IDENTIFIED BY '${MariaDB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MariaDB_DATABASE}.* TO ${MariaDB_USER};
ALTER USER root@localhost IDENTIFIED BY '${MariaDB_ROOT_PASSWORD}';
