plugins {
	id 'svws.gradle.node.plugin'
}

task assembleClient(type: NpmRun) {
	dependsOn rootProject.npmPrepare
	dependsOn ':svws-openapi:assembleTranspiled'
	group = "build"
	args = ['build']
	inputs.files fileTree("$rootDir/svws-webclient/core").matching { exclude "build", "dist" },
		fileTree("$rootDir/svws-webclient/ui").matching { exclude "build", "dist", ".histoire" },
		fileTree("$projectDir").matching { exclude "build" }
	outputs.dir file("$buildDir/output")
}

assemble.dependsOn assembleClient

task lint(type: NpmRun) {
	dependsOn assembleClient
	group = "build"
	args = ["lint-tsc"]
}

task doZip(type: Zip) {
	dependsOn assembleClient
	archiveFileName = "SVWS-Client.zip"
	destinationDirectory = file("$buildDir")
	from "$buildDir/output"
}

build.dependsOn lint
build.dependsOn doZip

task cleanClient(type: Delete) {
	delete file("$buildDir/output")
}

clean.dependsOn cleanClient
