[# th:if="${LehrerStundenplaene.isEmpty()}"]
    Lehrer-Stundenplaene-Kombiniert_[(${ #strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
[/]
[# th:if="${!LehrerStundenplaene.isEmpty()}"]
    [# th:each="lehrerstundenplan,iterState : ${LehrerStundenplaene}"]
        [# th:if="${iterState.first && (LehrerStundenplaene.size() == 1)}"]
            Lehrer-Stundenplan-Kombiniert_[(${ #strings.replace(#strings.replace(lehrerstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]_[(${ #strings.replace(lehrerstundenplan.lehrer().kuerzel(), ' ', '_') })]_[(${ #dates.format(#dates.createNow(), 'yyyyMMdd-HHmm') })]
        [/]
        [# th:if="${iterState.first && (LehrerStundenplaene.size() > 1)}"]
            Lehrer-Stundenplaene-Kombiniert_[(${ #strings.replace(#strings.replace(lehrerstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
        [/]
    [/]
[/]
