[# th:with="stundenplaene = ${RaeumeStundenplaene}, anzahl = ${#lists.size(stundenplaene)}, schuljahresabschnitt = ${#strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-')}"]
    [# th:if="${anzahl == 1}"]
        Raum-Stundenplan_[(${schuljahresabschnitt})]_[(${ #strings.replace(stundenplaene[0].raum().kuerzel(), ' ', '_') })]
    [/]
    [# th:if="${anzahl != 1}"]
        Raum-Stundenplaene_[(${schuljahresabschnitt})]
    [/]
[/]
[# th:if="${VorlageParameter.get('dateinameMitZeitstempel')}"]_[(${ #aktuell.formatiert('yyyyMMdd-HHmm') })][/]
