[# th:with="stundenplaene = ${LehrerStundenplaene}, anzahl = ${#lists.size(stundenplaene)}, schuljahresabschnitt = ${#strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-')}"]
    [# th:if="${anzahl == 1}"]
        Lehrer-Stundenplan-Kombiniert_[(${schuljahresabschnitt})]_[(${ #strings.replace(stundenplaene[0].lehrer().kuerzel(), ' ', '_') })]
    [/]
    [# th:if="${anzahl != 1}"]
        Lehrer-Stundenplaene-Kombiniert_[(${schuljahresabschnitt})]
    [/]
[/]
[# th:if="${VorlageParameter.get('dateinameMitZeitstempel')}"]_[(${ #dates.format(#aktuell.jetztAlsDate(), 'yyyyMMdd-HHmm') })][/]
