[# th:with="stundenplaene = ${LehrerStundenplaene}, anzahl = ${#lists.size(stundenplaene)}, schuljahresabschnitt = ${#strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-')}"]
    [# th:if="${anzahl == 1}"]
        Lehrer-Stundenplan_[(${schuljahresabschnitt})]_[(${ #strings.replace(stundenplaene[0].lehrer().kuerzel(), ' ', '_') })]
    [/]
    [# th:if="${anzahl != 1}"]
        Lehrer-Stundenplaene_[(${schuljahresabschnitt})]
    [/]
[/]
[# th:if="${VorlageParameter.get('dateinameMitZeitstempel')}"]_[(${ #aktuell.formatiert('yyyyMMdd-HHmm') })][/]
