[# th:if="${SchuelerStundenplaene.isEmpty()}"]
    Schueler-Stundenplaene_[(${ #strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
[/]
[# th:if="${!SchuelerStundenplaene.isEmpty()}"]
    [# th:each="schuelerstundenplan,iterState : ${SchuelerStundenplaene}"]
        [# th:if="${iterState.first && (SchuelerStundenplaene.size() == 1)}"]
            Schueler-Stundenplan_[(${ #strings.replace(#strings.replace(schuelerstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
            _[(${ #strings.replace(schuelerstundenplan.schueler().nachname(), ' ', '_') })]
            __[(${ #strings.replace(schuelerstundenplan.schueler().vorname(), ' ', '_') })]
            _([(${ schuelerstundenplan.schueler().id() })])
            _[(${ #dates.format(#dates.createNow(), 'yyyyMMdd-HHmm') })]
        [/]
        [# th:if="${iterState.first && (SchuelerStundenplaene.size() > 1)}"]
            Schueler-Stundenplaene_[(${ #strings.replace(#strings.replace(schuelerstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
        [/]
    [/]
[/]
