[# th:if="${KlassenStundenplaene.isEmpty()}"]
    Klassen-Stundenplaene_[(${ #strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
[/]
[# th:if="${!KlassenStundenplaene.isEmpty()}"]
    [# th:each="klassenstundenplan,iterState : ${KlassenStundenplaene}"]
        [# th:if="${iterState.first && (KlassenStundenplaene.size() == 1)}"]
            Klassen-Stundenplan_[(${ #strings.replace(#strings.replace(klassenstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]_[(${ #strings.replace(klassenstundenplan.klasse().kuerzel(), ' ', '_') })]_[(${ #dates.format(#dates.createNow(), 'yyyyMMdd-HHmm') })]
        [/]
        [# th:if="${iterState.first && (KlassenStundenplaene.size() > 1)}"]
            Klassen-Stundenplaene_[(${ #strings.replace(#strings.replace(klassenstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
        [/]
    [/]
[/]
