[# th:if="${FaecherStundenplaene.isEmpty()}"]
    Fach-Stundenplaene_[(${ #strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
[/]
[# th:if="${!FaecherStundenplaene.isEmpty()}"]
    [# th:each="fachstundenplan,iterState : ${FaecherStundenplaene}"]
        [# th:if="${iterState.first && (FaecherStundenplaene.size() == 1)}"]
            Fach-Stundenplan_[(${ #strings.replace(#strings.replace(fachstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]_[(${ #strings.replace(fachstundenplan.fach().kuerzel(), ' ', '_') })]_[(${ #dates.format(#dates.createNow(), 'yyyyMMdd-HHmm') })]
        [/]
        [# th:if="${iterState.first && (FaecherStundenplaene.size() > 1)}"]
            Fach-Stundenplaene_[(${ #strings.replace(#strings.replace(fachstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
        [/]
    [/]
[/]
