[# th:if="${RaeumeStundenplaene.isEmpty()}"]
    Raum-Stundenplaene_[(${ #strings.replace(#strings.replace(Schule.auswahlSchuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
[/]
[# th:if="${!RaeumeStundenplaene.isEmpty()}"]
    [# th:each="raumstundenplan,iterState : ${RaeumeStundenplaene}"]
        [# th:if="${iterState.first && (RaeumeStundenplaene.size() == 1)}"]
            Raum-Stundenplan_[(${ #strings.replace(#strings.replace(raumstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]_[(${ #strings.replace(raumstundenplan.raum().kuerzel(), ' ', '_') })]_[(${ #dates.format(#dates.createNow(), 'yyyyMMdd-HHmm') })]
        [/]
        [# th:if="${iterState.first && (RaeumeStundenplaene.size() > 1)}"]
            Raum-Stundenplaene_[(${ #strings.replace(#strings.replace(raumstundenplan.stundenplan().schuljahresabschnitt().textSchuljahresabschnittKurz(), '.', ''), '/', '-') })]
        [/]
    [/]
[/]

