import { AppContext } from "@ui/AppContext";
import { AbschnittStateKey } from "@ui/states/AbschnittState";
import { AuskunftStateKey } from "@ui/states/AuskunftState";
import { BenutzerStateKey } from "@ui/states/BenutzerState";
import { ConfigStateKey } from "@ui/states/ConfigState";
import { GostKlausurplanungStateKey } from "@ui/states/GostKlausurplanungState";
import { GostLaufbahnplanungStateKey } from "@ui/states/GostLaufbahnplanungState";
import { BeschaeftigungsartenStateKey } from "@ui/states/kataloge/BeschaeftigungsartenState";
import { BetriebeStateKey } from "@ui/states/kataloge/BetriebeState";
import { EntlassgruendeStateKey } from "@ui/states/kataloge/EntlassgruendeState";
import { LeitungsfunktionenStateKey } from "@ui/states/kataloge/LeitungsfunktionenState";
import { OrteStateKey } from "@ui/states/kataloge/OrteState";
import { NotenmodulStateKey } from "@ui/states/NotenmodulState";
import { NotificationsStateKey } from "@ui/states/NotificationsState";
import { ReportingStateKey } from "@ui/states/ReportingState";
import { SchuleStateKey } from "@ui/states/SchuleState";
import { ServerStateKey } from "@ui/states/ServerState";
import { StatistikStateKey } from "@ui/states/statistik/StatistikState";
import { UvStateKey } from "@ui/states/UvState";
import { WiedervorlageStateKey } from "@ui/states/WiedervorlageState";

import { abschnittStateImpl } from "./AbschnittStateImpl";
import { auskunftStateImpl } from "./AuskunftStateImpl";
import { benutzerStateImpl } from "./BenutzerStateImpl";
import { configStateImpl } from "./ConfigStateImpl";
import { gostKlausurplanungStateImpl } from "./GostKlausurplanungStateImpl";
import { gostLaufbahnplanungStateImpl } from "./GostLaufbahnplanungStateImpl";
import { beschaeftigungsartenStateImpl } from "./kataloge/BeschaeftigungsartenStateImpl";
import { betriebeStateImpl } from "./kataloge/BetriebeStateImpl";
import { entlassgruendeStateImpl } from "./kataloge/EntlassgruendeStateImpl";
import { leitungsfunktionenStateImpl } from "./kataloge/LeitungsfunktionenStateImpl";
import { orteStateImpl } from "./kataloge/OrteStateImpl";
import { KlassenAuswahlStateKey } from "./klassen/KlassenAuswahlState";
import { klassenAuswahlStateImpl } from "./klassen/KlassenAuswahlStateImpl";
import { KurseAuswahlStateKey } from "./kurse/KurseAuswahlState";
import { kurseAuswahlStateImpl } from "./kurse/KurseAuswahlStateImpl";
import { LehrerAuswahlStateKey } from "./lehrer/LehrerAuswahlState";
import { lehrerAuswahlStateImpl } from "./lehrer/LehrerAuswahlStateImpl";
import { notenmodulStateImpl } from "./NotenmodulStateImpl";
import { notificationStateImpl } from "./NotificationsStateImpl";
import { reportingStateImpl } from "./ReportingStateImpl";
import { SchuelerAuswahlStateKey } from "./schueler/SchuelerAuswahlState";
import { schuelerAuswahlStateImpl } from "./schueler/SchuelerAuswahlStateImpl";
import { schuleStateImpl } from "./SchuleStateImpl";
import { serverStateImpl } from "./ServerStateImpl";
import { statistikStateImpl } from "./statistik/StatistikStateImpl";
import { uvStateImpl } from "./UvStateImpl";
import { wiedervorlageStateImpl } from "./wiedervorlage/WiedervorlageStateImpl";


export function registerStates(): void {
	const context = AppContext.instance;

	context.provide(BenutzerStateKey, benutzerStateImpl);
	context.provide(ConfigStateKey, configStateImpl);
	context.provide(AbschnittStateKey, abschnittStateImpl);
	context.provide(SchuleStateKey, schuleStateImpl);
	context.provide(SchuelerAuswahlStateKey, schuelerAuswahlStateImpl);
	context.provide(LehrerAuswahlStateKey, lehrerAuswahlStateImpl);
	context.provide(ServerStateKey, serverStateImpl);
	context.provide(ReportingStateKey, reportingStateImpl);
	context.provide(WiedervorlageStateKey, wiedervorlageStateImpl);
	context.provide(AuskunftStateKey, auskunftStateImpl);
	context.provide(KlassenAuswahlStateKey, klassenAuswahlStateImpl);
	context.provide(KurseAuswahlStateKey, kurseAuswahlStateImpl);
	context.provide(GostLaufbahnplanungStateKey, gostLaufbahnplanungStateImpl);
	context.provide(GostKlausurplanungStateKey, gostKlausurplanungStateImpl);
	context.provide(UvStateKey, uvStateImpl);
	context.provide(NotenmodulStateKey, notenmodulStateImpl);
	context.provide(NotificationsStateKey, notificationStateImpl);
	context.provide(OrteStateKey, orteStateImpl);
	context.provide(LeitungsfunktionenStateKey, leitungsfunktionenStateImpl);
	context.provide(BeschaeftigungsartenStateKey, beschaeftigungsartenStateImpl);
	context.provide(BetriebeStateKey, betriebeStateImpl);
	context.provide(EntlassgruendeStateKey, entlassgruendeStateImpl);
	context.provide(StatistikStateKey, statistikStateImpl);
}
