[# th:if="${Kurse.isEmpty()}"]
    Kurs-Liste-Schueler-Leistungsdaten
[/]
[# th:if="${!Kurse.isEmpty()}"]
    [# th:each="kurs,iterState : ${Kurse}"]
        [# th:if="${iterState.first && (Kurse.size() == 1)}"]
            Kurs-Liste-Schueler-Leistungsdaten_[(${#strings.replace(#strings.replace(kurs.auflistungJahrgaenge(), ' ', '_'), ',', '-')})]-[(${#strings.replace(kurs.kuerzel(), ' ', '_')})]
		[/]
		[# th:if="${iterState.first && (Kurse.size() > 1)}"]
			Kurs-Liste-Schueler-Leistungsdaten_[(${ #dates.format(#dates.createNow(), 'yyyyMMdd-HHmm') })]
		[/]
    [/]
[/]
