import type { WritableComputedRef } from "vue";
import type { GostKursplanungSchuelerFilter } from "./GostKursplanungSchuelerFilter";
import type { ApiStatus } from "~/components/ApiStatus";
import type { GostBlockungKurs } from "@core/core/data/gost/GostBlockungKurs";
import type { GostBlockungKursLehrer } from "@core/core/data/gost/GostBlockungKursLehrer";
import type { GostBlockungRegelUpdate } from "@core/core/data/gost/GostBlockungRegelUpdate";
import type { GostBlockungSchiene } from "@core/core/data/gost/GostBlockungSchiene";
import type { GostBlockungsergebnisKurs } from "@core/core/data/gost/GostBlockungsergebnisKurs";
import type { GostBlockungsergebnisKursSchuelerZuordnungUpdate } from "@core/core/data/gost/GostBlockungsergebnisKursSchuelerZuordnungUpdate";
import type { GostJahrgangsdaten } from "@core/core/data/gost/GostJahrgangsdaten";
import type { GostStatistikFachwahl } from "@core/core/data/gost/GostStatistikFachwahl";
import type { LehrerListeEintrag } from "@core/core/data/lehrer/LehrerListeEintrag";
import type { GostHalbjahr } from "@core/core/types/gost/GostHalbjahr";
import type { GostBlockungsdatenManager } from "@core/core/utils/gost/GostBlockungsdatenManager";
import type { GostBlockungsergebnisManager } from "@core/core/utils/gost/GostBlockungsergebnisManager";
import type { GostFaecherManager } from "@core/core/utils/gost/GostFaecherManager";
import type { JavaSet } from "@core/java/util/JavaSet";

export interface GostKursplanungProps {
	getDatenmanager: () => GostBlockungsdatenManager;
	getKursauswahl: () => JavaSet<number>,
	setKursauswahl: (value: JavaSet<number>) => void;
	getErgebnismanager: () => GostBlockungsergebnisManager;
	addBlockung: () => Promise<void>;
	restoreBlockung: () => Promise<void>;
	regelnUpdate: (update: GostBlockungRegelUpdate) => Promise<void>;
	updateKursSchienenZuordnung: (idKurs: number, idSchieneAlt: number, idSchieneNeu: number) => Promise<boolean>;
	patchSchiene: (data: Partial<GostBlockungSchiene>, id: number) => Promise<void>;
	addSchiene: () => Promise<GostBlockungSchiene | undefined>;
	removeSchiene: (s: GostBlockungSchiene) => Promise<GostBlockungSchiene | undefined>;
	patchKurs: (data: Partial<GostBlockungKurs>, kurs_id: number) => Promise<void>;
	addKurs: (fach_id: number, kursart_id: number) => Promise<GostBlockungKurs | undefined>;
	removeKurse: (ids: Iterable<number>) => Promise<void>;
	combineKurs: (kurs1: GostBlockungKurs, fach2: GostBlockungKurs | GostBlockungsergebnisKurs | undefined | null) => Promise<void>;
	splitKurs: (kurs: GostBlockungKurs) => Promise<void>;
	addKursLehrer: (kurs_id: number, lehrer_id: number) => Promise<GostBlockungKursLehrer | undefined>;
	removeKursLehrer: (kurs_id: number, lehrer_id: number) => Promise<void>;
	addSchieneKurs: (kurs: GostBlockungKurs) => Promise<void>;
	removeSchieneKurs: (kurs: GostBlockungKurs) => Promise<void>;
	ergebnisAbleiten: () => Promise<void>;
	ergebnisHochschreiben: () => Promise<void>;
	ergebnisAktivieren: () => Promise<boolean>;
	ergebnisSynchronisieren: () => Promise<void>;
	jahrgangsdaten: () => GostJahrgangsdaten;
	kurssortierung: WritableComputedRef<'fach' | 'kursart'>;
	existiertSchuljahresabschnitt: boolean;
	hatBlockung: boolean;
	hatErgebnis: boolean;
	schuelerFilter: () => GostKursplanungSchuelerFilter;
	faecherManager: GostFaecherManager;
	halbjahr: GostHalbjahr;
	mapLehrer: Map<number, LehrerListeEintrag>;
	mapFachwahlStatistik: () => Map<number, GostStatistikFachwahl>;
	apiStatus: ApiStatus;
	updateKursSchuelerZuordnungen: (update: GostBlockungsergebnisKursSchuelerZuordnungUpdate) => Promise<boolean>;
	idSchueler: () => number;
	// Config
	zeigeSchienenbezeichnungen: () => boolean;
	setZeigeSchienenbezeichnungen: (value: boolean) => Promise<void>;
	blockungstabelleHidden: () => 'nichts' | 'alles' | 'schienen';
	setBlockungstabelleHidden: (value: 'nichts' | 'alles' | 'schienen') => Promise<void>;
	fixierteVerschieben: () => boolean;
	setFixierteVerschieben: (value: boolean) => Promise<void>;
	inZielkursFixieren: () => boolean;
	setInZielkursFixieren: (value: boolean) => Promise<void>;
}
