[# th:with="schueler = ${Schueler}, anzahl = ${#lists.size(schueler)}"]
    [# th:if="${anzahl == 0}"]
        GOSt-Laufbahnplanung-Wahlboegen
    [/]
    [# th:if="${anzahl == 1}"]
        GOSt-Laufbahnwahl_Abi[(${ schueler[0].gostLaufbahnplanung().abiturjahr() + '_' + #strings.replace(schueler[0].gostLaufbahnplanung().folgeAuswahlGOStHalbjahr(), '.', '') + '_' + #strings.replace(schueler[0].nachname(), ' ', '_') + '__' + #strings.replace(schueler[0].vorname(), ' ', '_') + '_(' + schueler[0].id() + ')' })]
    [/]
    [# th:if="${anzahl > 1}"]
        GOSt-Laufbahnwahl_Abi[(${ schueler[0].gostLaufbahnplanung().abiturjahr() + '_' + #strings.replace(schueler[0].gostLaufbahnplanung().folgeAuswahlGOStHalbjahr(), '.', '') })]
    [/]
[/]
[# th:if="${VorlageParameter.get('dateinameMitZeitstempel')}"]_[(${ #aktuell.formatiert('yyyyMMdd-HHmm') })][/]
