// Components
export type { AbschnittAuswahlDaten, AbschnittAuswahlProps } from './components/abschnittauswahl/AbschnittAuswahlProps'
export { default as AbschnittAuswahl } from './components/abschnittauswahl/AbschnittAuswahl.vue'
export type { SchuelerLaufbahnplanungProps } from './components/gost/laufbahnplanung/SSchuelerLaufbahnplanungProps'
export { default as SSchuelerLaufbahnplanung } from './components/gost/laufbahnplanung/SSchuelerLaufbahnplanung.vue'
export type { StundenplanAnsichtProps, StundenplanAnsichtDragData, StundenplanAnsichtDropZone } from './components/stundenplan/StundenplanAnsichtProps'
export type { StundenplanAnsichtLehrerProps } from './components/stundenplan/StundenplanAnsichtLehrerProps'
export type { StundenplanAnsichtSchuelerProps } from './components/stundenplan/StundenplanAnsichtSchuelerProps'
export type { StundenplanAnsichtKlasseProps } from './components/stundenplan/StundenplanAnsichtKlasseProps'
export type { StundenplanAnsichtFachProps } from './components/stundenplan/StundenplanAnsichtFachProps'
export type { StundenplanAnsichtRaumProps } from './components/stundenplan/StundenplanAnsichtRaumProps'
export { default as StundenplanAnsicht } from './components/stundenplan/StundenplanAnsicht.vue'
export { default as StundenplanAnsichtLehrer } from './components/stundenplan/StundenplanAnsichtLehrer.vue'
export { default as StundenplanAnsichtSchueler } from './components/stundenplan/StundenplanAnsichtSchueler.vue'
export { default as StundenplanAnsichtKlasse } from './components/stundenplan/StundenplanAnsichtKlasse.vue'
export { default as StundenplanAnsichtFach } from './components/stundenplan/StundenplanAnsichtFach.vue'
export { default as StundenplanAnsichtRaum } from './components/stundenplan/StundenplanAnsichtRaum.vue'
export type { StundenplanAuswahlProps } from './components/stundenplan/StundenplanAuswahlProps'
export { default as StundenplanAuswahl } from './components/stundenplan/StundenplanAuswahl.vue'
export { default as FehlermeldungModal } from './components/modals/FehlermeldungModal.vue'