// Components
export type { AbschnittAuswahlDaten, AbschnittAuswahlProps } from './components/abschnittauswahl/AbschnittAuswahlProps'
export { default as AbschnittAuswahl } from './components/abschnittauswahl/AbschnittAuswahl.vue'
export type { SchuelerLaufbahnplanungProps } from './components/gost/laufbahnplanung/SSchuelerLaufbahnplanungProps'
export { default as SSchuelerLaufbahnplanung } from './components/gost/laufbahnplanung/SSchuelerLaufbahnplanung.vue'
export type { StundenplanAnsichtProps, StundenplanAnsichtDragData, StundenplanAnsichtDropZone } from './components/stundenplan/StundenplanAnsichtProps'
export type { StundenplanLehrerProps } from './components/stundenplan/StundenplanLehrerProps'
export type { StundenplanSchuelerProps } from './components/stundenplan/StundenplanSchuelerProps'
export type { StundenplanKlasseProps } from './components/stundenplan/StundenplanKlasseProps'
export type { StundenplanFachProps } from './components/stundenplan/StundenplanFachProps'
export type { StundenplanRaumProps } from './components/stundenplan/StundenplanRaumProps'
export { default as StundenplanAnsicht } from './components/stundenplan/StundenplanAnsicht.vue'
export { default as StundenplanLehrer } from './components/stundenplan/StundenplanLehrer.vue'
export { default as StundenplanSchueler } from './components/stundenplan/StundenplanSchueler.vue'
export { default as StundenplanKlasse } from './components/stundenplan/StundenplanKlasse.vue'
export { default as StundenplanFach } from './components/stundenplan/StundenplanFach.vue'
export { default as StundenplanRaum } from './components/stundenplan/StundenplanRaum.vue'
export type { StundenplanAuswahlProps } from './components/stundenplan/StundenplanAuswahlProps'
export { default as StundenplanAuswahl } from './components/stundenplan/StundenplanAuswahl.vue'
export { default as FehlermeldungModal } from './components/modals/FehlermeldungModal.vue'