plugins {
	id 'svws.gradle.node.plugin'
}

sourcesJar.dependsOn project(':svws-openapi').tasks.assembleTranspiled

tasks.register('assembleCore', NpmRun) {
	dependsOn rootProject.npmPrepare, project(':svws-openapi').tasks.assemble
	group = "build"
	args = ['build']
	inputs.files fileTree("$projectDir").matching { exclude "build", "dist" }
	outputs.dir file("$projectDir/dist")
}

tasks.register('cleanCore', Delete) {
	delete file("$projectDir/dist")
}

clean.dependsOn cleanCore

tasks.register('testCore', NpmRun) {
	group = "svws"
	dependsOn ':svws-webclient:core:assemble'
	inputs.files file("$projectDir/src")
	outputs.dir file("$projectDir/build/coverage")
	args = ['test:coverage']
	doFirst {
		mkdir file("$projectDir/build/coverage")
	}
}

test.dependsOn testCore

tasks.register('publishNpmInternalRelease', NpmPublish) {
	dependsOn assemble
	group = "publishing"
	npmrc = "$rootDir/.npmrc.nexus"
	repository = "https://artifactory.svws-nrw.de/repository/npm-private/"
	actor = project.ext.getNexusActor()
	token = project.ext.getNexusToken()
	scopePublic = false
}

tasks.register('publishNpmExternalRelease', NpmPublish) {
	dependsOn assemble
	group = "publishing"
	npmrc = "$rootDir/.npmrc.npm"
	repository = "https://registry.npmjs.org/"
	token = project.ext.getNpmToken()
	scopePublic = true
	tokenOnly = true
}
