package de.nrw.schule.svws.db.dto;

import java.util.HashMap;

import de.nrw.schule.svws.db.dto.dev.coretypes.DevDTOKursFortschreibungsart;
import de.nrw.schule.svws.db.dto.dev.coretypes.DevDTONote;
import de.nrw.schule.svws.db.dto.dev.coretypes.DevDTOPersonalTyp;
import de.nrw.schule.svws.db.dto.dev.gost.DevDTOGostJahrgangBeratungslehrer;
import de.nrw.schule.svws.db.dto.dev.gost.DevDTOGostJahrgangFachkombinationen;
import de.nrw.schule.svws.db.dto.dev.gost.DevDTOGostJahrgangFaecher;
import de.nrw.schule.svws.db.dto.dev.gost.DevDTOGostJahrgangsdaten;
import de.nrw.schule.svws.db.dto.dev.gost.DevDTOGostSchueler;
import de.nrw.schule.svws.db.dto.dev.gost.DevDTOGostSchuelerFachbelegungen;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenKalenderinformationen;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenKursklausuren;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenNtaZeiten;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenRaeume;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenRaeumeStunden;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenRaeumeStundenAufsichten;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenSchuelerklausuren;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenSchuelerklausurenRaeumeStunden;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenTermine;
import de.nrw.schule.svws.db.dto.dev.gost.klausurplanung.DevDTOGostKlausurenVorgaben;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockung;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungKurs;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungKurslehrer;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungRegel;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungRegelParameter;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungSchiene;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungZwischenergebnis;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungZwischenergebnisKursSchiene;
import de.nrw.schule.svws.db.dto.dev.gost.kursblockung.DevDTOGostBlockungZwischenergebnisKursSchueler;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOSchildAuswahlFilter;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOSchildVerwaltung;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOSchuelerIndividuelleGruppe;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOSchuelerIndividuelleGruppeSchueler;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOSchuelerReportvorlagen;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOSchuelerWiedervorlage;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOTextExportVorlagen;
import de.nrw.schule.svws.db.dto.dev.schild.DevDTOZuordnungReportvorlagen;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzer;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzerAllgemein;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzerMail;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzergruppe;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzergruppenKompetenz;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOBenutzergruppenMitglied;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOKatalogBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOKatalogBenutzerKompetenzGruppe;
import de.nrw.schule.svws.db.dto.dev.schild.benutzer.DevDTOProtokollLogin;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOBeschaeftigungsart;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOFachgliederungen;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOFachklassen;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOKatalogZertifikate;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOSchuelerBKAbschluss;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOSchuelerBKFach;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOSchuelerZuweisung;
import de.nrw.schule.svws.db.dto.dev.schild.berufskolleg.DevDTOZertifikate;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOErzieherDatenschutz;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOErzieherLernplattform;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOErzieherart;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOErzieherfunktion;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOSchuelerErzieherAdresse;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOSchuelerTelefon;
import de.nrw.schule.svws.db.dto.dev.schild.erzieher.DevDTOTelefonArt;
import de.nrw.schule.svws.db.dto.dev.schild.faecher.DevDTOFach;
import de.nrw.schule.svws.db.dto.dev.schild.faecher.DevDTOFachTeilleistungsarten;
import de.nrw.schule.svws.db.dto.dev.schild.faecher.DevDTOFachgruppen;
import de.nrw.schule.svws.db.dto.dev.schild.faecher.DevDTOFaecherKatalog;
import de.nrw.schule.svws.db.dto.dev.schild.faecher.DevDTOFaecherKatalogKeys;
import de.nrw.schule.svws.db.dto.dev.schild.faecher.DevDTOFaecherKatalogSchulformen;
import de.nrw.schule.svws.db.dto.dev.schild.gost.DevDTOFaecherNichtMoeglicheKombination;
import de.nrw.schule.svws.db.dto.dev.schild.grundschule.DevDTOAnkreuzdaten;
import de.nrw.schule.svws.db.dto.dev.schild.grundschule.DevDTOAnkreuzfloskeln;
import de.nrw.schule.svws.db.dto.dev.schild.grundschule.DevDTOKindergarten;
import de.nrw.schule.svws.db.dto.dev.schild.grundschule.DevDTOSchuelerAnkreuzfloskeln;
import de.nrw.schule.svws.db.dto.dev.schild.impexp.DevDTOEigeneImporte;
import de.nrw.schule.svws.db.dto.dev.schild.impexp.DevDTOEigeneImporteFelder;
import de.nrw.schule.svws.db.dto.dev.schild.impexp.DevDTOEigeneImporteTabellen;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOAnsprechpartnerAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOFahrschuelerart;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOFloskelgruppen;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOFloskeln;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOHaltestellen;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKatalogAdressart;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKatalogAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKatalogAufsichtsbereich;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKatalogDatenschutz;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKatalogRaum;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKonfession;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOKursarten;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOOrt;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOOrtsteil;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOSchuleNRW;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOSchulfunktion;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOSchwerpunkt;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOTextDateien;
import de.nrw.schule.svws.db.dto.dev.schild.katalog.DevDTOVermerkArt;
import de.nrw.schule.svws.db.dto.dev.schild.klassen.DevDTOKlassen;
import de.nrw.schule.svws.db.dto.dev.schild.klassen.DevDTOKlassenLeitung;
import de.nrw.schule.svws.db.dto.dev.schild.klassen.DevDTOKlassenartenKatalogKeys;
import de.nrw.schule.svws.db.dto.dev.schild.kurse.DevDTOKurs;
import de.nrw.schule.svws.db.dto.dev.schild.kurse.DevDTOKursLehrer;
import de.nrw.schule.svws.db.dto.dev.schild.kurse.DevDTOKursSchueler;
import de.nrw.schule.svws.db.dto.dev.schild.kurse.DevDTOKursartenKatalogKeys;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrer;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerAbschnittsdaten;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerAnrechnungsstunde;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerDatenschutz;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerEntlastungsstunde;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerFoto;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerFunktion;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerLehramt;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerLehramtBefaehigung;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerLehramtFachrichtung;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerLeitungsfunktionKeys;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerLernplattform;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOLehrerMehrleistung;
import de.nrw.schule.svws.db.dto.dev.schild.lehrer.DevDTOSchulleitung;
import de.nrw.schule.svws.db.dto.dev.schild.personengruppen.DevDTOPersonengruppen;
import de.nrw.schule.svws.db.dto.dev.schild.personengruppen.DevDTOPersonengruppenPersonen;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOEinschulungsart;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOEntlassarten;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOFoerderschwerpunkt;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchueler;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerAbgaenge;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerDatenschutz;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerFehlstunden;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerFoerderempfehlung;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerFoto;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerGrundschuldaten;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerKAoADaten;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerLeistungsdaten;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerLernabschnittsdaten;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerLernplattform;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerMerkmale;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerPSFachBemerkungen;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerSprachenfolge;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerSprachpruefungen;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerTeilleistung;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerVermerke;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSchuelerZP10;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOSportbefreiung;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.DevDTOTeilleistungsarten;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.abitur.DevDTOSchuelerAbitur;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.abitur.DevDTOSchuelerAbiturFach;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.fhr.DevDTOSchuelerFHR;
import de.nrw.schule.svws.db.dto.dev.schild.schueler.fhr.DevDTOSchuelerFHRFach;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOAbteilungen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOAbteilungsKlassen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOAlleJahrgaengeKeys;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOAlleSchulformen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOAllgemeineMerkmaleKatalogKeys;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOBerufskollegAnlagen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOBerufskollegBerufsebenen1;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOBerufskollegBerufsebenen2;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOBerufskollegBerufsebenen3;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOBerufskollegFachklassenKeys;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOEigeneSchule;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOEigeneSchuleKAoADaten;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOEinschulungsartenKatalogKeys;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOHerkunft;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOHerkunftSchulformen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOHerkunftsart;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOHerkunftsartSchulformen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOJahrgang;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOMerkmale;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOOrganisationsformenKatalogKeys;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOSchulformen;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOSchuljahresabschnitte;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOSchultexte;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOStundentafel;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOStundentafelFaecher;
import de.nrw.schule.svws.db.dto.dev.schild.schule.DevDTOTeilstandorte;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOKatalogPausenzeit;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOKatalogZeitraster;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplan;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanAufsichtsbereich;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanPausenaufsichten;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanPausenaufsichtenBereiche;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanPausenzeit;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanRaum;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanUnterricht;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanUnterrichtLehrer;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanUnterrichtRaum;
import de.nrw.schule.svws.db.dto.dev.schild.stundenplan.DevDTOStundenplanZeitraster;
import de.nrw.schule.svws.db.dto.dev.schueler.DevDTOSchuelerStatus;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOHerkunftKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOHerkunftsartKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOKAoAAnschlussoptionKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOKAoABerufsfeldKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOKAoAKategorieKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOKAoAMerkmalKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOKAoASBOEB4Keys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOKAoAZusatzmerkmalKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTONationalitaetenKeys;
import de.nrw.schule.svws.db.dto.dev.schule.DevDTOReligionKeys;
import de.nrw.schule.svws.db.dto.dev.svws.auth.DevDTOCredentials;
import de.nrw.schule.svws.db.dto.dev.svws.auth.DevDTOCredentialsLernplattformen;
import de.nrw.schule.svws.db.dto.dev.svws.auth.DevDTOLernplattformen;
import de.nrw.schule.svws.db.dto.dev.svws.auth.DevDTOSchuleCredentials;
import de.nrw.schule.svws.db.dto.dev.svws.client.DevDTOClientKonfigurationBenutzer;
import de.nrw.schule.svws.db.dto.dev.svws.client.DevDTOClientKonfigurationGlobal;
import de.nrw.schule.svws.db.dto.dev.svws.dav.DevDTODavRessource;
import de.nrw.schule.svws.db.dto.dev.svws.dav.DevDTODavRessourceCollection;
import de.nrw.schule.svws.db.dto.dev.svws.dav.DevDTODavRessourceCollectionsACL;
import de.nrw.schule.svws.db.dto.dev.svws.dav.DevDTODavSyncTokenLehrer;
import de.nrw.schule.svws.db.dto.dev.svws.dav.DevDTODavSyncTokenSchueler;
import de.nrw.schule.svws.db.dto.dev.svws.db.DevDTOCoreTypeVersion;
import de.nrw.schule.svws.db.dto.dev.svws.db.DevDTODBAutoInkremente;
import de.nrw.schule.svws.db.dto.dev.svws.db.DevDTODBVersion;
import de.nrw.schule.svws.db.dto.dev.svws.enm.DevDTOEnmLeistungsdaten;
import de.nrw.schule.svws.db.dto.dev.svws.enm.DevDTOEnmLernabschnittsdaten;
import de.nrw.schule.svws.db.dto.dev.views.benutzer.DevDTOViewBenutzer;
import de.nrw.schule.svws.db.dto.dev.views.benutzer.DevDTOViewBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.dev.views.benutzer.DevDTOViewBenutzerdetails;
import de.nrw.schule.svws.db.dto.dev.views.gost.DevDTOViewGostSchuelerAbiturjahrgang;

/**
 * Diese Klasse dient als Verzeichnis aller Datenbank-DTO-Klassen.
 * Sie wurde automatisch per Skript generiert und sollte nicht verändert werden,
 * da sie aufgrund von Änderungen am DB-Schema ggf. neu generiert und überschrieben wird.
 */
public class DevDTOs {

    /** Enthält das Mapping der Namen aller Java-DTO-Klassen für die SVWS-DB zu den entsprechenden Java-DTO-Klassen. */
    private static HashMap<String, Class<? extends Object>> mapDTOName2DTOClass = null;

    /** Enthält das Mapping der Datenbank-Tabellennamen zu den zugehörigen Java-DTO-Klassen für die SVWS-DB. */
    private static HashMap<String, Class<? extends Object>> mapTablename2DTOClass = null;


    /**
     * Gibt das Mapping der Datenbank-Tabellennamen zu den zugehörigen Java-DTO-Klassen für die SVWS-DB zurück.
     *
     * @return eine Hashmap mit dem Mapping
     */
     private static final HashMap<String, Class<? extends Object>> getMapDTOName2DTOClass() {
         if (mapDTOName2DTOClass == null) {
             mapDTOName2DTOClass = new HashMap<>();
             mapDTOName2DTOClass.put(DevDTOKursFortschreibungsart.class.getSimpleName(),DevDTOKursFortschreibungsart.class);
             mapDTOName2DTOClass.put(DevDTONote.class.getSimpleName(),DevDTONote.class);
             mapDTOName2DTOClass.put(DevDTOPersonalTyp.class.getSimpleName(),DevDTOPersonalTyp.class);
             mapDTOName2DTOClass.put(DevDTOGostJahrgangBeratungslehrer.class.getSimpleName(),DevDTOGostJahrgangBeratungslehrer.class);
             mapDTOName2DTOClass.put(DevDTOGostJahrgangFachkombinationen.class.getSimpleName(),DevDTOGostJahrgangFachkombinationen.class);
             mapDTOName2DTOClass.put(DevDTOGostJahrgangFaecher.class.getSimpleName(),DevDTOGostJahrgangFaecher.class);
             mapDTOName2DTOClass.put(DevDTOGostJahrgangsdaten.class.getSimpleName(),DevDTOGostJahrgangsdaten.class);
             mapDTOName2DTOClass.put(DevDTOGostSchueler.class.getSimpleName(),DevDTOGostSchueler.class);
             mapDTOName2DTOClass.put(DevDTOGostSchuelerFachbelegungen.class.getSimpleName(),DevDTOGostSchuelerFachbelegungen.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenKalenderinformationen.class.getSimpleName(),DevDTOGostKlausurenKalenderinformationen.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenKursklausuren.class.getSimpleName(),DevDTOGostKlausurenKursklausuren.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenNtaZeiten.class.getSimpleName(),DevDTOGostKlausurenNtaZeiten.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenRaeume.class.getSimpleName(),DevDTOGostKlausurenRaeume.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenRaeumeStunden.class.getSimpleName(),DevDTOGostKlausurenRaeumeStunden.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenRaeumeStundenAufsichten.class.getSimpleName(),DevDTOGostKlausurenRaeumeStundenAufsichten.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenSchuelerklausuren.class.getSimpleName(),DevDTOGostKlausurenSchuelerklausuren.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenSchuelerklausurenRaeumeStunden.class.getSimpleName(),DevDTOGostKlausurenSchuelerklausurenRaeumeStunden.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenTermine.class.getSimpleName(),DevDTOGostKlausurenTermine.class);
             mapDTOName2DTOClass.put(DevDTOGostKlausurenVorgaben.class.getSimpleName(),DevDTOGostKlausurenVorgaben.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockung.class.getSimpleName(),DevDTOGostBlockung.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungKurs.class.getSimpleName(),DevDTOGostBlockungKurs.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungKurslehrer.class.getSimpleName(),DevDTOGostBlockungKurslehrer.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungRegel.class.getSimpleName(),DevDTOGostBlockungRegel.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungRegelParameter.class.getSimpleName(),DevDTOGostBlockungRegelParameter.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungSchiene.class.getSimpleName(),DevDTOGostBlockungSchiene.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungZwischenergebnis.class.getSimpleName(),DevDTOGostBlockungZwischenergebnis.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungZwischenergebnisKursSchiene.class.getSimpleName(),DevDTOGostBlockungZwischenergebnisKursSchiene.class);
             mapDTOName2DTOClass.put(DevDTOGostBlockungZwischenergebnisKursSchueler.class.getSimpleName(),DevDTOGostBlockungZwischenergebnisKursSchueler.class);
             mapDTOName2DTOClass.put(DevDTOSchildAuswahlFilter.class.getSimpleName(),DevDTOSchildAuswahlFilter.class);
             mapDTOName2DTOClass.put(DevDTOSchildVerwaltung.class.getSimpleName(),DevDTOSchildVerwaltung.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerIndividuelleGruppe.class.getSimpleName(),DevDTOSchuelerIndividuelleGruppe.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerIndividuelleGruppeSchueler.class.getSimpleName(),DevDTOSchuelerIndividuelleGruppeSchueler.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerReportvorlagen.class.getSimpleName(),DevDTOSchuelerReportvorlagen.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerWiedervorlage.class.getSimpleName(),DevDTOSchuelerWiedervorlage.class);
             mapDTOName2DTOClass.put(DevDTOTextExportVorlagen.class.getSimpleName(),DevDTOTextExportVorlagen.class);
             mapDTOName2DTOClass.put(DevDTOZuordnungReportvorlagen.class.getSimpleName(),DevDTOZuordnungReportvorlagen.class);
             mapDTOName2DTOClass.put(DevDTOBenutzer.class.getSimpleName(),DevDTOBenutzer.class);
             mapDTOName2DTOClass.put(DevDTOBenutzerAllgemein.class.getSimpleName(),DevDTOBenutzerAllgemein.class);
             mapDTOName2DTOClass.put(DevDTOBenutzerKompetenz.class.getSimpleName(),DevDTOBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(DevDTOBenutzerMail.class.getSimpleName(),DevDTOBenutzerMail.class);
             mapDTOName2DTOClass.put(DevDTOBenutzergruppe.class.getSimpleName(),DevDTOBenutzergruppe.class);
             mapDTOName2DTOClass.put(DevDTOBenutzergruppenKompetenz.class.getSimpleName(),DevDTOBenutzergruppenKompetenz.class);
             mapDTOName2DTOClass.put(DevDTOBenutzergruppenMitglied.class.getSimpleName(),DevDTOBenutzergruppenMitglied.class);
             mapDTOName2DTOClass.put(DevDTOKatalogBenutzerKompetenz.class.getSimpleName(),DevDTOKatalogBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(DevDTOKatalogBenutzerKompetenzGruppe.class.getSimpleName(),DevDTOKatalogBenutzerKompetenzGruppe.class);
             mapDTOName2DTOClass.put(DevDTOProtokollLogin.class.getSimpleName(),DevDTOProtokollLogin.class);
             mapDTOName2DTOClass.put(DevDTOBeschaeftigungsart.class.getSimpleName(),DevDTOBeschaeftigungsart.class);
             mapDTOName2DTOClass.put(DevDTOFachgliederungen.class.getSimpleName(),DevDTOFachgliederungen.class);
             mapDTOName2DTOClass.put(DevDTOFachklassen.class.getSimpleName(),DevDTOFachklassen.class);
             mapDTOName2DTOClass.put(DevDTOKatalogZertifikate.class.getSimpleName(),DevDTOKatalogZertifikate.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerBKAbschluss.class.getSimpleName(),DevDTOSchuelerBKAbschluss.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerBKFach.class.getSimpleName(),DevDTOSchuelerBKFach.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerZuweisung.class.getSimpleName(),DevDTOSchuelerZuweisung.class);
             mapDTOName2DTOClass.put(DevDTOZertifikate.class.getSimpleName(),DevDTOZertifikate.class);
             mapDTOName2DTOClass.put(DevDTOErzieherDatenschutz.class.getSimpleName(),DevDTOErzieherDatenschutz.class);
             mapDTOName2DTOClass.put(DevDTOErzieherLernplattform.class.getSimpleName(),DevDTOErzieherLernplattform.class);
             mapDTOName2DTOClass.put(DevDTOErzieherart.class.getSimpleName(),DevDTOErzieherart.class);
             mapDTOName2DTOClass.put(DevDTOErzieherfunktion.class.getSimpleName(),DevDTOErzieherfunktion.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerErzieherAdresse.class.getSimpleName(),DevDTOSchuelerErzieherAdresse.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerTelefon.class.getSimpleName(),DevDTOSchuelerTelefon.class);
             mapDTOName2DTOClass.put(DevDTOTelefonArt.class.getSimpleName(),DevDTOTelefonArt.class);
             mapDTOName2DTOClass.put(DevDTOFach.class.getSimpleName(),DevDTOFach.class);
             mapDTOName2DTOClass.put(DevDTOFachTeilleistungsarten.class.getSimpleName(),DevDTOFachTeilleistungsarten.class);
             mapDTOName2DTOClass.put(DevDTOFachgruppen.class.getSimpleName(),DevDTOFachgruppen.class);
             mapDTOName2DTOClass.put(DevDTOFaecherKatalog.class.getSimpleName(),DevDTOFaecherKatalog.class);
             mapDTOName2DTOClass.put(DevDTOFaecherKatalogKeys.class.getSimpleName(),DevDTOFaecherKatalogKeys.class);
             mapDTOName2DTOClass.put(DevDTOFaecherKatalogSchulformen.class.getSimpleName(),DevDTOFaecherKatalogSchulformen.class);
             mapDTOName2DTOClass.put(DevDTOFaecherNichtMoeglicheKombination.class.getSimpleName(),DevDTOFaecherNichtMoeglicheKombination.class);
             mapDTOName2DTOClass.put(DevDTOAnkreuzdaten.class.getSimpleName(),DevDTOAnkreuzdaten.class);
             mapDTOName2DTOClass.put(DevDTOAnkreuzfloskeln.class.getSimpleName(),DevDTOAnkreuzfloskeln.class);
             mapDTOName2DTOClass.put(DevDTOKindergarten.class.getSimpleName(),DevDTOKindergarten.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerAnkreuzfloskeln.class.getSimpleName(),DevDTOSchuelerAnkreuzfloskeln.class);
             mapDTOName2DTOClass.put(DevDTOEigeneImporte.class.getSimpleName(),DevDTOEigeneImporte.class);
             mapDTOName2DTOClass.put(DevDTOEigeneImporteFelder.class.getSimpleName(),DevDTOEigeneImporteFelder.class);
             mapDTOName2DTOClass.put(DevDTOEigeneImporteTabellen.class.getSimpleName(),DevDTOEigeneImporteTabellen.class);
             mapDTOName2DTOClass.put(DevDTOAnsprechpartnerAllgemeineAdresse.class.getSimpleName(),DevDTOAnsprechpartnerAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(DevDTOFahrschuelerart.class.getSimpleName(),DevDTOFahrschuelerart.class);
             mapDTOName2DTOClass.put(DevDTOFloskelgruppen.class.getSimpleName(),DevDTOFloskelgruppen.class);
             mapDTOName2DTOClass.put(DevDTOFloskeln.class.getSimpleName(),DevDTOFloskeln.class);
             mapDTOName2DTOClass.put(DevDTOHaltestellen.class.getSimpleName(),DevDTOHaltestellen.class);
             mapDTOName2DTOClass.put(DevDTOKatalogAdressart.class.getSimpleName(),DevDTOKatalogAdressart.class);
             mapDTOName2DTOClass.put(DevDTOKatalogAllgemeineAdresse.class.getSimpleName(),DevDTOKatalogAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(DevDTOKatalogAufsichtsbereich.class.getSimpleName(),DevDTOKatalogAufsichtsbereich.class);
             mapDTOName2DTOClass.put(DevDTOKatalogDatenschutz.class.getSimpleName(),DevDTOKatalogDatenschutz.class);
             mapDTOName2DTOClass.put(DevDTOKatalogRaum.class.getSimpleName(),DevDTOKatalogRaum.class);
             mapDTOName2DTOClass.put(DevDTOKonfession.class.getSimpleName(),DevDTOKonfession.class);
             mapDTOName2DTOClass.put(DevDTOKursarten.class.getSimpleName(),DevDTOKursarten.class);
             mapDTOName2DTOClass.put(DevDTOOrt.class.getSimpleName(),DevDTOOrt.class);
             mapDTOName2DTOClass.put(DevDTOOrtsteil.class.getSimpleName(),DevDTOOrtsteil.class);
             mapDTOName2DTOClass.put(DevDTOSchuleNRW.class.getSimpleName(),DevDTOSchuleNRW.class);
             mapDTOName2DTOClass.put(DevDTOSchulfunktion.class.getSimpleName(),DevDTOSchulfunktion.class);
             mapDTOName2DTOClass.put(DevDTOSchwerpunkt.class.getSimpleName(),DevDTOSchwerpunkt.class);
             mapDTOName2DTOClass.put(DevDTOTextDateien.class.getSimpleName(),DevDTOTextDateien.class);
             mapDTOName2DTOClass.put(DevDTOVermerkArt.class.getSimpleName(),DevDTOVermerkArt.class);
             mapDTOName2DTOClass.put(DevDTOKlassen.class.getSimpleName(),DevDTOKlassen.class);
             mapDTOName2DTOClass.put(DevDTOKlassenLeitung.class.getSimpleName(),DevDTOKlassenLeitung.class);
             mapDTOName2DTOClass.put(DevDTOKlassenartenKatalogKeys.class.getSimpleName(),DevDTOKlassenartenKatalogKeys.class);
             mapDTOName2DTOClass.put(DevDTOKurs.class.getSimpleName(),DevDTOKurs.class);
             mapDTOName2DTOClass.put(DevDTOKursLehrer.class.getSimpleName(),DevDTOKursLehrer.class);
             mapDTOName2DTOClass.put(DevDTOKursSchueler.class.getSimpleName(),DevDTOKursSchueler.class);
             mapDTOName2DTOClass.put(DevDTOKursartenKatalogKeys.class.getSimpleName(),DevDTOKursartenKatalogKeys.class);
             mapDTOName2DTOClass.put(DevDTOLehrer.class.getSimpleName(),DevDTOLehrer.class);
             mapDTOName2DTOClass.put(DevDTOLehrerAbschnittsdaten.class.getSimpleName(),DevDTOLehrerAbschnittsdaten.class);
             mapDTOName2DTOClass.put(DevDTOLehrerAnrechnungsstunde.class.getSimpleName(),DevDTOLehrerAnrechnungsstunde.class);
             mapDTOName2DTOClass.put(DevDTOLehrerDatenschutz.class.getSimpleName(),DevDTOLehrerDatenschutz.class);
             mapDTOName2DTOClass.put(DevDTOLehrerEntlastungsstunde.class.getSimpleName(),DevDTOLehrerEntlastungsstunde.class);
             mapDTOName2DTOClass.put(DevDTOLehrerFoto.class.getSimpleName(),DevDTOLehrerFoto.class);
             mapDTOName2DTOClass.put(DevDTOLehrerFunktion.class.getSimpleName(),DevDTOLehrerFunktion.class);
             mapDTOName2DTOClass.put(DevDTOLehrerLehramt.class.getSimpleName(),DevDTOLehrerLehramt.class);
             mapDTOName2DTOClass.put(DevDTOLehrerLehramtBefaehigung.class.getSimpleName(),DevDTOLehrerLehramtBefaehigung.class);
             mapDTOName2DTOClass.put(DevDTOLehrerLehramtFachrichtung.class.getSimpleName(),DevDTOLehrerLehramtFachrichtung.class);
             mapDTOName2DTOClass.put(DevDTOLehrerLeitungsfunktionKeys.class.getSimpleName(),DevDTOLehrerLeitungsfunktionKeys.class);
             mapDTOName2DTOClass.put(DevDTOLehrerLernplattform.class.getSimpleName(),DevDTOLehrerLernplattform.class);
             mapDTOName2DTOClass.put(DevDTOLehrerMehrleistung.class.getSimpleName(),DevDTOLehrerMehrleistung.class);
             mapDTOName2DTOClass.put(DevDTOSchulleitung.class.getSimpleName(),DevDTOSchulleitung.class);
             mapDTOName2DTOClass.put(DevDTOPersonengruppen.class.getSimpleName(),DevDTOPersonengruppen.class);
             mapDTOName2DTOClass.put(DevDTOPersonengruppenPersonen.class.getSimpleName(),DevDTOPersonengruppenPersonen.class);
             mapDTOName2DTOClass.put(DevDTOEinschulungsart.class.getSimpleName(),DevDTOEinschulungsart.class);
             mapDTOName2DTOClass.put(DevDTOEntlassarten.class.getSimpleName(),DevDTOEntlassarten.class);
             mapDTOName2DTOClass.put(DevDTOFoerderschwerpunkt.class.getSimpleName(),DevDTOFoerderschwerpunkt.class);
             mapDTOName2DTOClass.put(DevDTOSchueler.class.getSimpleName(),DevDTOSchueler.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerAbgaenge.class.getSimpleName(),DevDTOSchuelerAbgaenge.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerAllgemeineAdresse.class.getSimpleName(),DevDTOSchuelerAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerDatenschutz.class.getSimpleName(),DevDTOSchuelerDatenschutz.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerFehlstunden.class.getSimpleName(),DevDTOSchuelerFehlstunden.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerFoerderempfehlung.class.getSimpleName(),DevDTOSchuelerFoerderempfehlung.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerFoto.class.getSimpleName(),DevDTOSchuelerFoto.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerGrundschuldaten.class.getSimpleName(),DevDTOSchuelerGrundschuldaten.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerKAoADaten.class.getSimpleName(),DevDTOSchuelerKAoADaten.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerLeistungsdaten.class.getSimpleName(),DevDTOSchuelerLeistungsdaten.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerLernabschnittsdaten.class.getSimpleName(),DevDTOSchuelerLernabschnittsdaten.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerLernplattform.class.getSimpleName(),DevDTOSchuelerLernplattform.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerMerkmale.class.getSimpleName(),DevDTOSchuelerMerkmale.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerPSFachBemerkungen.class.getSimpleName(),DevDTOSchuelerPSFachBemerkungen.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerSprachenfolge.class.getSimpleName(),DevDTOSchuelerSprachenfolge.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerSprachpruefungen.class.getSimpleName(),DevDTOSchuelerSprachpruefungen.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerTeilleistung.class.getSimpleName(),DevDTOSchuelerTeilleistung.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerVermerke.class.getSimpleName(),DevDTOSchuelerVermerke.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerZP10.class.getSimpleName(),DevDTOSchuelerZP10.class);
             mapDTOName2DTOClass.put(DevDTOSportbefreiung.class.getSimpleName(),DevDTOSportbefreiung.class);
             mapDTOName2DTOClass.put(DevDTOTeilleistungsarten.class.getSimpleName(),DevDTOTeilleistungsarten.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerAbitur.class.getSimpleName(),DevDTOSchuelerAbitur.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerAbiturFach.class.getSimpleName(),DevDTOSchuelerAbiturFach.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerFHR.class.getSimpleName(),DevDTOSchuelerFHR.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerFHRFach.class.getSimpleName(),DevDTOSchuelerFHRFach.class);
             mapDTOName2DTOClass.put(DevDTOAbteilungen.class.getSimpleName(),DevDTOAbteilungen.class);
             mapDTOName2DTOClass.put(DevDTOAbteilungsKlassen.class.getSimpleName(),DevDTOAbteilungsKlassen.class);
             mapDTOName2DTOClass.put(DevDTOAlleJahrgaengeKeys.class.getSimpleName(),DevDTOAlleJahrgaengeKeys.class);
             mapDTOName2DTOClass.put(DevDTOAlleSchulformen.class.getSimpleName(),DevDTOAlleSchulformen.class);
             mapDTOName2DTOClass.put(DevDTOAllgemeineMerkmaleKatalogKeys.class.getSimpleName(),DevDTOAllgemeineMerkmaleKatalogKeys.class);
             mapDTOName2DTOClass.put(DevDTOBerufskollegAnlagen.class.getSimpleName(),DevDTOBerufskollegAnlagen.class);
             mapDTOName2DTOClass.put(DevDTOBerufskollegBerufsebenen1.class.getSimpleName(),DevDTOBerufskollegBerufsebenen1.class);
             mapDTOName2DTOClass.put(DevDTOBerufskollegBerufsebenen2.class.getSimpleName(),DevDTOBerufskollegBerufsebenen2.class);
             mapDTOName2DTOClass.put(DevDTOBerufskollegBerufsebenen3.class.getSimpleName(),DevDTOBerufskollegBerufsebenen3.class);
             mapDTOName2DTOClass.put(DevDTOBerufskollegFachklassenKeys.class.getSimpleName(),DevDTOBerufskollegFachklassenKeys.class);
             mapDTOName2DTOClass.put(DevDTOEigeneSchule.class.getSimpleName(),DevDTOEigeneSchule.class);
             mapDTOName2DTOClass.put(DevDTOEigeneSchuleKAoADaten.class.getSimpleName(),DevDTOEigeneSchuleKAoADaten.class);
             mapDTOName2DTOClass.put(DevDTOEinschulungsartenKatalogKeys.class.getSimpleName(),DevDTOEinschulungsartenKatalogKeys.class);
             mapDTOName2DTOClass.put(DevDTOHerkunft.class.getSimpleName(),DevDTOHerkunft.class);
             mapDTOName2DTOClass.put(DevDTOHerkunftSchulformen.class.getSimpleName(),DevDTOHerkunftSchulformen.class);
             mapDTOName2DTOClass.put(DevDTOHerkunftsart.class.getSimpleName(),DevDTOHerkunftsart.class);
             mapDTOName2DTOClass.put(DevDTOHerkunftsartSchulformen.class.getSimpleName(),DevDTOHerkunftsartSchulformen.class);
             mapDTOName2DTOClass.put(DevDTOJahrgang.class.getSimpleName(),DevDTOJahrgang.class);
             mapDTOName2DTOClass.put(DevDTOMerkmale.class.getSimpleName(),DevDTOMerkmale.class);
             mapDTOName2DTOClass.put(DevDTOOrganisationsformenKatalogKeys.class.getSimpleName(),DevDTOOrganisationsformenKatalogKeys.class);
             mapDTOName2DTOClass.put(DevDTOSchulformen.class.getSimpleName(),DevDTOSchulformen.class);
             mapDTOName2DTOClass.put(DevDTOSchuljahresabschnitte.class.getSimpleName(),DevDTOSchuljahresabschnitte.class);
             mapDTOName2DTOClass.put(DevDTOSchultexte.class.getSimpleName(),DevDTOSchultexte.class);
             mapDTOName2DTOClass.put(DevDTOStundentafel.class.getSimpleName(),DevDTOStundentafel.class);
             mapDTOName2DTOClass.put(DevDTOStundentafelFaecher.class.getSimpleName(),DevDTOStundentafelFaecher.class);
             mapDTOName2DTOClass.put(DevDTOTeilstandorte.class.getSimpleName(),DevDTOTeilstandorte.class);
             mapDTOName2DTOClass.put(DevDTOKatalogPausenzeit.class.getSimpleName(),DevDTOKatalogPausenzeit.class);
             mapDTOName2DTOClass.put(DevDTOKatalogZeitraster.class.getSimpleName(),DevDTOKatalogZeitraster.class);
             mapDTOName2DTOClass.put(DevDTOStundenplan.class.getSimpleName(),DevDTOStundenplan.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanAufsichtsbereich.class.getSimpleName(),DevDTOStundenplanAufsichtsbereich.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanPausenaufsichten.class.getSimpleName(),DevDTOStundenplanPausenaufsichten.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanPausenaufsichtenBereiche.class.getSimpleName(),DevDTOStundenplanPausenaufsichtenBereiche.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanPausenzeit.class.getSimpleName(),DevDTOStundenplanPausenzeit.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanRaum.class.getSimpleName(),DevDTOStundenplanRaum.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanUnterricht.class.getSimpleName(),DevDTOStundenplanUnterricht.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanUnterrichtLehrer.class.getSimpleName(),DevDTOStundenplanUnterrichtLehrer.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanUnterrichtRaum.class.getSimpleName(),DevDTOStundenplanUnterrichtRaum.class);
             mapDTOName2DTOClass.put(DevDTOStundenplanZeitraster.class.getSimpleName(),DevDTOStundenplanZeitraster.class);
             mapDTOName2DTOClass.put(DevDTOSchuelerStatus.class.getSimpleName(),DevDTOSchuelerStatus.class);
             mapDTOName2DTOClass.put(DevDTOHerkunftKeys.class.getSimpleName(),DevDTOHerkunftKeys.class);
             mapDTOName2DTOClass.put(DevDTOHerkunftsartKeys.class.getSimpleName(),DevDTOHerkunftsartKeys.class);
             mapDTOName2DTOClass.put(DevDTOKAoAAnschlussoptionKeys.class.getSimpleName(),DevDTOKAoAAnschlussoptionKeys.class);
             mapDTOName2DTOClass.put(DevDTOKAoABerufsfeldKeys.class.getSimpleName(),DevDTOKAoABerufsfeldKeys.class);
             mapDTOName2DTOClass.put(DevDTOKAoAKategorieKeys.class.getSimpleName(),DevDTOKAoAKategorieKeys.class);
             mapDTOName2DTOClass.put(DevDTOKAoAMerkmalKeys.class.getSimpleName(),DevDTOKAoAMerkmalKeys.class);
             mapDTOName2DTOClass.put(DevDTOKAoASBOEB4Keys.class.getSimpleName(),DevDTOKAoASBOEB4Keys.class);
             mapDTOName2DTOClass.put(DevDTOKAoAZusatzmerkmalKeys.class.getSimpleName(),DevDTOKAoAZusatzmerkmalKeys.class);
             mapDTOName2DTOClass.put(DevDTONationalitaetenKeys.class.getSimpleName(),DevDTONationalitaetenKeys.class);
             mapDTOName2DTOClass.put(DevDTOReligionKeys.class.getSimpleName(),DevDTOReligionKeys.class);
             mapDTOName2DTOClass.put(DevDTOCredentials.class.getSimpleName(),DevDTOCredentials.class);
             mapDTOName2DTOClass.put(DevDTOCredentialsLernplattformen.class.getSimpleName(),DevDTOCredentialsLernplattformen.class);
             mapDTOName2DTOClass.put(DevDTOLernplattformen.class.getSimpleName(),DevDTOLernplattformen.class);
             mapDTOName2DTOClass.put(DevDTOSchuleCredentials.class.getSimpleName(),DevDTOSchuleCredentials.class);
             mapDTOName2DTOClass.put(DevDTOClientKonfigurationBenutzer.class.getSimpleName(),DevDTOClientKonfigurationBenutzer.class);
             mapDTOName2DTOClass.put(DevDTOClientKonfigurationGlobal.class.getSimpleName(),DevDTOClientKonfigurationGlobal.class);
             mapDTOName2DTOClass.put(DevDTODavRessource.class.getSimpleName(),DevDTODavRessource.class);
             mapDTOName2DTOClass.put(DevDTODavRessourceCollection.class.getSimpleName(),DevDTODavRessourceCollection.class);
             mapDTOName2DTOClass.put(DevDTODavRessourceCollectionsACL.class.getSimpleName(),DevDTODavRessourceCollectionsACL.class);
             mapDTOName2DTOClass.put(DevDTODavSyncTokenLehrer.class.getSimpleName(),DevDTODavSyncTokenLehrer.class);
             mapDTOName2DTOClass.put(DevDTODavSyncTokenSchueler.class.getSimpleName(),DevDTODavSyncTokenSchueler.class);
             mapDTOName2DTOClass.put(DevDTOCoreTypeVersion.class.getSimpleName(),DevDTOCoreTypeVersion.class);
             mapDTOName2DTOClass.put(DevDTODBAutoInkremente.class.getSimpleName(),DevDTODBAutoInkremente.class);
             mapDTOName2DTOClass.put(DevDTODBVersion.class.getSimpleName(),DevDTODBVersion.class);
             mapDTOName2DTOClass.put(DevDTOEnmLeistungsdaten.class.getSimpleName(),DevDTOEnmLeistungsdaten.class);
             mapDTOName2DTOClass.put(DevDTOEnmLernabschnittsdaten.class.getSimpleName(),DevDTOEnmLernabschnittsdaten.class);
             mapDTOName2DTOClass.put(DevDTOViewBenutzer.class.getSimpleName(),DevDTOViewBenutzer.class);
             mapDTOName2DTOClass.put(DevDTOViewBenutzerKompetenz.class.getSimpleName(),DevDTOViewBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(DevDTOViewBenutzerdetails.class.getSimpleName(),DevDTOViewBenutzerdetails.class);
             mapDTOName2DTOClass.put(DevDTOViewGostSchuelerAbiturjahrgang.class.getSimpleName(),DevDTOViewGostSchuelerAbiturjahrgang.class);
         }
         return mapDTOName2DTOClass;
     }


    /**
     * Gibt die DTO-Klasse mit dem angegebenen DTO-Namen zurück.
     *
     * @param name   der DTO-Name
     *
     * @return die DTO-Klasse
     */
    public static Class<? extends Object> getFromDTOName(String name) {
    	return getMapDTOName2DTOClass().get(name);
    }


    /**
     * Gibt das Mapping der Namen aller Java-DTO-Klassen für die SVWS-DB zu den zugehörigen
     * Java-DTO-Klassen zurück.
     *
     * @return eine Hashmap mit dem Mapping
     */
     private static final HashMap<String, Class<? extends Object>> getMapTablename2DTOClass() {
         if (mapTablename2DTOClass == null) {
             mapTablename2DTOClass = new HashMap<>();
             mapTablename2DTOClass.put("KursFortschreibungsarten",DevDTOKursFortschreibungsart.class);
             mapTablename2DTOClass.put("Noten",DevDTONote.class);
             mapTablename2DTOClass.put("PersonalTypen",DevDTOPersonalTyp.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Beratungslehrer",DevDTOGostJahrgangBeratungslehrer.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Fachkombinationen",DevDTOGostJahrgangFachkombinationen.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Faecher",DevDTOGostJahrgangFaecher.class);
             mapTablename2DTOClass.put("Gost_Jahrgangsdaten",DevDTOGostJahrgangsdaten.class);
             mapTablename2DTOClass.put("Gost_Schueler",DevDTOGostSchueler.class);
             mapTablename2DTOClass.put("Gost_Schueler_Fachwahlen",DevDTOGostSchuelerFachbelegungen.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Kalenderinformationen",DevDTOGostKlausurenKalenderinformationen.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Kursklausuren",DevDTOGostKlausurenKursklausuren.class);
             mapTablename2DTOClass.put("Gost_Klausuren_NtaZeiten",DevDTOGostKlausurenNtaZeiten.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Raeume",DevDTOGostKlausurenRaeume.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Raeume_Stunden",DevDTOGostKlausurenRaeumeStunden.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Raeume_Stunden_Aufsichten",DevDTOGostKlausurenRaeumeStundenAufsichten.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Schuelerklausuren",DevDTOGostKlausurenSchuelerklausuren.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Schuelerklausuren_Raeume_Stunden",DevDTOGostKlausurenSchuelerklausurenRaeumeStunden.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Termine",DevDTOGostKlausurenTermine.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Vorgaben",DevDTOGostKlausurenVorgaben.class);
             mapTablename2DTOClass.put("Gost_Blockung",DevDTOGostBlockung.class);
             mapTablename2DTOClass.put("Gost_Blockung_Kurse",DevDTOGostBlockungKurs.class);
             mapTablename2DTOClass.put("Gost_Blockung_Kurslehrer",DevDTOGostBlockungKurslehrer.class);
             mapTablename2DTOClass.put("Gost_Blockung_Regeln",DevDTOGostBlockungRegel.class);
             mapTablename2DTOClass.put("Gost_Blockung_Regelparameter",DevDTOGostBlockungRegelParameter.class);
             mapTablename2DTOClass.put("Gost_Blockung_Schienen",DevDTOGostBlockungSchiene.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse",DevDTOGostBlockungZwischenergebnis.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse_Kurs_Schienen",DevDTOGostBlockungZwischenergebnisKursSchiene.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse_Kurs_Schueler",DevDTOGostBlockungZwischenergebnisKursSchueler.class);
             mapTablename2DTOClass.put("SchildFilter",DevDTOSchildAuswahlFilter.class);
             mapTablename2DTOClass.put("Schild_Verwaltung",DevDTOSchildVerwaltung.class);
             mapTablename2DTOClass.put("SchuelerListe",DevDTOSchuelerIndividuelleGruppe.class);
             mapTablename2DTOClass.put("SchuelerListe_Inhalt",DevDTOSchuelerIndividuelleGruppeSchueler.class);
             mapTablename2DTOClass.put("SchuelerReportvorlagen",DevDTOSchuelerReportvorlagen.class);
             mapTablename2DTOClass.put("SchuelerWiedervorlage",DevDTOSchuelerWiedervorlage.class);
             mapTablename2DTOClass.put("TextExportVorlagen",DevDTOTextExportVorlagen.class);
             mapTablename2DTOClass.put("ZuordnungReportvorlagen",DevDTOZuordnungReportvorlagen.class);
             mapTablename2DTOClass.put("Benutzer",DevDTOBenutzer.class);
             mapTablename2DTOClass.put("BenutzerAllgemein",DevDTOBenutzerAllgemein.class);
             mapTablename2DTOClass.put("BenutzerKompetenzen",DevDTOBenutzerKompetenz.class);
             mapTablename2DTOClass.put("BenutzerEmail",DevDTOBenutzerMail.class);
             mapTablename2DTOClass.put("Benutzergruppen",DevDTOBenutzergruppe.class);
             mapTablename2DTOClass.put("BenutzergruppenKompetenzen",DevDTOBenutzergruppenKompetenz.class);
             mapTablename2DTOClass.put("BenutzergruppenMitglieder",DevDTOBenutzergruppenMitglied.class);
             mapTablename2DTOClass.put("Kompetenzen",DevDTOKatalogBenutzerKompetenz.class);
             mapTablename2DTOClass.put("Kompetenzgruppen",DevDTOKatalogBenutzerKompetenzGruppe.class);
             mapTablename2DTOClass.put("Logins",DevDTOProtokollLogin.class);
             mapTablename2DTOClass.put("K_BeschaeftigungsArt",DevDTOBeschaeftigungsart.class);
             mapTablename2DTOClass.put("Fach_Gliederungen",DevDTOFachgliederungen.class);
             mapTablename2DTOClass.put("EigeneSchule_Fachklassen",DevDTOFachklassen.class);
             mapTablename2DTOClass.put("K_Zertifikate",DevDTOKatalogZertifikate.class);
             mapTablename2DTOClass.put("SchuelerBKAbschluss",DevDTOSchuelerBKAbschluss.class);
             mapTablename2DTOClass.put("SchuelerBKFaecher",DevDTOSchuelerBKFach.class);
             mapTablename2DTOClass.put("SchuelerZuweisungen",DevDTOSchuelerZuweisung.class);
             mapTablename2DTOClass.put("EigeneSchule_Zertifikate",DevDTOZertifikate.class);
             mapTablename2DTOClass.put("ErzieherDatenschutz",DevDTOErzieherDatenschutz.class);
             mapTablename2DTOClass.put("ErzieherLernplattform",DevDTOErzieherLernplattform.class);
             mapTablename2DTOClass.put("K_ErzieherArt",DevDTOErzieherart.class);
             mapTablename2DTOClass.put("K_ErzieherFunktion",DevDTOErzieherfunktion.class);
             mapTablename2DTOClass.put("SchuelerErzAdr",DevDTOSchuelerErzieherAdresse.class);
             mapTablename2DTOClass.put("SchuelerTelefone",DevDTOSchuelerTelefon.class);
             mapTablename2DTOClass.put("K_TelefonArt",DevDTOTelefonArt.class);
             mapTablename2DTOClass.put("EigeneSchule_Faecher",DevDTOFach.class);
             mapTablename2DTOClass.put("EigeneSchule_FachTeilleistungen",DevDTOFachTeilleistungsarten.class);
             mapTablename2DTOClass.put("Fachgruppen",DevDTOFachgruppen.class);
             mapTablename2DTOClass.put("FachKatalog",DevDTOFaecherKatalog.class);
             mapTablename2DTOClass.put("FachKatalog_Keys",DevDTOFaecherKatalogKeys.class);
             mapTablename2DTOClass.put("FachKatalog_Schulformen",DevDTOFaecherKatalogSchulformen.class);
             mapTablename2DTOClass.put("NichtMoeglAbiFachKombi",DevDTOFaecherNichtMoeglicheKombination.class);
             mapTablename2DTOClass.put("K_Ankreuzdaten",DevDTOAnkreuzdaten.class);
             mapTablename2DTOClass.put("K_Ankreuzfloskeln",DevDTOAnkreuzfloskeln.class);
             mapTablename2DTOClass.put("K_Kindergarten",DevDTOKindergarten.class);
             mapTablename2DTOClass.put("SchuelerAnkreuzfloskeln",DevDTOSchuelerAnkreuzfloskeln.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte",DevDTOEigeneImporte.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte_Felder",DevDTOEigeneImporteFelder.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte_Tabellen",DevDTOEigeneImporteTabellen.class);
             mapTablename2DTOClass.put("AllgAdrAnsprechpartner",DevDTOAnsprechpartnerAllgemeineAdresse.class);
             mapTablename2DTOClass.put("K_FahrschuelerArt",DevDTOFahrschuelerart.class);
             mapTablename2DTOClass.put("Floskelgruppen",DevDTOFloskelgruppen.class);
             mapTablename2DTOClass.put("Floskeln",DevDTOFloskeln.class);
             mapTablename2DTOClass.put("K_Haltestelle",DevDTOHaltestellen.class);
             mapTablename2DTOClass.put("K_Adressart",DevDTOKatalogAdressart.class);
             mapTablename2DTOClass.put("K_AllgAdresse",DevDTOKatalogAllgemeineAdresse.class);
             mapTablename2DTOClass.put("Katalog_Aufsichtsbereich",DevDTOKatalogAufsichtsbereich.class);
             mapTablename2DTOClass.put("K_Datenschutz",DevDTOKatalogDatenschutz.class);
             mapTablename2DTOClass.put("Katalog_Raeume",DevDTOKatalogRaum.class);
             mapTablename2DTOClass.put("K_Religion",DevDTOKonfession.class);
             mapTablename2DTOClass.put("EigeneSchule_Kursart",DevDTOKursarten.class);
             mapTablename2DTOClass.put("K_Ort",DevDTOOrt.class);
             mapTablename2DTOClass.put("K_Ortsteil",DevDTOOrtsteil.class);
             mapTablename2DTOClass.put("K_Schule",DevDTOSchuleNRW.class);
             mapTablename2DTOClass.put("K_Schulfunktionen",DevDTOSchulfunktion.class);
             mapTablename2DTOClass.put("K_Schwerpunkt",DevDTOSchwerpunkt.class);
             mapTablename2DTOClass.put("K_Textdateien",DevDTOTextDateien.class);
             mapTablename2DTOClass.put("K_Vermerkart",DevDTOVermerkArt.class);
             mapTablename2DTOClass.put("Klassen",DevDTOKlassen.class);
             mapTablename2DTOClass.put("KlassenLehrer",DevDTOKlassenLeitung.class);
             mapTablename2DTOClass.put("KlassenartenKatalog_Keys",DevDTOKlassenartenKatalogKeys.class);
             mapTablename2DTOClass.put("Kurse",DevDTOKurs.class);
             mapTablename2DTOClass.put("KursLehrer",DevDTOKursLehrer.class);
             mapTablename2DTOClass.put("Kurs_Schueler",DevDTOKursSchueler.class);
             mapTablename2DTOClass.put("KursartenKatalog_Keys",DevDTOKursartenKatalogKeys.class);
             mapTablename2DTOClass.put("K_Lehrer",DevDTOLehrer.class);
             mapTablename2DTOClass.put("LehrerAbschnittsdaten",DevDTOLehrerAbschnittsdaten.class);
             mapTablename2DTOClass.put("LehrerAnrechnung",DevDTOLehrerAnrechnungsstunde.class);
             mapTablename2DTOClass.put("LehrerDatenschutz",DevDTOLehrerDatenschutz.class);
             mapTablename2DTOClass.put("LehrerEntlastung",DevDTOLehrerEntlastungsstunde.class);
             mapTablename2DTOClass.put("LehrerFotos",DevDTOLehrerFoto.class);
             mapTablename2DTOClass.put("LehrerFunktionen",DevDTOLehrerFunktion.class);
             mapTablename2DTOClass.put("LehrerLehramt",DevDTOLehrerLehramt.class);
             mapTablename2DTOClass.put("LehrerLehramtLehrbef",DevDTOLehrerLehramtBefaehigung.class);
             mapTablename2DTOClass.put("LehrerLehramtFachr",DevDTOLehrerLehramtFachrichtung.class);
             mapTablename2DTOClass.put("LehrerLeitungsfunktion_Keys",DevDTOLehrerLeitungsfunktionKeys.class);
             mapTablename2DTOClass.put("LehrerLernplattform",DevDTOLehrerLernplattform.class);
             mapTablename2DTOClass.put("LehrerMehrleistung",DevDTOLehrerMehrleistung.class);
             mapTablename2DTOClass.put("Schulleitung",DevDTOSchulleitung.class);
             mapTablename2DTOClass.put("Personengruppen",DevDTOPersonengruppen.class);
             mapTablename2DTOClass.put("Personengruppen_Personen",DevDTOPersonengruppenPersonen.class);
             mapTablename2DTOClass.put("K_EinschulungsArt",DevDTOEinschulungsart.class);
             mapTablename2DTOClass.put("K_EntlassGrund",DevDTOEntlassarten.class);
             mapTablename2DTOClass.put("K_Foerderschwerpunkt",DevDTOFoerderschwerpunkt.class);
             mapTablename2DTOClass.put("Schueler",DevDTOSchueler.class);
             mapTablename2DTOClass.put("SchuelerAbgaenge",DevDTOSchuelerAbgaenge.class);
             mapTablename2DTOClass.put("Schueler_AllgAdr",DevDTOSchuelerAllgemeineAdresse.class);
             mapTablename2DTOClass.put("SchuelerDatenschutz",DevDTOSchuelerDatenschutz.class);
             mapTablename2DTOClass.put("SchuelerFehlstunden",DevDTOSchuelerFehlstunden.class);
             mapTablename2DTOClass.put("SchuelerFoerderempfehlungen",DevDTOSchuelerFoerderempfehlung.class);
             mapTablename2DTOClass.put("SchuelerFotos",DevDTOSchuelerFoto.class);
             mapTablename2DTOClass.put("SchuelerGSDaten",DevDTOSchuelerGrundschuldaten.class);
             mapTablename2DTOClass.put("SchuelerKAoADaten",DevDTOSchuelerKAoADaten.class);
             mapTablename2DTOClass.put("SchuelerLeistungsdaten",DevDTOSchuelerLeistungsdaten.class);
             mapTablename2DTOClass.put("SchuelerLernabschnittsdaten",DevDTOSchuelerLernabschnittsdaten.class);
             mapTablename2DTOClass.put("SchuelerLernplattform",DevDTOSchuelerLernplattform.class);
             mapTablename2DTOClass.put("SchuelerMerkmale",DevDTOSchuelerMerkmale.class);
             mapTablename2DTOClass.put("SchuelerLD_PSFachBem",DevDTOSchuelerPSFachBemerkungen.class);
             mapTablename2DTOClass.put("SchuelerSprachenfolge",DevDTOSchuelerSprachenfolge.class);
             mapTablename2DTOClass.put("SchuelerSprachpruefungen",DevDTOSchuelerSprachpruefungen.class);
             mapTablename2DTOClass.put("SchuelerEinzelleistungen",DevDTOSchuelerTeilleistung.class);
             mapTablename2DTOClass.put("SchuelerVermerke",DevDTOSchuelerVermerke.class);
             mapTablename2DTOClass.put("SchuelerZP10",DevDTOSchuelerZP10.class);
             mapTablename2DTOClass.put("K_Sportbefreiung",DevDTOSportbefreiung.class);
             mapTablename2DTOClass.put("K_Einzelleistungen",DevDTOTeilleistungsarten.class);
             mapTablename2DTOClass.put("SchuelerAbitur",DevDTOSchuelerAbitur.class);
             mapTablename2DTOClass.put("SchuelerAbiFaecher",DevDTOSchuelerAbiturFach.class);
             mapTablename2DTOClass.put("SchuelerFHR",DevDTOSchuelerFHR.class);
             mapTablename2DTOClass.put("SchuelerFHRFaecher",DevDTOSchuelerFHRFach.class);
             mapTablename2DTOClass.put("EigeneSchule_Abteilungen",DevDTOAbteilungen.class);
             mapTablename2DTOClass.put("EigeneSchule_Abt_Kl",DevDTOAbteilungsKlassen.class);
             mapTablename2DTOClass.put("Jahrgaenge_Keys",DevDTOAlleJahrgaengeKeys.class);
             mapTablename2DTOClass.put("Schulformen",DevDTOAlleSchulformen.class);
             mapTablename2DTOClass.put("AllgemeineMerkmaleKatalog_Keys",DevDTOAllgemeineMerkmaleKatalogKeys.class);
             mapTablename2DTOClass.put("Berufskolleg_Anlagen",DevDTOBerufskollegAnlagen.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen1",DevDTOBerufskollegBerufsebenen1.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen2",DevDTOBerufskollegBerufsebenen2.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen3",DevDTOBerufskollegBerufsebenen3.class);
             mapTablename2DTOClass.put("Berufskolleg_Fachklassen_Keys",DevDTOBerufskollegFachklassenKeys.class);
             mapTablename2DTOClass.put("EigeneSchule",DevDTOEigeneSchule.class);
             mapTablename2DTOClass.put("EigeneSchule_KAoADaten",DevDTOEigeneSchuleKAoADaten.class);
             mapTablename2DTOClass.put("EinschulungsartKatalog_Keys",DevDTOEinschulungsartenKatalogKeys.class);
             mapTablename2DTOClass.put("Herkunft",DevDTOHerkunft.class);
             mapTablename2DTOClass.put("Herkunft_Schulformen",DevDTOHerkunftSchulformen.class);
             mapTablename2DTOClass.put("Herkunftsart",DevDTOHerkunftsart.class);
             mapTablename2DTOClass.put("Herkunftsart_Schulformen",DevDTOHerkunftsartSchulformen.class);
             mapTablename2DTOClass.put("EigeneSchule_Jahrgaenge",DevDTOJahrgang.class);
             mapTablename2DTOClass.put("EigeneSchule_Merkmale",DevDTOMerkmale.class);
             mapTablename2DTOClass.put("OrganisationsformenKatalog_Keys",DevDTOOrganisationsformenKatalogKeys.class);
             mapTablename2DTOClass.put("EigeneSchule_Schulformen",DevDTOSchulformen.class);
             mapTablename2DTOClass.put("Schuljahresabschnitte",DevDTOSchuljahresabschnitte.class);
             mapTablename2DTOClass.put("EigeneSchule_Texte",DevDTOSchultexte.class);
             mapTablename2DTOClass.put("Stundentafel",DevDTOStundentafel.class);
             mapTablename2DTOClass.put("Stundentafel_Faecher",DevDTOStundentafelFaecher.class);
             mapTablename2DTOClass.put("EigeneSchule_Teilstandorte",DevDTOTeilstandorte.class);
             mapTablename2DTOClass.put("Katalog_Pausenzeiten",DevDTOKatalogPausenzeit.class);
             mapTablename2DTOClass.put("Katalog_Zeitraster",DevDTOKatalogZeitraster.class);
             mapTablename2DTOClass.put("Stundenplan",DevDTOStundenplan.class);
             mapTablename2DTOClass.put("Stundenplan_Aufsichtsbereiche",DevDTOStundenplanAufsichtsbereich.class);
             mapTablename2DTOClass.put("Stundenplan_Pausenaufsichten",DevDTOStundenplanPausenaufsichten.class);
             mapTablename2DTOClass.put("Stundenplan_PausenaufsichtenBereich",DevDTOStundenplanPausenaufsichtenBereiche.class);
             mapTablename2DTOClass.put("Stundenplan_Pausenzeit",DevDTOStundenplanPausenzeit.class);
             mapTablename2DTOClass.put("Stundenplan_Raeume",DevDTOStundenplanRaum.class);
             mapTablename2DTOClass.put("Stundenplan_Unterricht",DevDTOStundenplanUnterricht.class);
             mapTablename2DTOClass.put("Stundenplan_UnterrichtLehrer",DevDTOStundenplanUnterrichtLehrer.class);
             mapTablename2DTOClass.put("Stundenplan_UnterrichtRaum",DevDTOStundenplanUnterrichtRaum.class);
             mapTablename2DTOClass.put("Stundenplan_Zeitraster",DevDTOStundenplanZeitraster.class);
             mapTablename2DTOClass.put("SchuelerStatus_Keys",DevDTOSchuelerStatus.class);
             mapTablename2DTOClass.put("Herkunft_Keys",DevDTOHerkunftKeys.class);
             mapTablename2DTOClass.put("Herkunftsart_Keys",DevDTOHerkunftsartKeys.class);
             mapTablename2DTOClass.put("KAoA_Anschlussoption_Keys",DevDTOKAoAAnschlussoptionKeys.class);
             mapTablename2DTOClass.put("KAoA_Berufsfeld_Keys",DevDTOKAoABerufsfeldKeys.class);
             mapTablename2DTOClass.put("KAoA_Kategorie_Keys",DevDTOKAoAKategorieKeys.class);
             mapTablename2DTOClass.put("KAoA_Merkmal_Keys",DevDTOKAoAMerkmalKeys.class);
             mapTablename2DTOClass.put("KAoA_SBO_Ebene4_Keys",DevDTOKAoASBOEB4Keys.class);
             mapTablename2DTOClass.put("KAoA_Zusatzmerkmal_Keys",DevDTOKAoAZusatzmerkmalKeys.class);
             mapTablename2DTOClass.put("Nationalitaeten_Keys",DevDTONationalitaetenKeys.class);
             mapTablename2DTOClass.put("Religionen_Keys",DevDTOReligionKeys.class);
             mapTablename2DTOClass.put("Credentials",DevDTOCredentials.class);
             mapTablename2DTOClass.put("CredentialsLernplattformen",DevDTOCredentialsLernplattformen.class);
             mapTablename2DTOClass.put("Lernplattformen",DevDTOLernplattformen.class);
             mapTablename2DTOClass.put("SchuleCredentials",DevDTOSchuleCredentials.class);
             mapTablename2DTOClass.put("SVWS_Client_Konfiguration_Benutzer",DevDTOClientKonfigurationBenutzer.class);
             mapTablename2DTOClass.put("SVWS_Client_Konfiguration_Global",DevDTOClientKonfigurationGlobal.class);
             mapTablename2DTOClass.put("DavRessources",DevDTODavRessource.class);
             mapTablename2DTOClass.put("DavRessourceCollections",DevDTODavRessourceCollection.class);
             mapTablename2DTOClass.put("DavRessourceCollectionsACL",DevDTODavRessourceCollectionsACL.class);
             mapTablename2DTOClass.put("DavSyncTokenLehrer",DevDTODavSyncTokenLehrer.class);
             mapTablename2DTOClass.put("DavSyncTokenSchueler",DevDTODavSyncTokenSchueler.class);
             mapTablename2DTOClass.put("SVWS_Core_Type_Versionen",DevDTOCoreTypeVersion.class);
             mapTablename2DTOClass.put("SVWS_DB_AutoInkremente",DevDTODBAutoInkremente.class);
             mapTablename2DTOClass.put("SVWS_DB_Version",DevDTODBVersion.class);
             mapTablename2DTOClass.put("EnmLeistungsdaten",DevDTOEnmLeistungsdaten.class);
             mapTablename2DTOClass.put("EnmLernabschnittsdaten",DevDTOEnmLernabschnittsdaten.class);
             mapTablename2DTOClass.put("V_Benutzer",DevDTOViewBenutzer.class);
             mapTablename2DTOClass.put("V_Benutzerkompetenzen",DevDTOViewBenutzerKompetenz.class);
             mapTablename2DTOClass.put("V_BenutzerDetails",DevDTOViewBenutzerdetails.class);
             mapTablename2DTOClass.put("V_Gost_Schueler_Abiturjahrgang",DevDTOViewGostSchuelerAbiturjahrgang.class);
         }
         return mapTablename2DTOClass;
     }


    /**
     * Gibt die DTO-Klasse mit dem angegebenen Tabellennamen zurück.
     *
     * @param name   der Tabellenname
     *
     * @return die DTO-Klasse
     */
    public static Class<? extends Object> getFromTableName(String name) {
    	return getMapTablename2DTOClass().get(name);
    }

}
