package de.nrw.schule.svws.db.dto;

import java.util.HashMap;

import de.nrw.schule.svws.db.dto.rev8.coretypes.Rev8DTOKursFortschreibungsart;
import de.nrw.schule.svws.db.dto.rev8.coretypes.Rev8DTONote;
import de.nrw.schule.svws.db.dto.rev8.coretypes.Rev8DTOPersonalTyp;
import de.nrw.schule.svws.db.dto.rev8.coretypes.Rev8DTOSchuelerStatus;
import de.nrw.schule.svws.db.dto.rev8.gost.Rev8DTOGostJahrgangBeratungslehrer;
import de.nrw.schule.svws.db.dto.rev8.gost.Rev8DTOGostJahrgangFachkombinationen;
import de.nrw.schule.svws.db.dto.rev8.gost.Rev8DTOGostJahrgangFaecher;
import de.nrw.schule.svws.db.dto.rev8.gost.Rev8DTOGostJahrgangsdaten;
import de.nrw.schule.svws.db.dto.rev8.gost.Rev8DTOGostSchueler;
import de.nrw.schule.svws.db.dto.rev8.gost.Rev8DTOGostSchuelerFachbelegungen;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockung;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungKurs;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungKurslehrer;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungRegel;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungRegelParameter;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungSchiene;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungZwischenergebnis;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungZwischenergebnisKursSchiene;
import de.nrw.schule.svws.db.dto.rev8.gost.kursblockung.Rev8DTOGostBlockungZwischenergebnisKursSchueler;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOSchildAuswahlFilter;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOSchildVerwaltung;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOSchuelerIndividuelleGruppe;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOSchuelerIndividuelleGruppeSchueler;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOSchuelerReportvorlagen;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOSchuelerWiedervorlage;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOTextExportVorlagen;
import de.nrw.schule.svws.db.dto.rev8.schild.Rev8DTOZuordnungReportvorlagen;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzer;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzerAllgemein;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzerMail;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzergruppe;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzergruppenKompetenz;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOBenutzergruppenMitglied;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOKatalogBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOKatalogBenutzerKompetenzGruppe;
import de.nrw.schule.svws.db.dto.rev8.schild.benutzer.Rev8DTOProtokollLogin;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOBeschaeftigungsart;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOFachgliederungen;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOFachklassen;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOKatalogZertifikate;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOSchuelerBKAbschluss;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOSchuelerBKFach;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOSchuelerZuweisung;
import de.nrw.schule.svws.db.dto.rev8.schild.berufskolleg.Rev8DTOZertifikate;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOErzieherDatenschutz;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOErzieherLernplattform;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOErzieherart;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOErzieherfunktion;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOSchuelerErzieherAdresse;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOSchuelerTelefon;
import de.nrw.schule.svws.db.dto.rev8.schild.erzieher.Rev8DTOTelefonArt;
import de.nrw.schule.svws.db.dto.rev8.schild.faecher.Rev8DTOFach;
import de.nrw.schule.svws.db.dto.rev8.schild.faecher.Rev8DTOFachTeilleistungsarten;
import de.nrw.schule.svws.db.dto.rev8.schild.faecher.Rev8DTOFachgruppen;
import de.nrw.schule.svws.db.dto.rev8.schild.faecher.Rev8DTOFaecherKatalog;
import de.nrw.schule.svws.db.dto.rev8.schild.faecher.Rev8DTOFaecherKatalogKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.faecher.Rev8DTOFaecherKatalogSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.gost.Rev8DTOFaecherNichtMoeglicheKombination;
import de.nrw.schule.svws.db.dto.rev8.schild.grundschule.Rev8DTOAnkreuzdaten;
import de.nrw.schule.svws.db.dto.rev8.schild.grundschule.Rev8DTOAnkreuzfloskeln;
import de.nrw.schule.svws.db.dto.rev8.schild.grundschule.Rev8DTOKindergarten;
import de.nrw.schule.svws.db.dto.rev8.schild.grundschule.Rev8DTOSchuelerAnkreuzfloskeln;
import de.nrw.schule.svws.db.dto.rev8.schild.impexp.Rev8DTOEigeneImporte;
import de.nrw.schule.svws.db.dto.rev8.schild.impexp.Rev8DTOEigeneImporteFelder;
import de.nrw.schule.svws.db.dto.rev8.schild.impexp.Rev8DTOEigeneImporteTabellen;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternAbiturInfos;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternDQRNiveaus;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternDatenart;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternFaecherSortierung;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternFilterFehlendeEintraege;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternFilterFehlendeEintraegeSchild3;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternFilterFeldListe;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternLaender;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternPrfSemesterAbschluss;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternPruefungsOrdnung;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternPruefungsOrdnungOptionen;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternSchuelerImportExport;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternSchuelerStatus;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternSpezialFilterFelder;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternTextExport;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternUnicodeUmwandllung;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternVerfImportFelder;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternVerfImportTabellen;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOInternZusatzinfos;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOKAoAAnschlussoption;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOKAoABerufsfeld;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOKAoAKategorie;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOKAoAMerkmal;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOKAoASBOEB4;
import de.nrw.schule.svws.db.dto.rev8.schild.intern.Rev8DTOKAoAZusatzmerkmal;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOAnsprechpartnerAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOFahrschuelerart;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOFloskelgruppen;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOFloskeln;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOHaltestellen;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKatalogAdressart;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKatalogAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKatalogAufsichtsbereich;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKatalogDatenschutz;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKatalogRaum;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKonfession;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOKursarten;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOOrt;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOOrtsteil;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOSchuleNRW;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOSchulfunktion;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOSchwerpunkt;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOTextDateien;
import de.nrw.schule.svws.db.dto.rev8.schild.katalog.Rev8DTOVermerkArt;
import de.nrw.schule.svws.db.dto.rev8.schild.klassen.Rev8DTOKlassen;
import de.nrw.schule.svws.db.dto.rev8.schild.klassen.Rev8DTOKlassenLeitung;
import de.nrw.schule.svws.db.dto.rev8.schild.klassen.Rev8DTOKlassenartenKatalog;
import de.nrw.schule.svws.db.dto.rev8.schild.klassen.Rev8DTOKlassenartenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.klassen.Rev8DTOKlassenartenKatalogSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.kurse.Rev8DTOKurs;
import de.nrw.schule.svws.db.dto.rev8.schild.kurse.Rev8DTOKursLehrer;
import de.nrw.schule.svws.db.dto.rev8.schild.kurse.Rev8DTOKursSchueler;
import de.nrw.schule.svws.db.dto.rev8.schild.kurse.Rev8DTOKursartenKatalog;
import de.nrw.schule.svws.db.dto.rev8.schild.kurse.Rev8DTOKursartenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.kurse.Rev8DTOKursartenKatalogSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrer;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerAbschnittsdaten;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerAnrechnungsstunde;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerDatenschutz;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerEntlastungsstunde;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerFoto;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerFunktion;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerLehramt;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerLehramtBefaehigung;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerLehramtFachrichtung;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerLernplattform;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOLehrerMehrleistung;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOSchulleitung;
import de.nrw.schule.svws.db.dto.rev8.schild.lehrer.Rev8DTOSchulleitungFunktion;
import de.nrw.schule.svws.db.dto.rev8.schild.personengruppen.Rev8DTOPersonengruppen;
import de.nrw.schule.svws.db.dto.rev8.schild.personengruppen.Rev8DTOPersonengruppenPersonen;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOEinschulungsart;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOEntlassarten;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOFoerderschwerpunkt;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchueler;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerAbgaenge;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerDatenschutz;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerFehlstunden;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerFoerderempfehlung;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerFoto;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerGrundschuldaten;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerKAoADaten;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerLeistungsdaten;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerLernabschnittsdaten;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerLernplattform;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerMerkmale;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerPSFachBemerkungen;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerSprachenfolge;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerSprachpruefungen;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerTeilleistung;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerVermerke;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSchuelerZP10;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOSportbefreiung;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.Rev8DTOTeilleistungsarten;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.abitur.Rev8DTOSchuelerAbitur;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.abitur.Rev8DTOSchuelerAbiturFach;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.fhr.Rev8DTOSchuelerFHR;
import de.nrw.schule.svws.db.dto.rev8.schild.schueler.fhr.Rev8DTOSchuelerFHRFach;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAbteilungen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAbteilungsKlassen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleFoerderschwerpunkte;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleFoerderschwerpunkteSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleJahrgaenge;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleJahrgaengeBezeichnungen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleJahrgaengeKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleSchulgliederungen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleSchulgliederungenAbschluesseAllgmeinbildend;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleSchulgliederungenAbschluesseBerufsbildend;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAlleSchulgliederungenSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAllgemeineMerkmaleKatalog;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAllgemeineMerkmaleKatalogKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOAllgemeineMerkmaleKatalogSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOBerufskollegAnlagen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOBerufskollegBerufsebenen1;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOBerufskollegBerufsebenen2;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOBerufskollegBerufsebenen3;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOBerufskollegFachklassen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOBerufskollegFachklassenKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOEigeneSchule;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOEigeneSchuleKAoADaten;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOEinschulungsartenKatalog;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOEinschulungsartenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOHerkunft;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOHerkunftSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOHerkunftsart;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOHerkunftsartSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOJahrgang;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOMerkmale;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOOrganisationsformenKatalog;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOOrganisationsformenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOOrganisationsformenKatalogSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOSchulabschluesse_Allgemeinbildend;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOSchulabschluesse_Berufsbildend;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOSchulformen;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOSchuljahresabschnitte;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOSchultexte;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOStundentafel;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOStundentafelFaecher;
import de.nrw.schule.svws.db.dto.rev8.schild.schule.Rev8DTOTeilstandorte;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOKatalogPausenzeit;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOKatalogZeitraster;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplan;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanAufsichtsbereich;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanPausenaufsichten;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanPausenaufsichtenBereiche;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanPausenzeit;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanRaum;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanUnterricht;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanUnterrichtLehrer;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanUnterrichtRaum;
import de.nrw.schule.svws.db.dto.rev8.schild.stundenplan.Rev8DTOStundenplanZeitraster;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTOHerkunftKeys;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTOHerkunftsartKeys;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTONationalitaeten;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTONationalitaetenKeys;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTOReligion;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTOReligionKeys;
import de.nrw.schule.svws.db.dto.rev8.schule.Rev8DTOVerkehrssprachen;
import de.nrw.schule.svws.db.dto.rev8.schulver.Rev8DTOSchulverDBS;
import de.nrw.schule.svws.db.dto.rev8.schulver.Rev8DTOSchulverSchultraeger;
import de.nrw.schule.svws.db.dto.rev8.schulver.Rev8DTOSchulverWeitereSF;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOSVWSSprachpruefungNiveaus;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueAbgangsart;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueAndereGrundschulen;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueBilingual;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerAbgang;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerAnrechnung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerBeschaeftigungsart;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerEinsatzstatus;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerFachrichtung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerFachrichtungAnerkennung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerLehramt;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerLehramtAnerkennung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerLehrbefaehigung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerLehrbefaehigungAnerkennung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerMehrleistung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerMinderleistung;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerRechtsverhaeltnis;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueLehrerZugang;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkuePLZOrt;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueReformpaedagogik;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueSchuelerErsteSchulformSekI;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueSchuelerKindergartenbesuch;
import de.nrw.schule.svws.db.dto.rev8.statkue.Rev8DTOStatkueSchuelerUebergangsempfehlung5Jg;
import de.nrw.schule.svws.db.dto.rev8.svws.auth.Rev8DTOCredentials;
import de.nrw.schule.svws.db.dto.rev8.svws.auth.Rev8DTOCredentialsLernplattformen;
import de.nrw.schule.svws.db.dto.rev8.svws.auth.Rev8DTOLernplattformen;
import de.nrw.schule.svws.db.dto.rev8.svws.auth.Rev8DTOSchuleCredentials;
import de.nrw.schule.svws.db.dto.rev8.svws.client.Rev8DTOClientKonfigurationBenutzer;
import de.nrw.schule.svws.db.dto.rev8.svws.client.Rev8DTOClientKonfigurationGlobal;
import de.nrw.schule.svws.db.dto.rev8.svws.dav.Rev8DTODavRessource;
import de.nrw.schule.svws.db.dto.rev8.svws.dav.Rev8DTODavRessourceCollection;
import de.nrw.schule.svws.db.dto.rev8.svws.dav.Rev8DTODavRessourceCollectionsACL;
import de.nrw.schule.svws.db.dto.rev8.svws.dav.Rev8DTODavSyncTokenLehrer;
import de.nrw.schule.svws.db.dto.rev8.svws.dav.Rev8DTODavSyncTokenSchueler;
import de.nrw.schule.svws.db.dto.rev8.svws.db.Rev8DTOCoreTypeVersion;
import de.nrw.schule.svws.db.dto.rev8.svws.db.Rev8DTODBAutoInkremente;
import de.nrw.schule.svws.db.dto.rev8.svws.db.Rev8DTODBVersion;
import de.nrw.schule.svws.db.dto.rev8.views.schildintern.Rev8DTOSchildInternBerufsebenen;
import de.nrw.schule.svws.db.dto.rev8.views.schildintern.Rev8DTOSchildInternFachgruppen;
import de.nrw.schule.svws.db.dto.rev8.views.schildintern.Rev8DTOSchildInternNote;
import de.nrw.schule.svws.db.dto.rev8.views.schulver.Rev8DTOSchulverSchulformen;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueFachklasse;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueFoerderschwerpunkte;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueSchulformen;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueGliederung;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueHerkunftsschulform;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueHerkunftsart;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOSVWSSchulgliederungen;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueNationalitaeten;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueSchuelerVerkehrssprache;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueZulaessigerJahrgang;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueZulaessigeKlassenart;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueZulaessigeKursart;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueZulaessigesFach;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOSVWSZulaessigeFaecherMapping;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueEinschulungsart;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueAllgMerkmale;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueReligion;
import de.nrw.schule.svws.db.dto.rev8.views.statkue.Rev8DTOStatkueOrganisationsform;
import de.nrw.schule.svws.db.dto.rev8.views.benutzer.Rev8DTOViewBenutzer;
import de.nrw.schule.svws.db.dto.rev8.views.benutzer.Rev8DTOViewBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.rev8.views.benutzer.Rev8DTOViewBenutzerdetails;
import de.nrw.schule.svws.db.dto.rev8.views.gost.Rev8DTOViewGostSchuelerAbiturjahrgang;

/**
 * Diese Klasse dient als Verzeichnis aller Datenbank-DTO-Klassen.
 * Sie wurde automatisch per Skript generiert und sollte nicht verändert werden,
 * da sie aufgrund von Änderungen am DB-Schema ggf. neu generiert und überschrieben wird.
 */
public class Rev8DTOs {

    /** Enthält das Mapping der Namen aller Java-DTO-Klassen für die SVWS-DB zu den entsprechenden Java-DTO-Klassen. */
    private static HashMap<String, Class<? extends Object>> mapDTOName2DTOClass = null;

    /** Enthält das Mapping der Datenbank-Tabellennamen zu den zugehörigen Java-DTO-Klassen für die SVWS-DB. */
    private static HashMap<String, Class<? extends Object>> mapTablename2DTOClass = null;


    /**
     * Gibt das Mapping der Datenbank-Tabellennamen zu den zugehörigen Java-DTO-Klassen für die SVWS-DB zurück.
     *
     * @return eine Hashmap mit dem Mapping
     */
     private static final HashMap<String, Class<? extends Object>> getMapDTOName2DTOClass() {
         if (mapDTOName2DTOClass == null) {
             mapDTOName2DTOClass = new HashMap<>();
             mapDTOName2DTOClass.put(Rev8DTOKursFortschreibungsart.class.getSimpleName(),Rev8DTOKursFortschreibungsart.class);
             mapDTOName2DTOClass.put(Rev8DTONote.class.getSimpleName(),Rev8DTONote.class);
             mapDTOName2DTOClass.put(Rev8DTOPersonalTyp.class.getSimpleName(),Rev8DTOPersonalTyp.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerStatus.class.getSimpleName(),Rev8DTOSchuelerStatus.class);
             mapDTOName2DTOClass.put(Rev8DTOGostJahrgangBeratungslehrer.class.getSimpleName(),Rev8DTOGostJahrgangBeratungslehrer.class);
             mapDTOName2DTOClass.put(Rev8DTOGostJahrgangFachkombinationen.class.getSimpleName(),Rev8DTOGostJahrgangFachkombinationen.class);
             mapDTOName2DTOClass.put(Rev8DTOGostJahrgangFaecher.class.getSimpleName(),Rev8DTOGostJahrgangFaecher.class);
             mapDTOName2DTOClass.put(Rev8DTOGostJahrgangsdaten.class.getSimpleName(),Rev8DTOGostJahrgangsdaten.class);
             mapDTOName2DTOClass.put(Rev8DTOGostSchueler.class.getSimpleName(),Rev8DTOGostSchueler.class);
             mapDTOName2DTOClass.put(Rev8DTOGostSchuelerFachbelegungen.class.getSimpleName(),Rev8DTOGostSchuelerFachbelegungen.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockung.class.getSimpleName(),Rev8DTOGostBlockung.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungKurs.class.getSimpleName(),Rev8DTOGostBlockungKurs.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungKurslehrer.class.getSimpleName(),Rev8DTOGostBlockungKurslehrer.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungRegel.class.getSimpleName(),Rev8DTOGostBlockungRegel.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungRegelParameter.class.getSimpleName(),Rev8DTOGostBlockungRegelParameter.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungSchiene.class.getSimpleName(),Rev8DTOGostBlockungSchiene.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungZwischenergebnis.class.getSimpleName(),Rev8DTOGostBlockungZwischenergebnis.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungZwischenergebnisKursSchiene.class.getSimpleName(),Rev8DTOGostBlockungZwischenergebnisKursSchiene.class);
             mapDTOName2DTOClass.put(Rev8DTOGostBlockungZwischenergebnisKursSchueler.class.getSimpleName(),Rev8DTOGostBlockungZwischenergebnisKursSchueler.class);
             mapDTOName2DTOClass.put(Rev8DTOSchildAuswahlFilter.class.getSimpleName(),Rev8DTOSchildAuswahlFilter.class);
             mapDTOName2DTOClass.put(Rev8DTOSchildVerwaltung.class.getSimpleName(),Rev8DTOSchildVerwaltung.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerIndividuelleGruppe.class.getSimpleName(),Rev8DTOSchuelerIndividuelleGruppe.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerIndividuelleGruppeSchueler.class.getSimpleName(),Rev8DTOSchuelerIndividuelleGruppeSchueler.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerReportvorlagen.class.getSimpleName(),Rev8DTOSchuelerReportvorlagen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerWiedervorlage.class.getSimpleName(),Rev8DTOSchuelerWiedervorlage.class);
             mapDTOName2DTOClass.put(Rev8DTOTextExportVorlagen.class.getSimpleName(),Rev8DTOTextExportVorlagen.class);
             mapDTOName2DTOClass.put(Rev8DTOZuordnungReportvorlagen.class.getSimpleName(),Rev8DTOZuordnungReportvorlagen.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzer.class.getSimpleName(),Rev8DTOBenutzer.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzerAllgemein.class.getSimpleName(),Rev8DTOBenutzerAllgemein.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzerKompetenz.class.getSimpleName(),Rev8DTOBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzerMail.class.getSimpleName(),Rev8DTOBenutzerMail.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzergruppe.class.getSimpleName(),Rev8DTOBenutzergruppe.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzergruppenKompetenz.class.getSimpleName(),Rev8DTOBenutzergruppenKompetenz.class);
             mapDTOName2DTOClass.put(Rev8DTOBenutzergruppenMitglied.class.getSimpleName(),Rev8DTOBenutzergruppenMitglied.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogBenutzerKompetenz.class.getSimpleName(),Rev8DTOKatalogBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogBenutzerKompetenzGruppe.class.getSimpleName(),Rev8DTOKatalogBenutzerKompetenzGruppe.class);
             mapDTOName2DTOClass.put(Rev8DTOProtokollLogin.class.getSimpleName(),Rev8DTOProtokollLogin.class);
             mapDTOName2DTOClass.put(Rev8DTOBeschaeftigungsart.class.getSimpleName(),Rev8DTOBeschaeftigungsart.class);
             mapDTOName2DTOClass.put(Rev8DTOFachgliederungen.class.getSimpleName(),Rev8DTOFachgliederungen.class);
             mapDTOName2DTOClass.put(Rev8DTOFachklassen.class.getSimpleName(),Rev8DTOFachklassen.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogZertifikate.class.getSimpleName(),Rev8DTOKatalogZertifikate.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerBKAbschluss.class.getSimpleName(),Rev8DTOSchuelerBKAbschluss.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerBKFach.class.getSimpleName(),Rev8DTOSchuelerBKFach.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerZuweisung.class.getSimpleName(),Rev8DTOSchuelerZuweisung.class);
             mapDTOName2DTOClass.put(Rev8DTOZertifikate.class.getSimpleName(),Rev8DTOZertifikate.class);
             mapDTOName2DTOClass.put(Rev8DTOErzieherDatenschutz.class.getSimpleName(),Rev8DTOErzieherDatenschutz.class);
             mapDTOName2DTOClass.put(Rev8DTOErzieherLernplattform.class.getSimpleName(),Rev8DTOErzieherLernplattform.class);
             mapDTOName2DTOClass.put(Rev8DTOErzieherart.class.getSimpleName(),Rev8DTOErzieherart.class);
             mapDTOName2DTOClass.put(Rev8DTOErzieherfunktion.class.getSimpleName(),Rev8DTOErzieherfunktion.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerErzieherAdresse.class.getSimpleName(),Rev8DTOSchuelerErzieherAdresse.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerTelefon.class.getSimpleName(),Rev8DTOSchuelerTelefon.class);
             mapDTOName2DTOClass.put(Rev8DTOTelefonArt.class.getSimpleName(),Rev8DTOTelefonArt.class);
             mapDTOName2DTOClass.put(Rev8DTOFach.class.getSimpleName(),Rev8DTOFach.class);
             mapDTOName2DTOClass.put(Rev8DTOFachTeilleistungsarten.class.getSimpleName(),Rev8DTOFachTeilleistungsarten.class);
             mapDTOName2DTOClass.put(Rev8DTOFachgruppen.class.getSimpleName(),Rev8DTOFachgruppen.class);
             mapDTOName2DTOClass.put(Rev8DTOFaecherKatalog.class.getSimpleName(),Rev8DTOFaecherKatalog.class);
             mapDTOName2DTOClass.put(Rev8DTOFaecherKatalogKeys.class.getSimpleName(),Rev8DTOFaecherKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOFaecherKatalogSchulformen.class.getSimpleName(),Rev8DTOFaecherKatalogSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOFaecherNichtMoeglicheKombination.class.getSimpleName(),Rev8DTOFaecherNichtMoeglicheKombination.class);
             mapDTOName2DTOClass.put(Rev8DTOAnkreuzdaten.class.getSimpleName(),Rev8DTOAnkreuzdaten.class);
             mapDTOName2DTOClass.put(Rev8DTOAnkreuzfloskeln.class.getSimpleName(),Rev8DTOAnkreuzfloskeln.class);
             mapDTOName2DTOClass.put(Rev8DTOKindergarten.class.getSimpleName(),Rev8DTOKindergarten.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerAnkreuzfloskeln.class.getSimpleName(),Rev8DTOSchuelerAnkreuzfloskeln.class);
             mapDTOName2DTOClass.put(Rev8DTOEigeneImporte.class.getSimpleName(),Rev8DTOEigeneImporte.class);
             mapDTOName2DTOClass.put(Rev8DTOEigeneImporteFelder.class.getSimpleName(),Rev8DTOEigeneImporteFelder.class);
             mapDTOName2DTOClass.put(Rev8DTOEigeneImporteTabellen.class.getSimpleName(),Rev8DTOEigeneImporteTabellen.class);
             mapDTOName2DTOClass.put(Rev8DTOInternAbiturInfos.class.getSimpleName(),Rev8DTOInternAbiturInfos.class);
             mapDTOName2DTOClass.put(Rev8DTOInternDQRNiveaus.class.getSimpleName(),Rev8DTOInternDQRNiveaus.class);
             mapDTOName2DTOClass.put(Rev8DTOInternDatenart.class.getSimpleName(),Rev8DTOInternDatenart.class);
             mapDTOName2DTOClass.put(Rev8DTOInternFaecherSortierung.class.getSimpleName(),Rev8DTOInternFaecherSortierung.class);
             mapDTOName2DTOClass.put(Rev8DTOInternFilterFehlendeEintraege.class.getSimpleName(),Rev8DTOInternFilterFehlendeEintraege.class);
             mapDTOName2DTOClass.put(Rev8DTOInternFilterFehlendeEintraegeSchild3.class.getSimpleName(),Rev8DTOInternFilterFehlendeEintraegeSchild3.class);
             mapDTOName2DTOClass.put(Rev8DTOInternFilterFeldListe.class.getSimpleName(),Rev8DTOInternFilterFeldListe.class);
             mapDTOName2DTOClass.put(Rev8DTOInternLaender.class.getSimpleName(),Rev8DTOInternLaender.class);
             mapDTOName2DTOClass.put(Rev8DTOInternPrfSemesterAbschluss.class.getSimpleName(),Rev8DTOInternPrfSemesterAbschluss.class);
             mapDTOName2DTOClass.put(Rev8DTOInternPruefungsOrdnung.class.getSimpleName(),Rev8DTOInternPruefungsOrdnung.class);
             mapDTOName2DTOClass.put(Rev8DTOInternPruefungsOrdnungOptionen.class.getSimpleName(),Rev8DTOInternPruefungsOrdnungOptionen.class);
             mapDTOName2DTOClass.put(Rev8DTOInternSchuelerImportExport.class.getSimpleName(),Rev8DTOInternSchuelerImportExport.class);
             mapDTOName2DTOClass.put(Rev8DTOInternSchuelerStatus.class.getSimpleName(),Rev8DTOInternSchuelerStatus.class);
             mapDTOName2DTOClass.put(Rev8DTOInternSpezialFilterFelder.class.getSimpleName(),Rev8DTOInternSpezialFilterFelder.class);
             mapDTOName2DTOClass.put(Rev8DTOInternTextExport.class.getSimpleName(),Rev8DTOInternTextExport.class);
             mapDTOName2DTOClass.put(Rev8DTOInternUnicodeUmwandllung.class.getSimpleName(),Rev8DTOInternUnicodeUmwandllung.class);
             mapDTOName2DTOClass.put(Rev8DTOInternVerfImportFelder.class.getSimpleName(),Rev8DTOInternVerfImportFelder.class);
             mapDTOName2DTOClass.put(Rev8DTOInternVerfImportTabellen.class.getSimpleName(),Rev8DTOInternVerfImportTabellen.class);
             mapDTOName2DTOClass.put(Rev8DTOInternZusatzinfos.class.getSimpleName(),Rev8DTOInternZusatzinfos.class);
             mapDTOName2DTOClass.put(Rev8DTOKAoAAnschlussoption.class.getSimpleName(),Rev8DTOKAoAAnschlussoption.class);
             mapDTOName2DTOClass.put(Rev8DTOKAoABerufsfeld.class.getSimpleName(),Rev8DTOKAoABerufsfeld.class);
             mapDTOName2DTOClass.put(Rev8DTOKAoAKategorie.class.getSimpleName(),Rev8DTOKAoAKategorie.class);
             mapDTOName2DTOClass.put(Rev8DTOKAoAMerkmal.class.getSimpleName(),Rev8DTOKAoAMerkmal.class);
             mapDTOName2DTOClass.put(Rev8DTOKAoASBOEB4.class.getSimpleName(),Rev8DTOKAoASBOEB4.class);
             mapDTOName2DTOClass.put(Rev8DTOKAoAZusatzmerkmal.class.getSimpleName(),Rev8DTOKAoAZusatzmerkmal.class);
             mapDTOName2DTOClass.put(Rev8DTOAnsprechpartnerAllgemeineAdresse.class.getSimpleName(),Rev8DTOAnsprechpartnerAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(Rev8DTOFahrschuelerart.class.getSimpleName(),Rev8DTOFahrschuelerart.class);
             mapDTOName2DTOClass.put(Rev8DTOFloskelgruppen.class.getSimpleName(),Rev8DTOFloskelgruppen.class);
             mapDTOName2DTOClass.put(Rev8DTOFloskeln.class.getSimpleName(),Rev8DTOFloskeln.class);
             mapDTOName2DTOClass.put(Rev8DTOHaltestellen.class.getSimpleName(),Rev8DTOHaltestellen.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogAdressart.class.getSimpleName(),Rev8DTOKatalogAdressart.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogAllgemeineAdresse.class.getSimpleName(),Rev8DTOKatalogAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogAufsichtsbereich.class.getSimpleName(),Rev8DTOKatalogAufsichtsbereich.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogDatenschutz.class.getSimpleName(),Rev8DTOKatalogDatenschutz.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogRaum.class.getSimpleName(),Rev8DTOKatalogRaum.class);
             mapDTOName2DTOClass.put(Rev8DTOKonfession.class.getSimpleName(),Rev8DTOKonfession.class);
             mapDTOName2DTOClass.put(Rev8DTOKursarten.class.getSimpleName(),Rev8DTOKursarten.class);
             mapDTOName2DTOClass.put(Rev8DTOOrt.class.getSimpleName(),Rev8DTOOrt.class);
             mapDTOName2DTOClass.put(Rev8DTOOrtsteil.class.getSimpleName(),Rev8DTOOrtsteil.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuleNRW.class.getSimpleName(),Rev8DTOSchuleNRW.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulfunktion.class.getSimpleName(),Rev8DTOSchulfunktion.class);
             mapDTOName2DTOClass.put(Rev8DTOSchwerpunkt.class.getSimpleName(),Rev8DTOSchwerpunkt.class);
             mapDTOName2DTOClass.put(Rev8DTOTextDateien.class.getSimpleName(),Rev8DTOTextDateien.class);
             mapDTOName2DTOClass.put(Rev8DTOVermerkArt.class.getSimpleName(),Rev8DTOVermerkArt.class);
             mapDTOName2DTOClass.put(Rev8DTOKlassen.class.getSimpleName(),Rev8DTOKlassen.class);
             mapDTOName2DTOClass.put(Rev8DTOKlassenLeitung.class.getSimpleName(),Rev8DTOKlassenLeitung.class);
             mapDTOName2DTOClass.put(Rev8DTOKlassenartenKatalog.class.getSimpleName(),Rev8DTOKlassenartenKatalog.class);
             mapDTOName2DTOClass.put(Rev8DTOKlassenartenKatalogKeys.class.getSimpleName(),Rev8DTOKlassenartenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOKlassenartenKatalogSchulformen.class.getSimpleName(),Rev8DTOKlassenartenKatalogSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOKurs.class.getSimpleName(),Rev8DTOKurs.class);
             mapDTOName2DTOClass.put(Rev8DTOKursLehrer.class.getSimpleName(),Rev8DTOKursLehrer.class);
             mapDTOName2DTOClass.put(Rev8DTOKursSchueler.class.getSimpleName(),Rev8DTOKursSchueler.class);
             mapDTOName2DTOClass.put(Rev8DTOKursartenKatalog.class.getSimpleName(),Rev8DTOKursartenKatalog.class);
             mapDTOName2DTOClass.put(Rev8DTOKursartenKatalogKeys.class.getSimpleName(),Rev8DTOKursartenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOKursartenKatalogSchulformen.class.getSimpleName(),Rev8DTOKursartenKatalogSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrer.class.getSimpleName(),Rev8DTOLehrer.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerAbschnittsdaten.class.getSimpleName(),Rev8DTOLehrerAbschnittsdaten.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerAnrechnungsstunde.class.getSimpleName(),Rev8DTOLehrerAnrechnungsstunde.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerDatenschutz.class.getSimpleName(),Rev8DTOLehrerDatenschutz.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerEntlastungsstunde.class.getSimpleName(),Rev8DTOLehrerEntlastungsstunde.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerFoto.class.getSimpleName(),Rev8DTOLehrerFoto.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerFunktion.class.getSimpleName(),Rev8DTOLehrerFunktion.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerLehramt.class.getSimpleName(),Rev8DTOLehrerLehramt.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerLehramtBefaehigung.class.getSimpleName(),Rev8DTOLehrerLehramtBefaehigung.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerLehramtFachrichtung.class.getSimpleName(),Rev8DTOLehrerLehramtFachrichtung.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerLernplattform.class.getSimpleName(),Rev8DTOLehrerLernplattform.class);
             mapDTOName2DTOClass.put(Rev8DTOLehrerMehrleistung.class.getSimpleName(),Rev8DTOLehrerMehrleistung.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulleitung.class.getSimpleName(),Rev8DTOSchulleitung.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulleitungFunktion.class.getSimpleName(),Rev8DTOSchulleitungFunktion.class);
             mapDTOName2DTOClass.put(Rev8DTOPersonengruppen.class.getSimpleName(),Rev8DTOPersonengruppen.class);
             mapDTOName2DTOClass.put(Rev8DTOPersonengruppenPersonen.class.getSimpleName(),Rev8DTOPersonengruppenPersonen.class);
             mapDTOName2DTOClass.put(Rev8DTOEinschulungsart.class.getSimpleName(),Rev8DTOEinschulungsart.class);
             mapDTOName2DTOClass.put(Rev8DTOEntlassarten.class.getSimpleName(),Rev8DTOEntlassarten.class);
             mapDTOName2DTOClass.put(Rev8DTOFoerderschwerpunkt.class.getSimpleName(),Rev8DTOFoerderschwerpunkt.class);
             mapDTOName2DTOClass.put(Rev8DTOSchueler.class.getSimpleName(),Rev8DTOSchueler.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerAbgaenge.class.getSimpleName(),Rev8DTOSchuelerAbgaenge.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerAllgemeineAdresse.class.getSimpleName(),Rev8DTOSchuelerAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerDatenschutz.class.getSimpleName(),Rev8DTOSchuelerDatenschutz.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerFehlstunden.class.getSimpleName(),Rev8DTOSchuelerFehlstunden.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerFoerderempfehlung.class.getSimpleName(),Rev8DTOSchuelerFoerderempfehlung.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerFoto.class.getSimpleName(),Rev8DTOSchuelerFoto.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerGrundschuldaten.class.getSimpleName(),Rev8DTOSchuelerGrundschuldaten.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerKAoADaten.class.getSimpleName(),Rev8DTOSchuelerKAoADaten.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerLeistungsdaten.class.getSimpleName(),Rev8DTOSchuelerLeistungsdaten.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerLernabschnittsdaten.class.getSimpleName(),Rev8DTOSchuelerLernabschnittsdaten.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerLernplattform.class.getSimpleName(),Rev8DTOSchuelerLernplattform.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerMerkmale.class.getSimpleName(),Rev8DTOSchuelerMerkmale.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerPSFachBemerkungen.class.getSimpleName(),Rev8DTOSchuelerPSFachBemerkungen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerSprachenfolge.class.getSimpleName(),Rev8DTOSchuelerSprachenfolge.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerSprachpruefungen.class.getSimpleName(),Rev8DTOSchuelerSprachpruefungen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerTeilleistung.class.getSimpleName(),Rev8DTOSchuelerTeilleistung.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerVermerke.class.getSimpleName(),Rev8DTOSchuelerVermerke.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerZP10.class.getSimpleName(),Rev8DTOSchuelerZP10.class);
             mapDTOName2DTOClass.put(Rev8DTOSportbefreiung.class.getSimpleName(),Rev8DTOSportbefreiung.class);
             mapDTOName2DTOClass.put(Rev8DTOTeilleistungsarten.class.getSimpleName(),Rev8DTOTeilleistungsarten.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerAbitur.class.getSimpleName(),Rev8DTOSchuelerAbitur.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerAbiturFach.class.getSimpleName(),Rev8DTOSchuelerAbiturFach.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerFHR.class.getSimpleName(),Rev8DTOSchuelerFHR.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuelerFHRFach.class.getSimpleName(),Rev8DTOSchuelerFHRFach.class);
             mapDTOName2DTOClass.put(Rev8DTOAbteilungen.class.getSimpleName(),Rev8DTOAbteilungen.class);
             mapDTOName2DTOClass.put(Rev8DTOAbteilungsKlassen.class.getSimpleName(),Rev8DTOAbteilungsKlassen.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleFoerderschwerpunkte.class.getSimpleName(),Rev8DTOAlleFoerderschwerpunkte.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleFoerderschwerpunkteSchulformen.class.getSimpleName(),Rev8DTOAlleFoerderschwerpunkteSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleJahrgaenge.class.getSimpleName(),Rev8DTOAlleJahrgaenge.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleJahrgaengeBezeichnungen.class.getSimpleName(),Rev8DTOAlleJahrgaengeBezeichnungen.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleJahrgaengeKeys.class.getSimpleName(),Rev8DTOAlleJahrgaengeKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleSchulformen.class.getSimpleName(),Rev8DTOAlleSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleSchulgliederungen.class.getSimpleName(),Rev8DTOAlleSchulgliederungen.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleSchulgliederungenAbschluesseAllgmeinbildend.class.getSimpleName(),Rev8DTOAlleSchulgliederungenAbschluesseAllgmeinbildend.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleSchulgliederungenAbschluesseBerufsbildend.class.getSimpleName(),Rev8DTOAlleSchulgliederungenAbschluesseBerufsbildend.class);
             mapDTOName2DTOClass.put(Rev8DTOAlleSchulgliederungenSchulformen.class.getSimpleName(),Rev8DTOAlleSchulgliederungenSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOAllgemeineMerkmaleKatalog.class.getSimpleName(),Rev8DTOAllgemeineMerkmaleKatalog.class);
             mapDTOName2DTOClass.put(Rev8DTOAllgemeineMerkmaleKatalogKeys.class.getSimpleName(),Rev8DTOAllgemeineMerkmaleKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOAllgemeineMerkmaleKatalogSchulformen.class.getSimpleName(),Rev8DTOAllgemeineMerkmaleKatalogSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOBerufskollegAnlagen.class.getSimpleName(),Rev8DTOBerufskollegAnlagen.class);
             mapDTOName2DTOClass.put(Rev8DTOBerufskollegBerufsebenen1.class.getSimpleName(),Rev8DTOBerufskollegBerufsebenen1.class);
             mapDTOName2DTOClass.put(Rev8DTOBerufskollegBerufsebenen2.class.getSimpleName(),Rev8DTOBerufskollegBerufsebenen2.class);
             mapDTOName2DTOClass.put(Rev8DTOBerufskollegBerufsebenen3.class.getSimpleName(),Rev8DTOBerufskollegBerufsebenen3.class);
             mapDTOName2DTOClass.put(Rev8DTOBerufskollegFachklassen.class.getSimpleName(),Rev8DTOBerufskollegFachklassen.class);
             mapDTOName2DTOClass.put(Rev8DTOBerufskollegFachklassenKeys.class.getSimpleName(),Rev8DTOBerufskollegFachklassenKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOEigeneSchule.class.getSimpleName(),Rev8DTOEigeneSchule.class);
             mapDTOName2DTOClass.put(Rev8DTOEigeneSchuleKAoADaten.class.getSimpleName(),Rev8DTOEigeneSchuleKAoADaten.class);
             mapDTOName2DTOClass.put(Rev8DTOEinschulungsartenKatalog.class.getSimpleName(),Rev8DTOEinschulungsartenKatalog.class);
             mapDTOName2DTOClass.put(Rev8DTOEinschulungsartenKatalogKeys.class.getSimpleName(),Rev8DTOEinschulungsartenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOHerkunft.class.getSimpleName(),Rev8DTOHerkunft.class);
             mapDTOName2DTOClass.put(Rev8DTOHerkunftSchulformen.class.getSimpleName(),Rev8DTOHerkunftSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOHerkunftsart.class.getSimpleName(),Rev8DTOHerkunftsart.class);
             mapDTOName2DTOClass.put(Rev8DTOHerkunftsartSchulformen.class.getSimpleName(),Rev8DTOHerkunftsartSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOJahrgang.class.getSimpleName(),Rev8DTOJahrgang.class);
             mapDTOName2DTOClass.put(Rev8DTOMerkmale.class.getSimpleName(),Rev8DTOMerkmale.class);
             mapDTOName2DTOClass.put(Rev8DTOOrganisationsformenKatalog.class.getSimpleName(),Rev8DTOOrganisationsformenKatalog.class);
             mapDTOName2DTOClass.put(Rev8DTOOrganisationsformenKatalogKeys.class.getSimpleName(),Rev8DTOOrganisationsformenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOOrganisationsformenKatalogSchulformen.class.getSimpleName(),Rev8DTOOrganisationsformenKatalogSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulabschluesse_Allgemeinbildend.class.getSimpleName(),Rev8DTOSchulabschluesse_Allgemeinbildend.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulabschluesse_Berufsbildend.class.getSimpleName(),Rev8DTOSchulabschluesse_Berufsbildend.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulformen.class.getSimpleName(),Rev8DTOSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuljahresabschnitte.class.getSimpleName(),Rev8DTOSchuljahresabschnitte.class);
             mapDTOName2DTOClass.put(Rev8DTOSchultexte.class.getSimpleName(),Rev8DTOSchultexte.class);
             mapDTOName2DTOClass.put(Rev8DTOStundentafel.class.getSimpleName(),Rev8DTOStundentafel.class);
             mapDTOName2DTOClass.put(Rev8DTOStundentafelFaecher.class.getSimpleName(),Rev8DTOStundentafelFaecher.class);
             mapDTOName2DTOClass.put(Rev8DTOTeilstandorte.class.getSimpleName(),Rev8DTOTeilstandorte.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogPausenzeit.class.getSimpleName(),Rev8DTOKatalogPausenzeit.class);
             mapDTOName2DTOClass.put(Rev8DTOKatalogZeitraster.class.getSimpleName(),Rev8DTOKatalogZeitraster.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplan.class.getSimpleName(),Rev8DTOStundenplan.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanAufsichtsbereich.class.getSimpleName(),Rev8DTOStundenplanAufsichtsbereich.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanPausenaufsichten.class.getSimpleName(),Rev8DTOStundenplanPausenaufsichten.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanPausenaufsichtenBereiche.class.getSimpleName(),Rev8DTOStundenplanPausenaufsichtenBereiche.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanPausenzeit.class.getSimpleName(),Rev8DTOStundenplanPausenzeit.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanRaum.class.getSimpleName(),Rev8DTOStundenplanRaum.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanUnterricht.class.getSimpleName(),Rev8DTOStundenplanUnterricht.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanUnterrichtLehrer.class.getSimpleName(),Rev8DTOStundenplanUnterrichtLehrer.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanUnterrichtRaum.class.getSimpleName(),Rev8DTOStundenplanUnterrichtRaum.class);
             mapDTOName2DTOClass.put(Rev8DTOStundenplanZeitraster.class.getSimpleName(),Rev8DTOStundenplanZeitraster.class);
             mapDTOName2DTOClass.put(Rev8DTOHerkunftKeys.class.getSimpleName(),Rev8DTOHerkunftKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOHerkunftsartKeys.class.getSimpleName(),Rev8DTOHerkunftsartKeys.class);
             mapDTOName2DTOClass.put(Rev8DTONationalitaeten.class.getSimpleName(),Rev8DTONationalitaeten.class);
             mapDTOName2DTOClass.put(Rev8DTONationalitaetenKeys.class.getSimpleName(),Rev8DTONationalitaetenKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOReligion.class.getSimpleName(),Rev8DTOReligion.class);
             mapDTOName2DTOClass.put(Rev8DTOReligionKeys.class.getSimpleName(),Rev8DTOReligionKeys.class);
             mapDTOName2DTOClass.put(Rev8DTOVerkehrssprachen.class.getSimpleName(),Rev8DTOVerkehrssprachen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulverDBS.class.getSimpleName(),Rev8DTOSchulverDBS.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulverSchultraeger.class.getSimpleName(),Rev8DTOSchulverSchultraeger.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulverWeitereSF.class.getSimpleName(),Rev8DTOSchulverWeitereSF.class);
             mapDTOName2DTOClass.put(Rev8DTOSVWSSprachpruefungNiveaus.class.getSimpleName(),Rev8DTOSVWSSprachpruefungNiveaus.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueAbgangsart.class.getSimpleName(),Rev8DTOStatkueAbgangsart.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueAndereGrundschulen.class.getSimpleName(),Rev8DTOStatkueAndereGrundschulen.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueBilingual.class.getSimpleName(),Rev8DTOStatkueBilingual.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerAbgang.class.getSimpleName(),Rev8DTOStatkueLehrerAbgang.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerAnrechnung.class.getSimpleName(),Rev8DTOStatkueLehrerAnrechnung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerBeschaeftigungsart.class.getSimpleName(),Rev8DTOStatkueLehrerBeschaeftigungsart.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerEinsatzstatus.class.getSimpleName(),Rev8DTOStatkueLehrerEinsatzstatus.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerFachrichtung.class.getSimpleName(),Rev8DTOStatkueLehrerFachrichtung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerFachrichtungAnerkennung.class.getSimpleName(),Rev8DTOStatkueLehrerFachrichtungAnerkennung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerLehramt.class.getSimpleName(),Rev8DTOStatkueLehrerLehramt.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerLehramtAnerkennung.class.getSimpleName(),Rev8DTOStatkueLehrerLehramtAnerkennung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerLehrbefaehigung.class.getSimpleName(),Rev8DTOStatkueLehrerLehrbefaehigung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerLehrbefaehigungAnerkennung.class.getSimpleName(),Rev8DTOStatkueLehrerLehrbefaehigungAnerkennung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerMehrleistung.class.getSimpleName(),Rev8DTOStatkueLehrerMehrleistung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerMinderleistung.class.getSimpleName(),Rev8DTOStatkueLehrerMinderleistung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerRechtsverhaeltnis.class.getSimpleName(),Rev8DTOStatkueLehrerRechtsverhaeltnis.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueLehrerZugang.class.getSimpleName(),Rev8DTOStatkueLehrerZugang.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkuePLZOrt.class.getSimpleName(),Rev8DTOStatkuePLZOrt.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueReformpaedagogik.class.getSimpleName(),Rev8DTOStatkueReformpaedagogik.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueSchuelerErsteSchulformSekI.class.getSimpleName(),Rev8DTOStatkueSchuelerErsteSchulformSekI.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueSchuelerKindergartenbesuch.class.getSimpleName(),Rev8DTOStatkueSchuelerKindergartenbesuch.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueSchuelerUebergangsempfehlung5Jg.class.getSimpleName(),Rev8DTOStatkueSchuelerUebergangsempfehlung5Jg.class);
             mapDTOName2DTOClass.put(Rev8DTOCredentials.class.getSimpleName(),Rev8DTOCredentials.class);
             mapDTOName2DTOClass.put(Rev8DTOCredentialsLernplattformen.class.getSimpleName(),Rev8DTOCredentialsLernplattformen.class);
             mapDTOName2DTOClass.put(Rev8DTOLernplattformen.class.getSimpleName(),Rev8DTOLernplattformen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchuleCredentials.class.getSimpleName(),Rev8DTOSchuleCredentials.class);
             mapDTOName2DTOClass.put(Rev8DTOClientKonfigurationBenutzer.class.getSimpleName(),Rev8DTOClientKonfigurationBenutzer.class);
             mapDTOName2DTOClass.put(Rev8DTOClientKonfigurationGlobal.class.getSimpleName(),Rev8DTOClientKonfigurationGlobal.class);
             mapDTOName2DTOClass.put(Rev8DTODavRessource.class.getSimpleName(),Rev8DTODavRessource.class);
             mapDTOName2DTOClass.put(Rev8DTODavRessourceCollection.class.getSimpleName(),Rev8DTODavRessourceCollection.class);
             mapDTOName2DTOClass.put(Rev8DTODavRessourceCollectionsACL.class.getSimpleName(),Rev8DTODavRessourceCollectionsACL.class);
             mapDTOName2DTOClass.put(Rev8DTODavSyncTokenLehrer.class.getSimpleName(),Rev8DTODavSyncTokenLehrer.class);
             mapDTOName2DTOClass.put(Rev8DTODavSyncTokenSchueler.class.getSimpleName(),Rev8DTODavSyncTokenSchueler.class);
             mapDTOName2DTOClass.put(Rev8DTOCoreTypeVersion.class.getSimpleName(),Rev8DTOCoreTypeVersion.class);
             mapDTOName2DTOClass.put(Rev8DTODBAutoInkremente.class.getSimpleName(),Rev8DTODBAutoInkremente.class);
             mapDTOName2DTOClass.put(Rev8DTODBVersion.class.getSimpleName(),Rev8DTODBVersion.class);
             mapDTOName2DTOClass.put(Rev8DTOSchildInternBerufsebenen.class.getSimpleName(),Rev8DTOSchildInternBerufsebenen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchildInternFachgruppen.class.getSimpleName(),Rev8DTOSchildInternFachgruppen.class);
             mapDTOName2DTOClass.put(Rev8DTOSchildInternNote.class.getSimpleName(),Rev8DTOSchildInternNote.class);
             mapDTOName2DTOClass.put(Rev8DTOSchulverSchulformen.class.getSimpleName(),Rev8DTOSchulverSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueFachklasse.class.getSimpleName(),Rev8DTOStatkueFachklasse.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueFoerderschwerpunkte.class.getSimpleName(),Rev8DTOStatkueFoerderschwerpunkte.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueSchulformen.class.getSimpleName(),Rev8DTOStatkueSchulformen.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueGliederung.class.getSimpleName(),Rev8DTOStatkueGliederung.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueHerkunftsschulform.class.getSimpleName(),Rev8DTOStatkueHerkunftsschulform.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueHerkunftsart.class.getSimpleName(),Rev8DTOStatkueHerkunftsart.class);
             mapDTOName2DTOClass.put(Rev8DTOSVWSSchulgliederungen.class.getSimpleName(),Rev8DTOSVWSSchulgliederungen.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueNationalitaeten.class.getSimpleName(),Rev8DTOStatkueNationalitaeten.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueSchuelerVerkehrssprache.class.getSimpleName(),Rev8DTOStatkueSchuelerVerkehrssprache.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueZulaessigerJahrgang.class.getSimpleName(),Rev8DTOStatkueZulaessigerJahrgang.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueZulaessigeKlassenart.class.getSimpleName(),Rev8DTOStatkueZulaessigeKlassenart.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueZulaessigeKursart.class.getSimpleName(),Rev8DTOStatkueZulaessigeKursart.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueZulaessigesFach.class.getSimpleName(),Rev8DTOStatkueZulaessigesFach.class);
             mapDTOName2DTOClass.put(Rev8DTOSVWSZulaessigeFaecherMapping.class.getSimpleName(),Rev8DTOSVWSZulaessigeFaecherMapping.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueEinschulungsart.class.getSimpleName(),Rev8DTOStatkueEinschulungsart.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueAllgMerkmale.class.getSimpleName(),Rev8DTOStatkueAllgMerkmale.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueReligion.class.getSimpleName(),Rev8DTOStatkueReligion.class);
             mapDTOName2DTOClass.put(Rev8DTOStatkueOrganisationsform.class.getSimpleName(),Rev8DTOStatkueOrganisationsform.class);
             mapDTOName2DTOClass.put(Rev8DTOViewBenutzer.class.getSimpleName(),Rev8DTOViewBenutzer.class);
             mapDTOName2DTOClass.put(Rev8DTOViewBenutzerKompetenz.class.getSimpleName(),Rev8DTOViewBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(Rev8DTOViewBenutzerdetails.class.getSimpleName(),Rev8DTOViewBenutzerdetails.class);
             mapDTOName2DTOClass.put(Rev8DTOViewGostSchuelerAbiturjahrgang.class.getSimpleName(),Rev8DTOViewGostSchuelerAbiturjahrgang.class);
         }
         return mapDTOName2DTOClass;
     }


    /**
     * Gibt die DTO-Klasse mit dem angegebenen DTO-Namen zurück.
     *
     * @param name   der DTO-Name
     *
     * @return die DTO-Klasse
     */
    public static Class<? extends Object> getFromDTOName(String name) {
    	return getMapDTOName2DTOClass().get(name);
    }


    /**
     * Gibt das Mapping der Namen aller Java-DTO-Klassen für die SVWS-DB zu den zugehörigen
     * Java-DTO-Klassen zurück.
     *
     * @return eine Hashmap mit dem Mapping
     */
     private static final HashMap<String, Class<? extends Object>> getMapTablename2DTOClass() {
         if (mapTablename2DTOClass == null) {
             mapTablename2DTOClass = new HashMap<>();
             mapTablename2DTOClass.put("KursFortschreibungsarten",Rev8DTOKursFortschreibungsart.class);
             mapTablename2DTOClass.put("Noten",Rev8DTONote.class);
             mapTablename2DTOClass.put("PersonalTypen",Rev8DTOPersonalTyp.class);
             mapTablename2DTOClass.put("SchuelerStatus",Rev8DTOSchuelerStatus.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Beratungslehrer",Rev8DTOGostJahrgangBeratungslehrer.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Fachkombinationen",Rev8DTOGostJahrgangFachkombinationen.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Faecher",Rev8DTOGostJahrgangFaecher.class);
             mapTablename2DTOClass.put("Gost_Jahrgangsdaten",Rev8DTOGostJahrgangsdaten.class);
             mapTablename2DTOClass.put("Gost_Schueler",Rev8DTOGostSchueler.class);
             mapTablename2DTOClass.put("Gost_Schueler_Fachwahlen",Rev8DTOGostSchuelerFachbelegungen.class);
             mapTablename2DTOClass.put("Gost_Blockung",Rev8DTOGostBlockung.class);
             mapTablename2DTOClass.put("Gost_Blockung_Kurse",Rev8DTOGostBlockungKurs.class);
             mapTablename2DTOClass.put("Gost_Blockung_Kurslehrer",Rev8DTOGostBlockungKurslehrer.class);
             mapTablename2DTOClass.put("Gost_Blockung_Regeln",Rev8DTOGostBlockungRegel.class);
             mapTablename2DTOClass.put("Gost_Blockung_Regelparameter",Rev8DTOGostBlockungRegelParameter.class);
             mapTablename2DTOClass.put("Gost_Blockung_Schienen",Rev8DTOGostBlockungSchiene.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse",Rev8DTOGostBlockungZwischenergebnis.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse_Kurs_Schienen",Rev8DTOGostBlockungZwischenergebnisKursSchiene.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse_Kurs_Schueler",Rev8DTOGostBlockungZwischenergebnisKursSchueler.class);
             mapTablename2DTOClass.put("SchildFilter",Rev8DTOSchildAuswahlFilter.class);
             mapTablename2DTOClass.put("Schild_Verwaltung",Rev8DTOSchildVerwaltung.class);
             mapTablename2DTOClass.put("SchuelerListe",Rev8DTOSchuelerIndividuelleGruppe.class);
             mapTablename2DTOClass.put("SchuelerListe_Inhalt",Rev8DTOSchuelerIndividuelleGruppeSchueler.class);
             mapTablename2DTOClass.put("SchuelerReportvorlagen",Rev8DTOSchuelerReportvorlagen.class);
             mapTablename2DTOClass.put("SchuelerWiedervorlage",Rev8DTOSchuelerWiedervorlage.class);
             mapTablename2DTOClass.put("TextExportVorlagen",Rev8DTOTextExportVorlagen.class);
             mapTablename2DTOClass.put("ZuordnungReportvorlagen",Rev8DTOZuordnungReportvorlagen.class);
             mapTablename2DTOClass.put("Benutzer",Rev8DTOBenutzer.class);
             mapTablename2DTOClass.put("BenutzerAllgemein",Rev8DTOBenutzerAllgemein.class);
             mapTablename2DTOClass.put("BenutzerKompetenzen",Rev8DTOBenutzerKompetenz.class);
             mapTablename2DTOClass.put("BenutzerEmail",Rev8DTOBenutzerMail.class);
             mapTablename2DTOClass.put("Benutzergruppen",Rev8DTOBenutzergruppe.class);
             mapTablename2DTOClass.put("BenutzergruppenKompetenzen",Rev8DTOBenutzergruppenKompetenz.class);
             mapTablename2DTOClass.put("BenutzergruppenMitglieder",Rev8DTOBenutzergruppenMitglied.class);
             mapTablename2DTOClass.put("Kompetenzen",Rev8DTOKatalogBenutzerKompetenz.class);
             mapTablename2DTOClass.put("Kompetenzgruppen",Rev8DTOKatalogBenutzerKompetenzGruppe.class);
             mapTablename2DTOClass.put("Logins",Rev8DTOProtokollLogin.class);
             mapTablename2DTOClass.put("K_BeschaeftigungsArt",Rev8DTOBeschaeftigungsart.class);
             mapTablename2DTOClass.put("Fach_Gliederungen",Rev8DTOFachgliederungen.class);
             mapTablename2DTOClass.put("EigeneSchule_Fachklassen",Rev8DTOFachklassen.class);
             mapTablename2DTOClass.put("K_Zertifikate",Rev8DTOKatalogZertifikate.class);
             mapTablename2DTOClass.put("SchuelerBKAbschluss",Rev8DTOSchuelerBKAbschluss.class);
             mapTablename2DTOClass.put("SchuelerBKFaecher",Rev8DTOSchuelerBKFach.class);
             mapTablename2DTOClass.put("SchuelerZuweisungen",Rev8DTOSchuelerZuweisung.class);
             mapTablename2DTOClass.put("EigeneSchule_Zertifikate",Rev8DTOZertifikate.class);
             mapTablename2DTOClass.put("ErzieherDatenschutz",Rev8DTOErzieherDatenschutz.class);
             mapTablename2DTOClass.put("ErzieherLernplattform",Rev8DTOErzieherLernplattform.class);
             mapTablename2DTOClass.put("K_ErzieherArt",Rev8DTOErzieherart.class);
             mapTablename2DTOClass.put("K_ErzieherFunktion",Rev8DTOErzieherfunktion.class);
             mapTablename2DTOClass.put("SchuelerErzAdr",Rev8DTOSchuelerErzieherAdresse.class);
             mapTablename2DTOClass.put("SchuelerTelefone",Rev8DTOSchuelerTelefon.class);
             mapTablename2DTOClass.put("K_TelefonArt",Rev8DTOTelefonArt.class);
             mapTablename2DTOClass.put("EigeneSchule_Faecher",Rev8DTOFach.class);
             mapTablename2DTOClass.put("EigeneSchule_FachTeilleistungen",Rev8DTOFachTeilleistungsarten.class);
             mapTablename2DTOClass.put("Fachgruppen",Rev8DTOFachgruppen.class);
             mapTablename2DTOClass.put("FachKatalog",Rev8DTOFaecherKatalog.class);
             mapTablename2DTOClass.put("FachKatalog_Keys",Rev8DTOFaecherKatalogKeys.class);
             mapTablename2DTOClass.put("FachKatalog_Schulformen",Rev8DTOFaecherKatalogSchulformen.class);
             mapTablename2DTOClass.put("NichtMoeglAbiFachKombi",Rev8DTOFaecherNichtMoeglicheKombination.class);
             mapTablename2DTOClass.put("K_Ankreuzdaten",Rev8DTOAnkreuzdaten.class);
             mapTablename2DTOClass.put("K_Ankreuzfloskeln",Rev8DTOAnkreuzfloskeln.class);
             mapTablename2DTOClass.put("K_Kindergarten",Rev8DTOKindergarten.class);
             mapTablename2DTOClass.put("SchuelerAnkreuzfloskeln",Rev8DTOSchuelerAnkreuzfloskeln.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte",Rev8DTOEigeneImporte.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte_Felder",Rev8DTOEigeneImporteFelder.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte_Tabellen",Rev8DTOEigeneImporteTabellen.class);
             mapTablename2DTOClass.put("Schildintern_AbiturInfos",Rev8DTOInternAbiturInfos.class);
             mapTablename2DTOClass.put("Schildintern_DQR_Niveaus",Rev8DTOInternDQRNiveaus.class);
             mapTablename2DTOClass.put("Schildintern_Datenart",Rev8DTOInternDatenart.class);
             mapTablename2DTOClass.put("Schildintern_FaecherSortierung",Rev8DTOInternFaecherSortierung.class);
             mapTablename2DTOClass.put("Schildintern_FilterFehlendeEintraege",Rev8DTOInternFilterFehlendeEintraege.class);
             mapTablename2DTOClass.put("Schildintern_FilterFehlendeEintraegeSchild3",Rev8DTOInternFilterFehlendeEintraegeSchild3.class);
             mapTablename2DTOClass.put("Schildintern_FilterFeldListe",Rev8DTOInternFilterFeldListe.class);
             mapTablename2DTOClass.put("Schildintern_Laender",Rev8DTOInternLaender.class);
             mapTablename2DTOClass.put("Schildintern_PrfSemAbschl",Rev8DTOInternPrfSemesterAbschluss.class);
             mapTablename2DTOClass.put("Schildintern_PruefungsOrdnung",Rev8DTOInternPruefungsOrdnung.class);
             mapTablename2DTOClass.put("Schildintern_PruefOrd_Optionen",Rev8DTOInternPruefungsOrdnungOptionen.class);
             mapTablename2DTOClass.put("Schildintern_SchuelerImpExp",Rev8DTOInternSchuelerImportExport.class);
             mapTablename2DTOClass.put("Schildintern_HSchStatus",Rev8DTOInternSchuelerStatus.class);
             mapTablename2DTOClass.put("Schildintern_SpezialFilterFelder",Rev8DTOInternSpezialFilterFelder.class);
             mapTablename2DTOClass.put("Schildintern_TextExport",Rev8DTOInternTextExport.class);
             mapTablename2DTOClass.put("Schildintern_UnicodeUmwandlung",Rev8DTOInternUnicodeUmwandllung.class);
             mapTablename2DTOClass.put("Schildintern_VerfImportFelder",Rev8DTOInternVerfImportFelder.class);
             mapTablename2DTOClass.put("Schildintern_VerfImportTabellen",Rev8DTOInternVerfImportTabellen.class);
             mapTablename2DTOClass.put("Schildintern_Zusatzinfos",Rev8DTOInternZusatzinfos.class);
             mapTablename2DTOClass.put("Schildintern_KAoA_Anschlussoption",Rev8DTOKAoAAnschlussoption.class);
             mapTablename2DTOClass.put("Schildintern_KAoA_Berufsfeld",Rev8DTOKAoABerufsfeld.class);
             mapTablename2DTOClass.put("Schildintern_KAoA_Kategorie",Rev8DTOKAoAKategorie.class);
             mapTablename2DTOClass.put("Schildintern_KAoA_Merkmal",Rev8DTOKAoAMerkmal.class);
             mapTablename2DTOClass.put("Schildintern_KAoA_SBO_Ebene4",Rev8DTOKAoASBOEB4.class);
             mapTablename2DTOClass.put("Schildintern_KAoA_Zusatzmerkmal",Rev8DTOKAoAZusatzmerkmal.class);
             mapTablename2DTOClass.put("AllgAdrAnsprechpartner",Rev8DTOAnsprechpartnerAllgemeineAdresse.class);
             mapTablename2DTOClass.put("K_FahrschuelerArt",Rev8DTOFahrschuelerart.class);
             mapTablename2DTOClass.put("Floskelgruppen",Rev8DTOFloskelgruppen.class);
             mapTablename2DTOClass.put("Floskeln",Rev8DTOFloskeln.class);
             mapTablename2DTOClass.put("K_Haltestelle",Rev8DTOHaltestellen.class);
             mapTablename2DTOClass.put("K_Adressart",Rev8DTOKatalogAdressart.class);
             mapTablename2DTOClass.put("K_AllgAdresse",Rev8DTOKatalogAllgemeineAdresse.class);
             mapTablename2DTOClass.put("Katalog_Aufsichtsbereich",Rev8DTOKatalogAufsichtsbereich.class);
             mapTablename2DTOClass.put("K_Datenschutz",Rev8DTOKatalogDatenschutz.class);
             mapTablename2DTOClass.put("Katalog_Raeume",Rev8DTOKatalogRaum.class);
             mapTablename2DTOClass.put("K_Religion",Rev8DTOKonfession.class);
             mapTablename2DTOClass.put("EigeneSchule_Kursart",Rev8DTOKursarten.class);
             mapTablename2DTOClass.put("K_Ort",Rev8DTOOrt.class);
             mapTablename2DTOClass.put("K_Ortsteil",Rev8DTOOrtsteil.class);
             mapTablename2DTOClass.put("K_Schule",Rev8DTOSchuleNRW.class);
             mapTablename2DTOClass.put("K_Schulfunktionen",Rev8DTOSchulfunktion.class);
             mapTablename2DTOClass.put("K_Schwerpunkt",Rev8DTOSchwerpunkt.class);
             mapTablename2DTOClass.put("K_Textdateien",Rev8DTOTextDateien.class);
             mapTablename2DTOClass.put("K_Vermerkart",Rev8DTOVermerkArt.class);
             mapTablename2DTOClass.put("Klassen",Rev8DTOKlassen.class);
             mapTablename2DTOClass.put("KlassenLehrer",Rev8DTOKlassenLeitung.class);
             mapTablename2DTOClass.put("KlassenartenKatalog",Rev8DTOKlassenartenKatalog.class);
             mapTablename2DTOClass.put("KlassenartenKatalog_Keys",Rev8DTOKlassenartenKatalogKeys.class);
             mapTablename2DTOClass.put("KlassenartenKatalog_Schulformen",Rev8DTOKlassenartenKatalogSchulformen.class);
             mapTablename2DTOClass.put("Kurse",Rev8DTOKurs.class);
             mapTablename2DTOClass.put("KursLehrer",Rev8DTOKursLehrer.class);
             mapTablename2DTOClass.put("Kurs_Schueler",Rev8DTOKursSchueler.class);
             mapTablename2DTOClass.put("KursartenKatalog",Rev8DTOKursartenKatalog.class);
             mapTablename2DTOClass.put("KursartenKatalog_Keys",Rev8DTOKursartenKatalogKeys.class);
             mapTablename2DTOClass.put("KursartenKatalog_Schulformen",Rev8DTOKursartenKatalogSchulformen.class);
             mapTablename2DTOClass.put("K_Lehrer",Rev8DTOLehrer.class);
             mapTablename2DTOClass.put("LehrerAbschnittsdaten",Rev8DTOLehrerAbschnittsdaten.class);
             mapTablename2DTOClass.put("LehrerAnrechnung",Rev8DTOLehrerAnrechnungsstunde.class);
             mapTablename2DTOClass.put("LehrerDatenschutz",Rev8DTOLehrerDatenschutz.class);
             mapTablename2DTOClass.put("LehrerEntlastung",Rev8DTOLehrerEntlastungsstunde.class);
             mapTablename2DTOClass.put("LehrerFotos",Rev8DTOLehrerFoto.class);
             mapTablename2DTOClass.put("LehrerFunktionen",Rev8DTOLehrerFunktion.class);
             mapTablename2DTOClass.put("LehrerLehramt",Rev8DTOLehrerLehramt.class);
             mapTablename2DTOClass.put("LehrerLehramtLehrbef",Rev8DTOLehrerLehramtBefaehigung.class);
             mapTablename2DTOClass.put("LehrerLehramtFachr",Rev8DTOLehrerLehramtFachrichtung.class);
             mapTablename2DTOClass.put("LehrerLernplattform",Rev8DTOLehrerLernplattform.class);
             mapTablename2DTOClass.put("LehrerMehrleistung",Rev8DTOLehrerMehrleistung.class);
             mapTablename2DTOClass.put("Schulleitung",Rev8DTOSchulleitung.class);
             mapTablename2DTOClass.put("SchulleitungFunktion",Rev8DTOSchulleitungFunktion.class);
             mapTablename2DTOClass.put("Personengruppen",Rev8DTOPersonengruppen.class);
             mapTablename2DTOClass.put("Personengruppen_Personen",Rev8DTOPersonengruppenPersonen.class);
             mapTablename2DTOClass.put("K_EinschulungsArt",Rev8DTOEinschulungsart.class);
             mapTablename2DTOClass.put("K_EntlassGrund",Rev8DTOEntlassarten.class);
             mapTablename2DTOClass.put("K_Foerderschwerpunkt",Rev8DTOFoerderschwerpunkt.class);
             mapTablename2DTOClass.put("Schueler",Rev8DTOSchueler.class);
             mapTablename2DTOClass.put("SchuelerAbgaenge",Rev8DTOSchuelerAbgaenge.class);
             mapTablename2DTOClass.put("Schueler_AllgAdr",Rev8DTOSchuelerAllgemeineAdresse.class);
             mapTablename2DTOClass.put("SchuelerDatenschutz",Rev8DTOSchuelerDatenschutz.class);
             mapTablename2DTOClass.put("SchuelerFehlstunden",Rev8DTOSchuelerFehlstunden.class);
             mapTablename2DTOClass.put("SchuelerFoerderempfehlungen",Rev8DTOSchuelerFoerderempfehlung.class);
             mapTablename2DTOClass.put("SchuelerFotos",Rev8DTOSchuelerFoto.class);
             mapTablename2DTOClass.put("SchuelerGSDaten",Rev8DTOSchuelerGrundschuldaten.class);
             mapTablename2DTOClass.put("SchuelerKAoADaten",Rev8DTOSchuelerKAoADaten.class);
             mapTablename2DTOClass.put("SchuelerLeistungsdaten",Rev8DTOSchuelerLeistungsdaten.class);
             mapTablename2DTOClass.put("SchuelerLernabschnittsdaten",Rev8DTOSchuelerLernabschnittsdaten.class);
             mapTablename2DTOClass.put("SchuelerLernplattform",Rev8DTOSchuelerLernplattform.class);
             mapTablename2DTOClass.put("SchuelerMerkmale",Rev8DTOSchuelerMerkmale.class);
             mapTablename2DTOClass.put("SchuelerLD_PSFachBem",Rev8DTOSchuelerPSFachBemerkungen.class);
             mapTablename2DTOClass.put("SchuelerSprachenfolge",Rev8DTOSchuelerSprachenfolge.class);
             mapTablename2DTOClass.put("SchuelerSprachpruefungen",Rev8DTOSchuelerSprachpruefungen.class);
             mapTablename2DTOClass.put("SchuelerEinzelleistungen",Rev8DTOSchuelerTeilleistung.class);
             mapTablename2DTOClass.put("SchuelerVermerke",Rev8DTOSchuelerVermerke.class);
             mapTablename2DTOClass.put("SchuelerZP10",Rev8DTOSchuelerZP10.class);
             mapTablename2DTOClass.put("K_Sportbefreiung",Rev8DTOSportbefreiung.class);
             mapTablename2DTOClass.put("K_Einzelleistungen",Rev8DTOTeilleistungsarten.class);
             mapTablename2DTOClass.put("SchuelerAbitur",Rev8DTOSchuelerAbitur.class);
             mapTablename2DTOClass.put("SchuelerAbiFaecher",Rev8DTOSchuelerAbiturFach.class);
             mapTablename2DTOClass.put("SchuelerFHR",Rev8DTOSchuelerFHR.class);
             mapTablename2DTOClass.put("SchuelerFHRFaecher",Rev8DTOSchuelerFHRFach.class);
             mapTablename2DTOClass.put("EigeneSchule_Abteilungen",Rev8DTOAbteilungen.class);
             mapTablename2DTOClass.put("EigeneSchule_Abt_Kl",Rev8DTOAbteilungsKlassen.class);
             mapTablename2DTOClass.put("Foerderschwerpunkte",Rev8DTOAlleFoerderschwerpunkte.class);
             mapTablename2DTOClass.put("Foerderschwerpunkte_Schulformen",Rev8DTOAlleFoerderschwerpunkteSchulformen.class);
             mapTablename2DTOClass.put("Jahrgaenge",Rev8DTOAlleJahrgaenge.class);
             mapTablename2DTOClass.put("Jahrgaenge_Bezeichnungen",Rev8DTOAlleJahrgaengeBezeichnungen.class);
             mapTablename2DTOClass.put("Jahrgaenge_Keys",Rev8DTOAlleJahrgaengeKeys.class);
             mapTablename2DTOClass.put("Schulformen",Rev8DTOAlleSchulformen.class);
             mapTablename2DTOClass.put("Schulgliederungen",Rev8DTOAlleSchulgliederungen.class);
             mapTablename2DTOClass.put("Schulgliederungen_Abschluesse_Allgemeinbildend",Rev8DTOAlleSchulgliederungenAbschluesseAllgmeinbildend.class);
             mapTablename2DTOClass.put("Schulgliederungen_Abschluesse_Berufsbildend",Rev8DTOAlleSchulgliederungenAbschluesseBerufsbildend.class);
             mapTablename2DTOClass.put("Schulgliederungen_Schulformen",Rev8DTOAlleSchulgliederungenSchulformen.class);
             mapTablename2DTOClass.put("AllgemeineMerkmaleKatalog",Rev8DTOAllgemeineMerkmaleKatalog.class);
             mapTablename2DTOClass.put("AllgemeineMerkmaleKatalog_Keys",Rev8DTOAllgemeineMerkmaleKatalogKeys.class);
             mapTablename2DTOClass.put("AllgemeineMerkmaleKatalog_Schulformen",Rev8DTOAllgemeineMerkmaleKatalogSchulformen.class);
             mapTablename2DTOClass.put("Berufskolleg_Anlagen",Rev8DTOBerufskollegAnlagen.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen1",Rev8DTOBerufskollegBerufsebenen1.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen2",Rev8DTOBerufskollegBerufsebenen2.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen3",Rev8DTOBerufskollegBerufsebenen3.class);
             mapTablename2DTOClass.put("Berufskolleg_Fachklassen",Rev8DTOBerufskollegFachklassen.class);
             mapTablename2DTOClass.put("Berufskolleg_Fachklassen_Keys",Rev8DTOBerufskollegFachklassenKeys.class);
             mapTablename2DTOClass.put("EigeneSchule",Rev8DTOEigeneSchule.class);
             mapTablename2DTOClass.put("EigeneSchule_KAoADaten",Rev8DTOEigeneSchuleKAoADaten.class);
             mapTablename2DTOClass.put("EinschulungsartKatalog",Rev8DTOEinschulungsartenKatalog.class);
             mapTablename2DTOClass.put("EinschulungsartKatalog_Keys",Rev8DTOEinschulungsartenKatalogKeys.class);
             mapTablename2DTOClass.put("Herkunft",Rev8DTOHerkunft.class);
             mapTablename2DTOClass.put("Herkunft_Schulformen",Rev8DTOHerkunftSchulformen.class);
             mapTablename2DTOClass.put("Herkunftsart",Rev8DTOHerkunftsart.class);
             mapTablename2DTOClass.put("Herkunftsart_Schulformen",Rev8DTOHerkunftsartSchulformen.class);
             mapTablename2DTOClass.put("EigeneSchule_Jahrgaenge",Rev8DTOJahrgang.class);
             mapTablename2DTOClass.put("EigeneSchule_Merkmale",Rev8DTOMerkmale.class);
             mapTablename2DTOClass.put("OrganisationsformenKatalog",Rev8DTOOrganisationsformenKatalog.class);
             mapTablename2DTOClass.put("OrganisationsformenKatalog_Keys",Rev8DTOOrganisationsformenKatalogKeys.class);
             mapTablename2DTOClass.put("OrganisationsformenKatalog_Schulformen",Rev8DTOOrganisationsformenKatalogSchulformen.class);
             mapTablename2DTOClass.put("Schulabschluesse_Allgemeinbildend",Rev8DTOSchulabschluesse_Allgemeinbildend.class);
             mapTablename2DTOClass.put("Schulabschluesse_Berufsbildend",Rev8DTOSchulabschluesse_Berufsbildend.class);
             mapTablename2DTOClass.put("EigeneSchule_Schulformen",Rev8DTOSchulformen.class);
             mapTablename2DTOClass.put("Schuljahresabschnitte",Rev8DTOSchuljahresabschnitte.class);
             mapTablename2DTOClass.put("EigeneSchule_Texte",Rev8DTOSchultexte.class);
             mapTablename2DTOClass.put("Stundentafel",Rev8DTOStundentafel.class);
             mapTablename2DTOClass.put("Stundentafel_Faecher",Rev8DTOStundentafelFaecher.class);
             mapTablename2DTOClass.put("EigeneSchule_Teilstandorte",Rev8DTOTeilstandorte.class);
             mapTablename2DTOClass.put("Katalog_Pausenzeiten",Rev8DTOKatalogPausenzeit.class);
             mapTablename2DTOClass.put("Katalog_Zeitraster",Rev8DTOKatalogZeitraster.class);
             mapTablename2DTOClass.put("Stundenplan",Rev8DTOStundenplan.class);
             mapTablename2DTOClass.put("Stundenplan_Aufsichtsbereiche",Rev8DTOStundenplanAufsichtsbereich.class);
             mapTablename2DTOClass.put("Stundenplan_Pausenaufsichten",Rev8DTOStundenplanPausenaufsichten.class);
             mapTablename2DTOClass.put("Stundenplan_PausenaufsichtenBereich",Rev8DTOStundenplanPausenaufsichtenBereiche.class);
             mapTablename2DTOClass.put("Stundenplan_Pausenzeit",Rev8DTOStundenplanPausenzeit.class);
             mapTablename2DTOClass.put("Stundenplan_Raeume",Rev8DTOStundenplanRaum.class);
             mapTablename2DTOClass.put("Stundenplan_Unterricht",Rev8DTOStundenplanUnterricht.class);
             mapTablename2DTOClass.put("Stundenplan_UnterrichtLehrer",Rev8DTOStundenplanUnterrichtLehrer.class);
             mapTablename2DTOClass.put("Stundenplan_UnterrichtRaum",Rev8DTOStundenplanUnterrichtRaum.class);
             mapTablename2DTOClass.put("Stundenplan_Zeitraster",Rev8DTOStundenplanZeitraster.class);
             mapTablename2DTOClass.put("Herkunft_Keys",Rev8DTOHerkunftKeys.class);
             mapTablename2DTOClass.put("Herkunftsart_Keys",Rev8DTOHerkunftsartKeys.class);
             mapTablename2DTOClass.put("Nationalitaeten",Rev8DTONationalitaeten.class);
             mapTablename2DTOClass.put("Nationalitaeten_Keys",Rev8DTONationalitaetenKeys.class);
             mapTablename2DTOClass.put("Religionen",Rev8DTOReligion.class);
             mapTablename2DTOClass.put("Religionen_Keys",Rev8DTOReligionKeys.class);
             mapTablename2DTOClass.put("Verkehrssprachen",Rev8DTOVerkehrssprachen.class);
             mapTablename2DTOClass.put("Schulver_DBS",Rev8DTOSchulverDBS.class);
             mapTablename2DTOClass.put("Schulver_Schultraeger",Rev8DTOSchulverSchultraeger.class);
             mapTablename2DTOClass.put("Schulver_WeitereSF",Rev8DTOSchulverWeitereSF.class);
             mapTablename2DTOClass.put("Statkue_SVWS_SprachpruefungNiveaus",Rev8DTOSVWSSprachpruefungNiveaus.class);
             mapTablename2DTOClass.put("Statkue_Abgangsart",Rev8DTOStatkueAbgangsart.class);
             mapTablename2DTOClass.put("Statkue_AndereGrundschulen",Rev8DTOStatkueAndereGrundschulen.class);
             mapTablename2DTOClass.put("Statkue_Bilingual",Rev8DTOStatkueBilingual.class);
             mapTablename2DTOClass.put("Statkue_LehrerAbgang",Rev8DTOStatkueLehrerAbgang.class);
             mapTablename2DTOClass.put("Statkue_LehrerAnrechnung",Rev8DTOStatkueLehrerAnrechnung.class);
             mapTablename2DTOClass.put("Statkue_LehrerBeschaeftigungsart",Rev8DTOStatkueLehrerBeschaeftigungsart.class);
             mapTablename2DTOClass.put("Statkue_LehrerEinsatzstatus",Rev8DTOStatkueLehrerEinsatzstatus.class);
             mapTablename2DTOClass.put("Statkue_LehrerFachrichtung",Rev8DTOStatkueLehrerFachrichtung.class);
             mapTablename2DTOClass.put("Statkue_LehrerFachrAnerkennung",Rev8DTOStatkueLehrerFachrichtungAnerkennung.class);
             mapTablename2DTOClass.put("Statkue_LehrerLehramt",Rev8DTOStatkueLehrerLehramt.class);
             mapTablename2DTOClass.put("Statkue_LehrerLehramtAnerkennung",Rev8DTOStatkueLehrerLehramtAnerkennung.class);
             mapTablename2DTOClass.put("Statkue_LehrerLehrbefaehigung",Rev8DTOStatkueLehrerLehrbefaehigung.class);
             mapTablename2DTOClass.put("Statkue_LehrerLehrbefAnerkennung",Rev8DTOStatkueLehrerLehrbefaehigungAnerkennung.class);
             mapTablename2DTOClass.put("Statkue_LehrerMehrleistung",Rev8DTOStatkueLehrerMehrleistung.class);
             mapTablename2DTOClass.put("Statkue_LehrerMinderleistung",Rev8DTOStatkueLehrerMinderleistung.class);
             mapTablename2DTOClass.put("Statkue_LehrerRechtsverhaeltnis",Rev8DTOStatkueLehrerRechtsverhaeltnis.class);
             mapTablename2DTOClass.put("Statkue_LehrerZugang",Rev8DTOStatkueLehrerZugang.class);
             mapTablename2DTOClass.put("Statkue_PLZOrt",Rev8DTOStatkuePLZOrt.class);
             mapTablename2DTOClass.put("Statkue_Reformpaedagogik",Rev8DTOStatkueReformpaedagogik.class);
             mapTablename2DTOClass.put("Statkue_SchuelerErsteSchulformSekI",Rev8DTOStatkueSchuelerErsteSchulformSekI.class);
             mapTablename2DTOClass.put("Statkue_SchuelerKindergartenbesuch",Rev8DTOStatkueSchuelerKindergartenbesuch.class);
             mapTablename2DTOClass.put("Statkue_SchuelerUebergangsempfehlung5Jg",Rev8DTOStatkueSchuelerUebergangsempfehlung5Jg.class);
             mapTablename2DTOClass.put("Credentials",Rev8DTOCredentials.class);
             mapTablename2DTOClass.put("CredentialsLernplattformen",Rev8DTOCredentialsLernplattformen.class);
             mapTablename2DTOClass.put("Lernplattformen",Rev8DTOLernplattformen.class);
             mapTablename2DTOClass.put("SchuleCredentials",Rev8DTOSchuleCredentials.class);
             mapTablename2DTOClass.put("SVWS_Client_Konfiguration_Benutzer",Rev8DTOClientKonfigurationBenutzer.class);
             mapTablename2DTOClass.put("SVWS_Client_Konfiguration_Global",Rev8DTOClientKonfigurationGlobal.class);
             mapTablename2DTOClass.put("DavRessources",Rev8DTODavRessource.class);
             mapTablename2DTOClass.put("DavRessourceCollections",Rev8DTODavRessourceCollection.class);
             mapTablename2DTOClass.put("DavRessourceCollectionsACL",Rev8DTODavRessourceCollectionsACL.class);
             mapTablename2DTOClass.put("DavSyncTokenLehrer",Rev8DTODavSyncTokenLehrer.class);
             mapTablename2DTOClass.put("DavSyncTokenSchueler",Rev8DTODavSyncTokenSchueler.class);
             mapTablename2DTOClass.put("SVWS_Core_Type_Versionen",Rev8DTOCoreTypeVersion.class);
             mapTablename2DTOClass.put("SVWS_DB_AutoInkremente",Rev8DTODBAutoInkremente.class);
             mapTablename2DTOClass.put("SVWS_DB_Version",Rev8DTODBVersion.class);
             mapTablename2DTOClass.put("Schildintern_Berufsebene",Rev8DTOSchildInternBerufsebenen.class);
             mapTablename2DTOClass.put("Schildintern_Fachgruppen",Rev8DTOSchildInternFachgruppen.class);
             mapTablename2DTOClass.put("Schildintern_K_Schulnote",Rev8DTOSchildInternNote.class);
             mapTablename2DTOClass.put("Schulver_Schulformen",Rev8DTOSchulverSchulformen.class);
             mapTablename2DTOClass.put("Statkue_Fachklasse",Rev8DTOStatkueFachklasse.class);
             mapTablename2DTOClass.put("Statkue_Foerderschwerpunkt",Rev8DTOStatkueFoerderschwerpunkte.class);
             mapTablename2DTOClass.put("Statkue_Schulformen",Rev8DTOStatkueSchulformen.class);
             mapTablename2DTOClass.put("Statkue_Gliederung",Rev8DTOStatkueGliederung.class);
             mapTablename2DTOClass.put("Statkue_Herkunftsschulform",Rev8DTOStatkueHerkunftsschulform.class);
             mapTablename2DTOClass.put("Statkue_Herkunftsart",Rev8DTOStatkueHerkunftsart.class);
             mapTablename2DTOClass.put("Statkue_SVWS_Schulgliederungen",Rev8DTOSVWSSchulgliederungen.class);
             mapTablename2DTOClass.put("Statkue_Nationalitaeten",Rev8DTOStatkueNationalitaeten.class);
             mapTablename2DTOClass.put("Statkue_SchuelerVerkehrssprache",Rev8DTOStatkueSchuelerVerkehrssprache.class);
             mapTablename2DTOClass.put("Statkue_ZulJahrgaenge",Rev8DTOStatkueZulaessigerJahrgang.class);
             mapTablename2DTOClass.put("Statkue_ZulKlArt",Rev8DTOStatkueZulaessigeKlassenart.class);
             mapTablename2DTOClass.put("Statkue_ZulKuArt",Rev8DTOStatkueZulaessigeKursart.class);
             mapTablename2DTOClass.put("Statkue_ZulFaecher",Rev8DTOStatkueZulaessigesFach.class);
             mapTablename2DTOClass.put("Statkue_SVWS_ZulaessigeFaecher",Rev8DTOSVWSZulaessigeFaecherMapping.class);
             mapTablename2DTOClass.put("Statkue_Einschulungsart",Rev8DTOStatkueEinschulungsart.class);
             mapTablename2DTOClass.put("Statkue_AllgMerkmale",Rev8DTOStatkueAllgMerkmale.class);
             mapTablename2DTOClass.put("Statkue_Religionen",Rev8DTOStatkueReligion.class);
             mapTablename2DTOClass.put("Statkue_Organisationsform",Rev8DTOStatkueOrganisationsform.class);
             mapTablename2DTOClass.put("V_Benutzer",Rev8DTOViewBenutzer.class);
             mapTablename2DTOClass.put("V_Benutzerkompetenzen",Rev8DTOViewBenutzerKompetenz.class);
             mapTablename2DTOClass.put("V_BenutzerDetails",Rev8DTOViewBenutzerdetails.class);
             mapTablename2DTOClass.put("V_Gost_Schueler_Abiturjahrgang",Rev8DTOViewGostSchuelerAbiturjahrgang.class);
         }
         return mapTablename2DTOClass;
     }


    /**
     * Gibt die DTO-Klasse mit dem angegebenen Tabellennamen zurück.
     *
     * @param name   der Tabellenname
     *
     * @return die DTO-Klasse
     */
    public static Class<? extends Object> getFromTableName(String name) {
    	return getMapTablename2DTOClass().get(name);
    }

}
