package de.nrw.schule.svws.db.dto;

import java.util.HashMap;

import de.nrw.schule.svws.db.dto.rev9.coretypes.Rev9DTOKursFortschreibungsart;
import de.nrw.schule.svws.db.dto.rev9.coretypes.Rev9DTONote;
import de.nrw.schule.svws.db.dto.rev9.coretypes.Rev9DTOPersonalTyp;
import de.nrw.schule.svws.db.dto.rev9.gost.Rev9DTOGostJahrgangBeratungslehrer;
import de.nrw.schule.svws.db.dto.rev9.gost.Rev9DTOGostJahrgangFachkombinationen;
import de.nrw.schule.svws.db.dto.rev9.gost.Rev9DTOGostJahrgangFaecher;
import de.nrw.schule.svws.db.dto.rev9.gost.Rev9DTOGostJahrgangsdaten;
import de.nrw.schule.svws.db.dto.rev9.gost.Rev9DTOGostSchueler;
import de.nrw.schule.svws.db.dto.rev9.gost.Rev9DTOGostSchuelerFachbelegungen;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenKalenderinformationen;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenKursklausuren;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenNtaZeiten;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenRaeume;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenRaeumeStunden;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenRaeumeStundenAufsichten;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenSchuelerklausuren;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenSchuelerklausurenRaeumeStunden;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenTermine;
import de.nrw.schule.svws.db.dto.rev9.gost.klausurplanung.Rev9DTOGostKlausurenVorgaben;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockung;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungKurs;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungKurslehrer;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungRegel;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungRegelParameter;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungSchiene;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungZwischenergebnis;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungZwischenergebnisKursSchiene;
import de.nrw.schule.svws.db.dto.rev9.gost.kursblockung.Rev9DTOGostBlockungZwischenergebnisKursSchueler;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOSchildAuswahlFilter;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOSchildVerwaltung;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOSchuelerIndividuelleGruppe;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOSchuelerIndividuelleGruppeSchueler;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOSchuelerReportvorlagen;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOSchuelerWiedervorlage;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOTextExportVorlagen;
import de.nrw.schule.svws.db.dto.rev9.schild.Rev9DTOZuordnungReportvorlagen;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzer;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzerAllgemein;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzerMail;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzergruppe;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzergruppenKompetenz;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOBenutzergruppenMitglied;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOKatalogBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOKatalogBenutzerKompetenzGruppe;
import de.nrw.schule.svws.db.dto.rev9.schild.benutzer.Rev9DTOProtokollLogin;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOBeschaeftigungsart;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOFachgliederungen;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOFachklassen;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOKatalogZertifikate;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOSchuelerBKAbschluss;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOSchuelerBKFach;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOSchuelerZuweisung;
import de.nrw.schule.svws.db.dto.rev9.schild.berufskolleg.Rev9DTOZertifikate;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOErzieherDatenschutz;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOErzieherLernplattform;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOErzieherart;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOErzieherfunktion;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOSchuelerErzieherAdresse;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOSchuelerTelefon;
import de.nrw.schule.svws.db.dto.rev9.schild.erzieher.Rev9DTOTelefonArt;
import de.nrw.schule.svws.db.dto.rev9.schild.faecher.Rev9DTOFach;
import de.nrw.schule.svws.db.dto.rev9.schild.faecher.Rev9DTOFachTeilleistungsarten;
import de.nrw.schule.svws.db.dto.rev9.schild.faecher.Rev9DTOFachgruppen;
import de.nrw.schule.svws.db.dto.rev9.schild.faecher.Rev9DTOFaecherKatalog;
import de.nrw.schule.svws.db.dto.rev9.schild.faecher.Rev9DTOFaecherKatalogKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.faecher.Rev9DTOFaecherKatalogSchulformen;
import de.nrw.schule.svws.db.dto.rev9.schild.gost.Rev9DTOFaecherNichtMoeglicheKombination;
import de.nrw.schule.svws.db.dto.rev9.schild.grundschule.Rev9DTOAnkreuzdaten;
import de.nrw.schule.svws.db.dto.rev9.schild.grundschule.Rev9DTOAnkreuzfloskeln;
import de.nrw.schule.svws.db.dto.rev9.schild.grundschule.Rev9DTOKindergarten;
import de.nrw.schule.svws.db.dto.rev9.schild.grundschule.Rev9DTOSchuelerAnkreuzfloskeln;
import de.nrw.schule.svws.db.dto.rev9.schild.impexp.Rev9DTOEigeneImporte;
import de.nrw.schule.svws.db.dto.rev9.schild.impexp.Rev9DTOEigeneImporteFelder;
import de.nrw.schule.svws.db.dto.rev9.schild.impexp.Rev9DTOEigeneImporteTabellen;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOAnsprechpartnerAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOFahrschuelerart;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOFloskelgruppen;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOFloskeln;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOHaltestellen;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKatalogAdressart;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKatalogAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKatalogAufsichtsbereich;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKatalogDatenschutz;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKatalogRaum;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKonfession;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOKursarten;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOOrt;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOOrtsteil;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOSchuleNRW;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOSchulfunktion;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOSchwerpunkt;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOTextDateien;
import de.nrw.schule.svws.db.dto.rev9.schild.katalog.Rev9DTOVermerkArt;
import de.nrw.schule.svws.db.dto.rev9.schild.klassen.Rev9DTOKlassen;
import de.nrw.schule.svws.db.dto.rev9.schild.klassen.Rev9DTOKlassenLeitung;
import de.nrw.schule.svws.db.dto.rev9.schild.klassen.Rev9DTOKlassenartenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.kurse.Rev9DTOKurs;
import de.nrw.schule.svws.db.dto.rev9.schild.kurse.Rev9DTOKursLehrer;
import de.nrw.schule.svws.db.dto.rev9.schild.kurse.Rev9DTOKursSchueler;
import de.nrw.schule.svws.db.dto.rev9.schild.kurse.Rev9DTOKursartenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrer;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerAbschnittsdaten;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerAnrechnungsstunde;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerDatenschutz;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerEntlastungsstunde;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerFoto;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerFunktion;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerLehramt;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerLehramtBefaehigung;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerLehramtFachrichtung;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerLeitungsfunktionKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerLernplattform;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOLehrerMehrleistung;
import de.nrw.schule.svws.db.dto.rev9.schild.lehrer.Rev9DTOSchulleitung;
import de.nrw.schule.svws.db.dto.rev9.schild.personengruppen.Rev9DTOPersonengruppen;
import de.nrw.schule.svws.db.dto.rev9.schild.personengruppen.Rev9DTOPersonengruppenPersonen;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOEinschulungsart;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOEntlassarten;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOFoerderschwerpunkt;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchueler;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerAbgaenge;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerAllgemeineAdresse;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerDatenschutz;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerFehlstunden;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerFoerderempfehlung;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerFoto;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerGrundschuldaten;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerKAoADaten;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerLeistungsdaten;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerLernabschnittsdaten;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerLernplattform;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerMerkmale;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerPSFachBemerkungen;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerSprachenfolge;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerSprachpruefungen;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerTeilleistung;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerVermerke;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSchuelerZP10;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOSportbefreiung;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.Rev9DTOTeilleistungsarten;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.abitur.Rev9DTOSchuelerAbitur;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.abitur.Rev9DTOSchuelerAbiturFach;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.fhr.Rev9DTOSchuelerFHR;
import de.nrw.schule.svws.db.dto.rev9.schild.schueler.fhr.Rev9DTOSchuelerFHRFach;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOAbteilungen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOAbteilungsKlassen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOAlleJahrgaengeKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOAlleSchulformen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOAllgemeineMerkmaleKatalogKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOBerufskollegAnlagen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOBerufskollegBerufsebenen1;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOBerufskollegBerufsebenen2;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOBerufskollegBerufsebenen3;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOBerufskollegFachklassenKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOEigeneSchule;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOEigeneSchuleKAoADaten;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOEinschulungsartenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOHerkunft;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOHerkunftSchulformen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOHerkunftsart;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOHerkunftsartSchulformen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOJahrgang;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOMerkmale;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOOrganisationsformenKatalogKeys;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOSchulformen;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOSchuljahresabschnitte;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOSchultexte;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOStundentafel;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOStundentafelFaecher;
import de.nrw.schule.svws.db.dto.rev9.schild.schule.Rev9DTOTeilstandorte;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOKatalogPausenzeit;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOKatalogZeitraster;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplan;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanAufsichtsbereich;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanPausenaufsichten;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanPausenaufsichtenBereiche;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanPausenzeit;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanRaum;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanUnterricht;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanUnterrichtLehrer;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanUnterrichtRaum;
import de.nrw.schule.svws.db.dto.rev9.schild.stundenplan.Rev9DTOStundenplanZeitraster;
import de.nrw.schule.svws.db.dto.rev9.schueler.Rev9DTOSchuelerStatus;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOHerkunftKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOHerkunftsartKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOKAoAAnschlussoptionKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOKAoABerufsfeldKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOKAoAKategorieKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOKAoAMerkmalKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOKAoASBOEB4Keys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOKAoAZusatzmerkmalKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTONationalitaetenKeys;
import de.nrw.schule.svws.db.dto.rev9.schule.Rev9DTOReligionKeys;
import de.nrw.schule.svws.db.dto.rev9.svws.auth.Rev9DTOCredentials;
import de.nrw.schule.svws.db.dto.rev9.svws.auth.Rev9DTOCredentialsLernplattformen;
import de.nrw.schule.svws.db.dto.rev9.svws.auth.Rev9DTOLernplattformen;
import de.nrw.schule.svws.db.dto.rev9.svws.auth.Rev9DTOSchuleCredentials;
import de.nrw.schule.svws.db.dto.rev9.svws.client.Rev9DTOClientKonfigurationBenutzer;
import de.nrw.schule.svws.db.dto.rev9.svws.client.Rev9DTOClientKonfigurationGlobal;
import de.nrw.schule.svws.db.dto.rev9.svws.dav.Rev9DTODavRessource;
import de.nrw.schule.svws.db.dto.rev9.svws.dav.Rev9DTODavRessourceCollection;
import de.nrw.schule.svws.db.dto.rev9.svws.dav.Rev9DTODavRessourceCollectionsACL;
import de.nrw.schule.svws.db.dto.rev9.svws.dav.Rev9DTODavSyncTokenLehrer;
import de.nrw.schule.svws.db.dto.rev9.svws.dav.Rev9DTODavSyncTokenSchueler;
import de.nrw.schule.svws.db.dto.rev9.svws.db.Rev9DTOCoreTypeVersion;
import de.nrw.schule.svws.db.dto.rev9.svws.db.Rev9DTODBAutoInkremente;
import de.nrw.schule.svws.db.dto.rev9.svws.db.Rev9DTODBVersion;
import de.nrw.schule.svws.db.dto.rev9.svws.enm.Rev9DTOEnmLeistungsdaten;
import de.nrw.schule.svws.db.dto.rev9.svws.enm.Rev9DTOEnmLernabschnittsdaten;
import de.nrw.schule.svws.db.dto.rev9.views.benutzer.Rev9DTOViewBenutzer;
import de.nrw.schule.svws.db.dto.rev9.views.benutzer.Rev9DTOViewBenutzerKompetenz;
import de.nrw.schule.svws.db.dto.rev9.views.benutzer.Rev9DTOViewBenutzerdetails;
import de.nrw.schule.svws.db.dto.rev9.views.gost.Rev9DTOViewGostSchuelerAbiturjahrgang;

/**
 * Diese Klasse dient als Verzeichnis aller Datenbank-DTO-Klassen.
 * Sie wurde automatisch per Skript generiert und sollte nicht verändert werden,
 * da sie aufgrund von Änderungen am DB-Schema ggf. neu generiert und überschrieben wird.
 */
public class Rev9DTOs {

    /** Enthält das Mapping der Namen aller Java-DTO-Klassen für die SVWS-DB zu den entsprechenden Java-DTO-Klassen. */
    private static HashMap<String, Class<? extends Object>> mapDTOName2DTOClass = null;

    /** Enthält das Mapping der Datenbank-Tabellennamen zu den zugehörigen Java-DTO-Klassen für die SVWS-DB. */
    private static HashMap<String, Class<? extends Object>> mapTablename2DTOClass = null;


    /**
     * Gibt das Mapping der Datenbank-Tabellennamen zu den zugehörigen Java-DTO-Klassen für die SVWS-DB zurück.
     *
     * @return eine Hashmap mit dem Mapping
     */
     private static final HashMap<String, Class<? extends Object>> getMapDTOName2DTOClass() {
         if (mapDTOName2DTOClass == null) {
             mapDTOName2DTOClass = new HashMap<>();
             mapDTOName2DTOClass.put(Rev9DTOKursFortschreibungsart.class.getSimpleName(),Rev9DTOKursFortschreibungsart.class);
             mapDTOName2DTOClass.put(Rev9DTONote.class.getSimpleName(),Rev9DTONote.class);
             mapDTOName2DTOClass.put(Rev9DTOPersonalTyp.class.getSimpleName(),Rev9DTOPersonalTyp.class);
             mapDTOName2DTOClass.put(Rev9DTOGostJahrgangBeratungslehrer.class.getSimpleName(),Rev9DTOGostJahrgangBeratungslehrer.class);
             mapDTOName2DTOClass.put(Rev9DTOGostJahrgangFachkombinationen.class.getSimpleName(),Rev9DTOGostJahrgangFachkombinationen.class);
             mapDTOName2DTOClass.put(Rev9DTOGostJahrgangFaecher.class.getSimpleName(),Rev9DTOGostJahrgangFaecher.class);
             mapDTOName2DTOClass.put(Rev9DTOGostJahrgangsdaten.class.getSimpleName(),Rev9DTOGostJahrgangsdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOGostSchueler.class.getSimpleName(),Rev9DTOGostSchueler.class);
             mapDTOName2DTOClass.put(Rev9DTOGostSchuelerFachbelegungen.class.getSimpleName(),Rev9DTOGostSchuelerFachbelegungen.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenKalenderinformationen.class.getSimpleName(),Rev9DTOGostKlausurenKalenderinformationen.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenKursklausuren.class.getSimpleName(),Rev9DTOGostKlausurenKursklausuren.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenNtaZeiten.class.getSimpleName(),Rev9DTOGostKlausurenNtaZeiten.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenRaeume.class.getSimpleName(),Rev9DTOGostKlausurenRaeume.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenRaeumeStunden.class.getSimpleName(),Rev9DTOGostKlausurenRaeumeStunden.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenRaeumeStundenAufsichten.class.getSimpleName(),Rev9DTOGostKlausurenRaeumeStundenAufsichten.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenSchuelerklausuren.class.getSimpleName(),Rev9DTOGostKlausurenSchuelerklausuren.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenSchuelerklausurenRaeumeStunden.class.getSimpleName(),Rev9DTOGostKlausurenSchuelerklausurenRaeumeStunden.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenTermine.class.getSimpleName(),Rev9DTOGostKlausurenTermine.class);
             mapDTOName2DTOClass.put(Rev9DTOGostKlausurenVorgaben.class.getSimpleName(),Rev9DTOGostKlausurenVorgaben.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockung.class.getSimpleName(),Rev9DTOGostBlockung.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungKurs.class.getSimpleName(),Rev9DTOGostBlockungKurs.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungKurslehrer.class.getSimpleName(),Rev9DTOGostBlockungKurslehrer.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungRegel.class.getSimpleName(),Rev9DTOGostBlockungRegel.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungRegelParameter.class.getSimpleName(),Rev9DTOGostBlockungRegelParameter.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungSchiene.class.getSimpleName(),Rev9DTOGostBlockungSchiene.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungZwischenergebnis.class.getSimpleName(),Rev9DTOGostBlockungZwischenergebnis.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungZwischenergebnisKursSchiene.class.getSimpleName(),Rev9DTOGostBlockungZwischenergebnisKursSchiene.class);
             mapDTOName2DTOClass.put(Rev9DTOGostBlockungZwischenergebnisKursSchueler.class.getSimpleName(),Rev9DTOGostBlockungZwischenergebnisKursSchueler.class);
             mapDTOName2DTOClass.put(Rev9DTOSchildAuswahlFilter.class.getSimpleName(),Rev9DTOSchildAuswahlFilter.class);
             mapDTOName2DTOClass.put(Rev9DTOSchildVerwaltung.class.getSimpleName(),Rev9DTOSchildVerwaltung.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerIndividuelleGruppe.class.getSimpleName(),Rev9DTOSchuelerIndividuelleGruppe.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerIndividuelleGruppeSchueler.class.getSimpleName(),Rev9DTOSchuelerIndividuelleGruppeSchueler.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerReportvorlagen.class.getSimpleName(),Rev9DTOSchuelerReportvorlagen.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerWiedervorlage.class.getSimpleName(),Rev9DTOSchuelerWiedervorlage.class);
             mapDTOName2DTOClass.put(Rev9DTOTextExportVorlagen.class.getSimpleName(),Rev9DTOTextExportVorlagen.class);
             mapDTOName2DTOClass.put(Rev9DTOZuordnungReportvorlagen.class.getSimpleName(),Rev9DTOZuordnungReportvorlagen.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzer.class.getSimpleName(),Rev9DTOBenutzer.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzerAllgemein.class.getSimpleName(),Rev9DTOBenutzerAllgemein.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzerKompetenz.class.getSimpleName(),Rev9DTOBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzerMail.class.getSimpleName(),Rev9DTOBenutzerMail.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzergruppe.class.getSimpleName(),Rev9DTOBenutzergruppe.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzergruppenKompetenz.class.getSimpleName(),Rev9DTOBenutzergruppenKompetenz.class);
             mapDTOName2DTOClass.put(Rev9DTOBenutzergruppenMitglied.class.getSimpleName(),Rev9DTOBenutzergruppenMitglied.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogBenutzerKompetenz.class.getSimpleName(),Rev9DTOKatalogBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogBenutzerKompetenzGruppe.class.getSimpleName(),Rev9DTOKatalogBenutzerKompetenzGruppe.class);
             mapDTOName2DTOClass.put(Rev9DTOProtokollLogin.class.getSimpleName(),Rev9DTOProtokollLogin.class);
             mapDTOName2DTOClass.put(Rev9DTOBeschaeftigungsart.class.getSimpleName(),Rev9DTOBeschaeftigungsart.class);
             mapDTOName2DTOClass.put(Rev9DTOFachgliederungen.class.getSimpleName(),Rev9DTOFachgliederungen.class);
             mapDTOName2DTOClass.put(Rev9DTOFachklassen.class.getSimpleName(),Rev9DTOFachklassen.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogZertifikate.class.getSimpleName(),Rev9DTOKatalogZertifikate.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerBKAbschluss.class.getSimpleName(),Rev9DTOSchuelerBKAbschluss.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerBKFach.class.getSimpleName(),Rev9DTOSchuelerBKFach.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerZuweisung.class.getSimpleName(),Rev9DTOSchuelerZuweisung.class);
             mapDTOName2DTOClass.put(Rev9DTOZertifikate.class.getSimpleName(),Rev9DTOZertifikate.class);
             mapDTOName2DTOClass.put(Rev9DTOErzieherDatenschutz.class.getSimpleName(),Rev9DTOErzieherDatenschutz.class);
             mapDTOName2DTOClass.put(Rev9DTOErzieherLernplattform.class.getSimpleName(),Rev9DTOErzieherLernplattform.class);
             mapDTOName2DTOClass.put(Rev9DTOErzieherart.class.getSimpleName(),Rev9DTOErzieherart.class);
             mapDTOName2DTOClass.put(Rev9DTOErzieherfunktion.class.getSimpleName(),Rev9DTOErzieherfunktion.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerErzieherAdresse.class.getSimpleName(),Rev9DTOSchuelerErzieherAdresse.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerTelefon.class.getSimpleName(),Rev9DTOSchuelerTelefon.class);
             mapDTOName2DTOClass.put(Rev9DTOTelefonArt.class.getSimpleName(),Rev9DTOTelefonArt.class);
             mapDTOName2DTOClass.put(Rev9DTOFach.class.getSimpleName(),Rev9DTOFach.class);
             mapDTOName2DTOClass.put(Rev9DTOFachTeilleistungsarten.class.getSimpleName(),Rev9DTOFachTeilleistungsarten.class);
             mapDTOName2DTOClass.put(Rev9DTOFachgruppen.class.getSimpleName(),Rev9DTOFachgruppen.class);
             mapDTOName2DTOClass.put(Rev9DTOFaecherKatalog.class.getSimpleName(),Rev9DTOFaecherKatalog.class);
             mapDTOName2DTOClass.put(Rev9DTOFaecherKatalogKeys.class.getSimpleName(),Rev9DTOFaecherKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOFaecherKatalogSchulformen.class.getSimpleName(),Rev9DTOFaecherKatalogSchulformen.class);
             mapDTOName2DTOClass.put(Rev9DTOFaecherNichtMoeglicheKombination.class.getSimpleName(),Rev9DTOFaecherNichtMoeglicheKombination.class);
             mapDTOName2DTOClass.put(Rev9DTOAnkreuzdaten.class.getSimpleName(),Rev9DTOAnkreuzdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOAnkreuzfloskeln.class.getSimpleName(),Rev9DTOAnkreuzfloskeln.class);
             mapDTOName2DTOClass.put(Rev9DTOKindergarten.class.getSimpleName(),Rev9DTOKindergarten.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerAnkreuzfloskeln.class.getSimpleName(),Rev9DTOSchuelerAnkreuzfloskeln.class);
             mapDTOName2DTOClass.put(Rev9DTOEigeneImporte.class.getSimpleName(),Rev9DTOEigeneImporte.class);
             mapDTOName2DTOClass.put(Rev9DTOEigeneImporteFelder.class.getSimpleName(),Rev9DTOEigeneImporteFelder.class);
             mapDTOName2DTOClass.put(Rev9DTOEigeneImporteTabellen.class.getSimpleName(),Rev9DTOEigeneImporteTabellen.class);
             mapDTOName2DTOClass.put(Rev9DTOAnsprechpartnerAllgemeineAdresse.class.getSimpleName(),Rev9DTOAnsprechpartnerAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(Rev9DTOFahrschuelerart.class.getSimpleName(),Rev9DTOFahrschuelerart.class);
             mapDTOName2DTOClass.put(Rev9DTOFloskelgruppen.class.getSimpleName(),Rev9DTOFloskelgruppen.class);
             mapDTOName2DTOClass.put(Rev9DTOFloskeln.class.getSimpleName(),Rev9DTOFloskeln.class);
             mapDTOName2DTOClass.put(Rev9DTOHaltestellen.class.getSimpleName(),Rev9DTOHaltestellen.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogAdressart.class.getSimpleName(),Rev9DTOKatalogAdressart.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogAllgemeineAdresse.class.getSimpleName(),Rev9DTOKatalogAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogAufsichtsbereich.class.getSimpleName(),Rev9DTOKatalogAufsichtsbereich.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogDatenschutz.class.getSimpleName(),Rev9DTOKatalogDatenschutz.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogRaum.class.getSimpleName(),Rev9DTOKatalogRaum.class);
             mapDTOName2DTOClass.put(Rev9DTOKonfession.class.getSimpleName(),Rev9DTOKonfession.class);
             mapDTOName2DTOClass.put(Rev9DTOKursarten.class.getSimpleName(),Rev9DTOKursarten.class);
             mapDTOName2DTOClass.put(Rev9DTOOrt.class.getSimpleName(),Rev9DTOOrt.class);
             mapDTOName2DTOClass.put(Rev9DTOOrtsteil.class.getSimpleName(),Rev9DTOOrtsteil.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuleNRW.class.getSimpleName(),Rev9DTOSchuleNRW.class);
             mapDTOName2DTOClass.put(Rev9DTOSchulfunktion.class.getSimpleName(),Rev9DTOSchulfunktion.class);
             mapDTOName2DTOClass.put(Rev9DTOSchwerpunkt.class.getSimpleName(),Rev9DTOSchwerpunkt.class);
             mapDTOName2DTOClass.put(Rev9DTOTextDateien.class.getSimpleName(),Rev9DTOTextDateien.class);
             mapDTOName2DTOClass.put(Rev9DTOVermerkArt.class.getSimpleName(),Rev9DTOVermerkArt.class);
             mapDTOName2DTOClass.put(Rev9DTOKlassen.class.getSimpleName(),Rev9DTOKlassen.class);
             mapDTOName2DTOClass.put(Rev9DTOKlassenLeitung.class.getSimpleName(),Rev9DTOKlassenLeitung.class);
             mapDTOName2DTOClass.put(Rev9DTOKlassenartenKatalogKeys.class.getSimpleName(),Rev9DTOKlassenartenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOKurs.class.getSimpleName(),Rev9DTOKurs.class);
             mapDTOName2DTOClass.put(Rev9DTOKursLehrer.class.getSimpleName(),Rev9DTOKursLehrer.class);
             mapDTOName2DTOClass.put(Rev9DTOKursSchueler.class.getSimpleName(),Rev9DTOKursSchueler.class);
             mapDTOName2DTOClass.put(Rev9DTOKursartenKatalogKeys.class.getSimpleName(),Rev9DTOKursartenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrer.class.getSimpleName(),Rev9DTOLehrer.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerAbschnittsdaten.class.getSimpleName(),Rev9DTOLehrerAbschnittsdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerAnrechnungsstunde.class.getSimpleName(),Rev9DTOLehrerAnrechnungsstunde.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerDatenschutz.class.getSimpleName(),Rev9DTOLehrerDatenschutz.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerEntlastungsstunde.class.getSimpleName(),Rev9DTOLehrerEntlastungsstunde.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerFoto.class.getSimpleName(),Rev9DTOLehrerFoto.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerFunktion.class.getSimpleName(),Rev9DTOLehrerFunktion.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerLehramt.class.getSimpleName(),Rev9DTOLehrerLehramt.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerLehramtBefaehigung.class.getSimpleName(),Rev9DTOLehrerLehramtBefaehigung.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerLehramtFachrichtung.class.getSimpleName(),Rev9DTOLehrerLehramtFachrichtung.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerLeitungsfunktionKeys.class.getSimpleName(),Rev9DTOLehrerLeitungsfunktionKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerLernplattform.class.getSimpleName(),Rev9DTOLehrerLernplattform.class);
             mapDTOName2DTOClass.put(Rev9DTOLehrerMehrleistung.class.getSimpleName(),Rev9DTOLehrerMehrleistung.class);
             mapDTOName2DTOClass.put(Rev9DTOSchulleitung.class.getSimpleName(),Rev9DTOSchulleitung.class);
             mapDTOName2DTOClass.put(Rev9DTOPersonengruppen.class.getSimpleName(),Rev9DTOPersonengruppen.class);
             mapDTOName2DTOClass.put(Rev9DTOPersonengruppenPersonen.class.getSimpleName(),Rev9DTOPersonengruppenPersonen.class);
             mapDTOName2DTOClass.put(Rev9DTOEinschulungsart.class.getSimpleName(),Rev9DTOEinschulungsart.class);
             mapDTOName2DTOClass.put(Rev9DTOEntlassarten.class.getSimpleName(),Rev9DTOEntlassarten.class);
             mapDTOName2DTOClass.put(Rev9DTOFoerderschwerpunkt.class.getSimpleName(),Rev9DTOFoerderschwerpunkt.class);
             mapDTOName2DTOClass.put(Rev9DTOSchueler.class.getSimpleName(),Rev9DTOSchueler.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerAbgaenge.class.getSimpleName(),Rev9DTOSchuelerAbgaenge.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerAllgemeineAdresse.class.getSimpleName(),Rev9DTOSchuelerAllgemeineAdresse.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerDatenschutz.class.getSimpleName(),Rev9DTOSchuelerDatenschutz.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerFehlstunden.class.getSimpleName(),Rev9DTOSchuelerFehlstunden.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerFoerderempfehlung.class.getSimpleName(),Rev9DTOSchuelerFoerderempfehlung.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerFoto.class.getSimpleName(),Rev9DTOSchuelerFoto.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerGrundschuldaten.class.getSimpleName(),Rev9DTOSchuelerGrundschuldaten.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerKAoADaten.class.getSimpleName(),Rev9DTOSchuelerKAoADaten.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerLeistungsdaten.class.getSimpleName(),Rev9DTOSchuelerLeistungsdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerLernabschnittsdaten.class.getSimpleName(),Rev9DTOSchuelerLernabschnittsdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerLernplattform.class.getSimpleName(),Rev9DTOSchuelerLernplattform.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerMerkmale.class.getSimpleName(),Rev9DTOSchuelerMerkmale.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerPSFachBemerkungen.class.getSimpleName(),Rev9DTOSchuelerPSFachBemerkungen.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerSprachenfolge.class.getSimpleName(),Rev9DTOSchuelerSprachenfolge.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerSprachpruefungen.class.getSimpleName(),Rev9DTOSchuelerSprachpruefungen.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerTeilleistung.class.getSimpleName(),Rev9DTOSchuelerTeilleistung.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerVermerke.class.getSimpleName(),Rev9DTOSchuelerVermerke.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerZP10.class.getSimpleName(),Rev9DTOSchuelerZP10.class);
             mapDTOName2DTOClass.put(Rev9DTOSportbefreiung.class.getSimpleName(),Rev9DTOSportbefreiung.class);
             mapDTOName2DTOClass.put(Rev9DTOTeilleistungsarten.class.getSimpleName(),Rev9DTOTeilleistungsarten.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerAbitur.class.getSimpleName(),Rev9DTOSchuelerAbitur.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerAbiturFach.class.getSimpleName(),Rev9DTOSchuelerAbiturFach.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerFHR.class.getSimpleName(),Rev9DTOSchuelerFHR.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerFHRFach.class.getSimpleName(),Rev9DTOSchuelerFHRFach.class);
             mapDTOName2DTOClass.put(Rev9DTOAbteilungen.class.getSimpleName(),Rev9DTOAbteilungen.class);
             mapDTOName2DTOClass.put(Rev9DTOAbteilungsKlassen.class.getSimpleName(),Rev9DTOAbteilungsKlassen.class);
             mapDTOName2DTOClass.put(Rev9DTOAlleJahrgaengeKeys.class.getSimpleName(),Rev9DTOAlleJahrgaengeKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOAlleSchulformen.class.getSimpleName(),Rev9DTOAlleSchulformen.class);
             mapDTOName2DTOClass.put(Rev9DTOAllgemeineMerkmaleKatalogKeys.class.getSimpleName(),Rev9DTOAllgemeineMerkmaleKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOBerufskollegAnlagen.class.getSimpleName(),Rev9DTOBerufskollegAnlagen.class);
             mapDTOName2DTOClass.put(Rev9DTOBerufskollegBerufsebenen1.class.getSimpleName(),Rev9DTOBerufskollegBerufsebenen1.class);
             mapDTOName2DTOClass.put(Rev9DTOBerufskollegBerufsebenen2.class.getSimpleName(),Rev9DTOBerufskollegBerufsebenen2.class);
             mapDTOName2DTOClass.put(Rev9DTOBerufskollegBerufsebenen3.class.getSimpleName(),Rev9DTOBerufskollegBerufsebenen3.class);
             mapDTOName2DTOClass.put(Rev9DTOBerufskollegFachklassenKeys.class.getSimpleName(),Rev9DTOBerufskollegFachklassenKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOEigeneSchule.class.getSimpleName(),Rev9DTOEigeneSchule.class);
             mapDTOName2DTOClass.put(Rev9DTOEigeneSchuleKAoADaten.class.getSimpleName(),Rev9DTOEigeneSchuleKAoADaten.class);
             mapDTOName2DTOClass.put(Rev9DTOEinschulungsartenKatalogKeys.class.getSimpleName(),Rev9DTOEinschulungsartenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOHerkunft.class.getSimpleName(),Rev9DTOHerkunft.class);
             mapDTOName2DTOClass.put(Rev9DTOHerkunftSchulformen.class.getSimpleName(),Rev9DTOHerkunftSchulformen.class);
             mapDTOName2DTOClass.put(Rev9DTOHerkunftsart.class.getSimpleName(),Rev9DTOHerkunftsart.class);
             mapDTOName2DTOClass.put(Rev9DTOHerkunftsartSchulformen.class.getSimpleName(),Rev9DTOHerkunftsartSchulformen.class);
             mapDTOName2DTOClass.put(Rev9DTOJahrgang.class.getSimpleName(),Rev9DTOJahrgang.class);
             mapDTOName2DTOClass.put(Rev9DTOMerkmale.class.getSimpleName(),Rev9DTOMerkmale.class);
             mapDTOName2DTOClass.put(Rev9DTOOrganisationsformenKatalogKeys.class.getSimpleName(),Rev9DTOOrganisationsformenKatalogKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOSchulformen.class.getSimpleName(),Rev9DTOSchulformen.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuljahresabschnitte.class.getSimpleName(),Rev9DTOSchuljahresabschnitte.class);
             mapDTOName2DTOClass.put(Rev9DTOSchultexte.class.getSimpleName(),Rev9DTOSchultexte.class);
             mapDTOName2DTOClass.put(Rev9DTOStundentafel.class.getSimpleName(),Rev9DTOStundentafel.class);
             mapDTOName2DTOClass.put(Rev9DTOStundentafelFaecher.class.getSimpleName(),Rev9DTOStundentafelFaecher.class);
             mapDTOName2DTOClass.put(Rev9DTOTeilstandorte.class.getSimpleName(),Rev9DTOTeilstandorte.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogPausenzeit.class.getSimpleName(),Rev9DTOKatalogPausenzeit.class);
             mapDTOName2DTOClass.put(Rev9DTOKatalogZeitraster.class.getSimpleName(),Rev9DTOKatalogZeitraster.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplan.class.getSimpleName(),Rev9DTOStundenplan.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanAufsichtsbereich.class.getSimpleName(),Rev9DTOStundenplanAufsichtsbereich.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanPausenaufsichten.class.getSimpleName(),Rev9DTOStundenplanPausenaufsichten.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanPausenaufsichtenBereiche.class.getSimpleName(),Rev9DTOStundenplanPausenaufsichtenBereiche.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanPausenzeit.class.getSimpleName(),Rev9DTOStundenplanPausenzeit.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanRaum.class.getSimpleName(),Rev9DTOStundenplanRaum.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanUnterricht.class.getSimpleName(),Rev9DTOStundenplanUnterricht.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanUnterrichtLehrer.class.getSimpleName(),Rev9DTOStundenplanUnterrichtLehrer.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanUnterrichtRaum.class.getSimpleName(),Rev9DTOStundenplanUnterrichtRaum.class);
             mapDTOName2DTOClass.put(Rev9DTOStundenplanZeitraster.class.getSimpleName(),Rev9DTOStundenplanZeitraster.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuelerStatus.class.getSimpleName(),Rev9DTOSchuelerStatus.class);
             mapDTOName2DTOClass.put(Rev9DTOHerkunftKeys.class.getSimpleName(),Rev9DTOHerkunftKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOHerkunftsartKeys.class.getSimpleName(),Rev9DTOHerkunftsartKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOKAoAAnschlussoptionKeys.class.getSimpleName(),Rev9DTOKAoAAnschlussoptionKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOKAoABerufsfeldKeys.class.getSimpleName(),Rev9DTOKAoABerufsfeldKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOKAoAKategorieKeys.class.getSimpleName(),Rev9DTOKAoAKategorieKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOKAoAMerkmalKeys.class.getSimpleName(),Rev9DTOKAoAMerkmalKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOKAoASBOEB4Keys.class.getSimpleName(),Rev9DTOKAoASBOEB4Keys.class);
             mapDTOName2DTOClass.put(Rev9DTOKAoAZusatzmerkmalKeys.class.getSimpleName(),Rev9DTOKAoAZusatzmerkmalKeys.class);
             mapDTOName2DTOClass.put(Rev9DTONationalitaetenKeys.class.getSimpleName(),Rev9DTONationalitaetenKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOReligionKeys.class.getSimpleName(),Rev9DTOReligionKeys.class);
             mapDTOName2DTOClass.put(Rev9DTOCredentials.class.getSimpleName(),Rev9DTOCredentials.class);
             mapDTOName2DTOClass.put(Rev9DTOCredentialsLernplattformen.class.getSimpleName(),Rev9DTOCredentialsLernplattformen.class);
             mapDTOName2DTOClass.put(Rev9DTOLernplattformen.class.getSimpleName(),Rev9DTOLernplattformen.class);
             mapDTOName2DTOClass.put(Rev9DTOSchuleCredentials.class.getSimpleName(),Rev9DTOSchuleCredentials.class);
             mapDTOName2DTOClass.put(Rev9DTOClientKonfigurationBenutzer.class.getSimpleName(),Rev9DTOClientKonfigurationBenutzer.class);
             mapDTOName2DTOClass.put(Rev9DTOClientKonfigurationGlobal.class.getSimpleName(),Rev9DTOClientKonfigurationGlobal.class);
             mapDTOName2DTOClass.put(Rev9DTODavRessource.class.getSimpleName(),Rev9DTODavRessource.class);
             mapDTOName2DTOClass.put(Rev9DTODavRessourceCollection.class.getSimpleName(),Rev9DTODavRessourceCollection.class);
             mapDTOName2DTOClass.put(Rev9DTODavRessourceCollectionsACL.class.getSimpleName(),Rev9DTODavRessourceCollectionsACL.class);
             mapDTOName2DTOClass.put(Rev9DTODavSyncTokenLehrer.class.getSimpleName(),Rev9DTODavSyncTokenLehrer.class);
             mapDTOName2DTOClass.put(Rev9DTODavSyncTokenSchueler.class.getSimpleName(),Rev9DTODavSyncTokenSchueler.class);
             mapDTOName2DTOClass.put(Rev9DTOCoreTypeVersion.class.getSimpleName(),Rev9DTOCoreTypeVersion.class);
             mapDTOName2DTOClass.put(Rev9DTODBAutoInkremente.class.getSimpleName(),Rev9DTODBAutoInkremente.class);
             mapDTOName2DTOClass.put(Rev9DTODBVersion.class.getSimpleName(),Rev9DTODBVersion.class);
             mapDTOName2DTOClass.put(Rev9DTOEnmLeistungsdaten.class.getSimpleName(),Rev9DTOEnmLeistungsdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOEnmLernabschnittsdaten.class.getSimpleName(),Rev9DTOEnmLernabschnittsdaten.class);
             mapDTOName2DTOClass.put(Rev9DTOViewBenutzer.class.getSimpleName(),Rev9DTOViewBenutzer.class);
             mapDTOName2DTOClass.put(Rev9DTOViewBenutzerKompetenz.class.getSimpleName(),Rev9DTOViewBenutzerKompetenz.class);
             mapDTOName2DTOClass.put(Rev9DTOViewBenutzerdetails.class.getSimpleName(),Rev9DTOViewBenutzerdetails.class);
             mapDTOName2DTOClass.put(Rev9DTOViewGostSchuelerAbiturjahrgang.class.getSimpleName(),Rev9DTOViewGostSchuelerAbiturjahrgang.class);
         }
         return mapDTOName2DTOClass;
     }


    /**
     * Gibt die DTO-Klasse mit dem angegebenen DTO-Namen zurück.
     *
     * @param name   der DTO-Name
     *
     * @return die DTO-Klasse
     */
    public static Class<? extends Object> getFromDTOName(String name) {
    	return getMapDTOName2DTOClass().get(name);
    }


    /**
     * Gibt das Mapping der Namen aller Java-DTO-Klassen für die SVWS-DB zu den zugehörigen
     * Java-DTO-Klassen zurück.
     *
     * @return eine Hashmap mit dem Mapping
     */
     private static final HashMap<String, Class<? extends Object>> getMapTablename2DTOClass() {
         if (mapTablename2DTOClass == null) {
             mapTablename2DTOClass = new HashMap<>();
             mapTablename2DTOClass.put("KursFortschreibungsarten",Rev9DTOKursFortschreibungsart.class);
             mapTablename2DTOClass.put("Noten",Rev9DTONote.class);
             mapTablename2DTOClass.put("PersonalTypen",Rev9DTOPersonalTyp.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Beratungslehrer",Rev9DTOGostJahrgangBeratungslehrer.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Fachkombinationen",Rev9DTOGostJahrgangFachkombinationen.class);
             mapTablename2DTOClass.put("Gost_Jahrgang_Faecher",Rev9DTOGostJahrgangFaecher.class);
             mapTablename2DTOClass.put("Gost_Jahrgangsdaten",Rev9DTOGostJahrgangsdaten.class);
             mapTablename2DTOClass.put("Gost_Schueler",Rev9DTOGostSchueler.class);
             mapTablename2DTOClass.put("Gost_Schueler_Fachwahlen",Rev9DTOGostSchuelerFachbelegungen.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Kalenderinformationen",Rev9DTOGostKlausurenKalenderinformationen.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Kursklausuren",Rev9DTOGostKlausurenKursklausuren.class);
             mapTablename2DTOClass.put("Gost_Klausuren_NtaZeiten",Rev9DTOGostKlausurenNtaZeiten.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Raeume",Rev9DTOGostKlausurenRaeume.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Raeume_Stunden",Rev9DTOGostKlausurenRaeumeStunden.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Raeume_Stunden_Aufsichten",Rev9DTOGostKlausurenRaeumeStundenAufsichten.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Schuelerklausuren",Rev9DTOGostKlausurenSchuelerklausuren.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Schuelerklausuren_Raeume_Stunden",Rev9DTOGostKlausurenSchuelerklausurenRaeumeStunden.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Termine",Rev9DTOGostKlausurenTermine.class);
             mapTablename2DTOClass.put("Gost_Klausuren_Vorgaben",Rev9DTOGostKlausurenVorgaben.class);
             mapTablename2DTOClass.put("Gost_Blockung",Rev9DTOGostBlockung.class);
             mapTablename2DTOClass.put("Gost_Blockung_Kurse",Rev9DTOGostBlockungKurs.class);
             mapTablename2DTOClass.put("Gost_Blockung_Kurslehrer",Rev9DTOGostBlockungKurslehrer.class);
             mapTablename2DTOClass.put("Gost_Blockung_Regeln",Rev9DTOGostBlockungRegel.class);
             mapTablename2DTOClass.put("Gost_Blockung_Regelparameter",Rev9DTOGostBlockungRegelParameter.class);
             mapTablename2DTOClass.put("Gost_Blockung_Schienen",Rev9DTOGostBlockungSchiene.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse",Rev9DTOGostBlockungZwischenergebnis.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse_Kurs_Schienen",Rev9DTOGostBlockungZwischenergebnisKursSchiene.class);
             mapTablename2DTOClass.put("Gost_Blockung_Zwischenergebnisse_Kurs_Schueler",Rev9DTOGostBlockungZwischenergebnisKursSchueler.class);
             mapTablename2DTOClass.put("SchildFilter",Rev9DTOSchildAuswahlFilter.class);
             mapTablename2DTOClass.put("Schild_Verwaltung",Rev9DTOSchildVerwaltung.class);
             mapTablename2DTOClass.put("SchuelerListe",Rev9DTOSchuelerIndividuelleGruppe.class);
             mapTablename2DTOClass.put("SchuelerListe_Inhalt",Rev9DTOSchuelerIndividuelleGruppeSchueler.class);
             mapTablename2DTOClass.put("SchuelerReportvorlagen",Rev9DTOSchuelerReportvorlagen.class);
             mapTablename2DTOClass.put("SchuelerWiedervorlage",Rev9DTOSchuelerWiedervorlage.class);
             mapTablename2DTOClass.put("TextExportVorlagen",Rev9DTOTextExportVorlagen.class);
             mapTablename2DTOClass.put("ZuordnungReportvorlagen",Rev9DTOZuordnungReportvorlagen.class);
             mapTablename2DTOClass.put("Benutzer",Rev9DTOBenutzer.class);
             mapTablename2DTOClass.put("BenutzerAllgemein",Rev9DTOBenutzerAllgemein.class);
             mapTablename2DTOClass.put("BenutzerKompetenzen",Rev9DTOBenutzerKompetenz.class);
             mapTablename2DTOClass.put("BenutzerEmail",Rev9DTOBenutzerMail.class);
             mapTablename2DTOClass.put("Benutzergruppen",Rev9DTOBenutzergruppe.class);
             mapTablename2DTOClass.put("BenutzergruppenKompetenzen",Rev9DTOBenutzergruppenKompetenz.class);
             mapTablename2DTOClass.put("BenutzergruppenMitglieder",Rev9DTOBenutzergruppenMitglied.class);
             mapTablename2DTOClass.put("Kompetenzen",Rev9DTOKatalogBenutzerKompetenz.class);
             mapTablename2DTOClass.put("Kompetenzgruppen",Rev9DTOKatalogBenutzerKompetenzGruppe.class);
             mapTablename2DTOClass.put("Logins",Rev9DTOProtokollLogin.class);
             mapTablename2DTOClass.put("K_BeschaeftigungsArt",Rev9DTOBeschaeftigungsart.class);
             mapTablename2DTOClass.put("Fach_Gliederungen",Rev9DTOFachgliederungen.class);
             mapTablename2DTOClass.put("EigeneSchule_Fachklassen",Rev9DTOFachklassen.class);
             mapTablename2DTOClass.put("K_Zertifikate",Rev9DTOKatalogZertifikate.class);
             mapTablename2DTOClass.put("SchuelerBKAbschluss",Rev9DTOSchuelerBKAbschluss.class);
             mapTablename2DTOClass.put("SchuelerBKFaecher",Rev9DTOSchuelerBKFach.class);
             mapTablename2DTOClass.put("SchuelerZuweisungen",Rev9DTOSchuelerZuweisung.class);
             mapTablename2DTOClass.put("EigeneSchule_Zertifikate",Rev9DTOZertifikate.class);
             mapTablename2DTOClass.put("ErzieherDatenschutz",Rev9DTOErzieherDatenschutz.class);
             mapTablename2DTOClass.put("ErzieherLernplattform",Rev9DTOErzieherLernplattform.class);
             mapTablename2DTOClass.put("K_ErzieherArt",Rev9DTOErzieherart.class);
             mapTablename2DTOClass.put("K_ErzieherFunktion",Rev9DTOErzieherfunktion.class);
             mapTablename2DTOClass.put("SchuelerErzAdr",Rev9DTOSchuelerErzieherAdresse.class);
             mapTablename2DTOClass.put("SchuelerTelefone",Rev9DTOSchuelerTelefon.class);
             mapTablename2DTOClass.put("K_TelefonArt",Rev9DTOTelefonArt.class);
             mapTablename2DTOClass.put("EigeneSchule_Faecher",Rev9DTOFach.class);
             mapTablename2DTOClass.put("EigeneSchule_FachTeilleistungen",Rev9DTOFachTeilleistungsarten.class);
             mapTablename2DTOClass.put("Fachgruppen",Rev9DTOFachgruppen.class);
             mapTablename2DTOClass.put("FachKatalog",Rev9DTOFaecherKatalog.class);
             mapTablename2DTOClass.put("FachKatalog_Keys",Rev9DTOFaecherKatalogKeys.class);
             mapTablename2DTOClass.put("FachKatalog_Schulformen",Rev9DTOFaecherKatalogSchulformen.class);
             mapTablename2DTOClass.put("NichtMoeglAbiFachKombi",Rev9DTOFaecherNichtMoeglicheKombination.class);
             mapTablename2DTOClass.put("K_Ankreuzdaten",Rev9DTOAnkreuzdaten.class);
             mapTablename2DTOClass.put("K_Ankreuzfloskeln",Rev9DTOAnkreuzfloskeln.class);
             mapTablename2DTOClass.put("K_Kindergarten",Rev9DTOKindergarten.class);
             mapTablename2DTOClass.put("SchuelerAnkreuzfloskeln",Rev9DTOSchuelerAnkreuzfloskeln.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte",Rev9DTOEigeneImporte.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte_Felder",Rev9DTOEigeneImporteFelder.class);
             mapTablename2DTOClass.put("ImpExp_EigeneImporte_Tabellen",Rev9DTOEigeneImporteTabellen.class);
             mapTablename2DTOClass.put("AllgAdrAnsprechpartner",Rev9DTOAnsprechpartnerAllgemeineAdresse.class);
             mapTablename2DTOClass.put("K_FahrschuelerArt",Rev9DTOFahrschuelerart.class);
             mapTablename2DTOClass.put("Floskelgruppen",Rev9DTOFloskelgruppen.class);
             mapTablename2DTOClass.put("Floskeln",Rev9DTOFloskeln.class);
             mapTablename2DTOClass.put("K_Haltestelle",Rev9DTOHaltestellen.class);
             mapTablename2DTOClass.put("K_Adressart",Rev9DTOKatalogAdressart.class);
             mapTablename2DTOClass.put("K_AllgAdresse",Rev9DTOKatalogAllgemeineAdresse.class);
             mapTablename2DTOClass.put("Katalog_Aufsichtsbereich",Rev9DTOKatalogAufsichtsbereich.class);
             mapTablename2DTOClass.put("K_Datenschutz",Rev9DTOKatalogDatenschutz.class);
             mapTablename2DTOClass.put("Katalog_Raeume",Rev9DTOKatalogRaum.class);
             mapTablename2DTOClass.put("K_Religion",Rev9DTOKonfession.class);
             mapTablename2DTOClass.put("EigeneSchule_Kursart",Rev9DTOKursarten.class);
             mapTablename2DTOClass.put("K_Ort",Rev9DTOOrt.class);
             mapTablename2DTOClass.put("K_Ortsteil",Rev9DTOOrtsteil.class);
             mapTablename2DTOClass.put("K_Schule",Rev9DTOSchuleNRW.class);
             mapTablename2DTOClass.put("K_Schulfunktionen",Rev9DTOSchulfunktion.class);
             mapTablename2DTOClass.put("K_Schwerpunkt",Rev9DTOSchwerpunkt.class);
             mapTablename2DTOClass.put("K_Textdateien",Rev9DTOTextDateien.class);
             mapTablename2DTOClass.put("K_Vermerkart",Rev9DTOVermerkArt.class);
             mapTablename2DTOClass.put("Klassen",Rev9DTOKlassen.class);
             mapTablename2DTOClass.put("KlassenLehrer",Rev9DTOKlassenLeitung.class);
             mapTablename2DTOClass.put("KlassenartenKatalog_Keys",Rev9DTOKlassenartenKatalogKeys.class);
             mapTablename2DTOClass.put("Kurse",Rev9DTOKurs.class);
             mapTablename2DTOClass.put("KursLehrer",Rev9DTOKursLehrer.class);
             mapTablename2DTOClass.put("Kurs_Schueler",Rev9DTOKursSchueler.class);
             mapTablename2DTOClass.put("KursartenKatalog_Keys",Rev9DTOKursartenKatalogKeys.class);
             mapTablename2DTOClass.put("K_Lehrer",Rev9DTOLehrer.class);
             mapTablename2DTOClass.put("LehrerAbschnittsdaten",Rev9DTOLehrerAbschnittsdaten.class);
             mapTablename2DTOClass.put("LehrerAnrechnung",Rev9DTOLehrerAnrechnungsstunde.class);
             mapTablename2DTOClass.put("LehrerDatenschutz",Rev9DTOLehrerDatenschutz.class);
             mapTablename2DTOClass.put("LehrerEntlastung",Rev9DTOLehrerEntlastungsstunde.class);
             mapTablename2DTOClass.put("LehrerFotos",Rev9DTOLehrerFoto.class);
             mapTablename2DTOClass.put("LehrerFunktionen",Rev9DTOLehrerFunktion.class);
             mapTablename2DTOClass.put("LehrerLehramt",Rev9DTOLehrerLehramt.class);
             mapTablename2DTOClass.put("LehrerLehramtLehrbef",Rev9DTOLehrerLehramtBefaehigung.class);
             mapTablename2DTOClass.put("LehrerLehramtFachr",Rev9DTOLehrerLehramtFachrichtung.class);
             mapTablename2DTOClass.put("LehrerLeitungsfunktion_Keys",Rev9DTOLehrerLeitungsfunktionKeys.class);
             mapTablename2DTOClass.put("LehrerLernplattform",Rev9DTOLehrerLernplattform.class);
             mapTablename2DTOClass.put("LehrerMehrleistung",Rev9DTOLehrerMehrleistung.class);
             mapTablename2DTOClass.put("Schulleitung",Rev9DTOSchulleitung.class);
             mapTablename2DTOClass.put("Personengruppen",Rev9DTOPersonengruppen.class);
             mapTablename2DTOClass.put("Personengruppen_Personen",Rev9DTOPersonengruppenPersonen.class);
             mapTablename2DTOClass.put("K_EinschulungsArt",Rev9DTOEinschulungsart.class);
             mapTablename2DTOClass.put("K_EntlassGrund",Rev9DTOEntlassarten.class);
             mapTablename2DTOClass.put("K_Foerderschwerpunkt",Rev9DTOFoerderschwerpunkt.class);
             mapTablename2DTOClass.put("Schueler",Rev9DTOSchueler.class);
             mapTablename2DTOClass.put("SchuelerAbgaenge",Rev9DTOSchuelerAbgaenge.class);
             mapTablename2DTOClass.put("Schueler_AllgAdr",Rev9DTOSchuelerAllgemeineAdresse.class);
             mapTablename2DTOClass.put("SchuelerDatenschutz",Rev9DTOSchuelerDatenschutz.class);
             mapTablename2DTOClass.put("SchuelerFehlstunden",Rev9DTOSchuelerFehlstunden.class);
             mapTablename2DTOClass.put("SchuelerFoerderempfehlungen",Rev9DTOSchuelerFoerderempfehlung.class);
             mapTablename2DTOClass.put("SchuelerFotos",Rev9DTOSchuelerFoto.class);
             mapTablename2DTOClass.put("SchuelerGSDaten",Rev9DTOSchuelerGrundschuldaten.class);
             mapTablename2DTOClass.put("SchuelerKAoADaten",Rev9DTOSchuelerKAoADaten.class);
             mapTablename2DTOClass.put("SchuelerLeistungsdaten",Rev9DTOSchuelerLeistungsdaten.class);
             mapTablename2DTOClass.put("SchuelerLernabschnittsdaten",Rev9DTOSchuelerLernabschnittsdaten.class);
             mapTablename2DTOClass.put("SchuelerLernplattform",Rev9DTOSchuelerLernplattform.class);
             mapTablename2DTOClass.put("SchuelerMerkmale",Rev9DTOSchuelerMerkmale.class);
             mapTablename2DTOClass.put("SchuelerLD_PSFachBem",Rev9DTOSchuelerPSFachBemerkungen.class);
             mapTablename2DTOClass.put("SchuelerSprachenfolge",Rev9DTOSchuelerSprachenfolge.class);
             mapTablename2DTOClass.put("SchuelerSprachpruefungen",Rev9DTOSchuelerSprachpruefungen.class);
             mapTablename2DTOClass.put("SchuelerEinzelleistungen",Rev9DTOSchuelerTeilleistung.class);
             mapTablename2DTOClass.put("SchuelerVermerke",Rev9DTOSchuelerVermerke.class);
             mapTablename2DTOClass.put("SchuelerZP10",Rev9DTOSchuelerZP10.class);
             mapTablename2DTOClass.put("K_Sportbefreiung",Rev9DTOSportbefreiung.class);
             mapTablename2DTOClass.put("K_Einzelleistungen",Rev9DTOTeilleistungsarten.class);
             mapTablename2DTOClass.put("SchuelerAbitur",Rev9DTOSchuelerAbitur.class);
             mapTablename2DTOClass.put("SchuelerAbiFaecher",Rev9DTOSchuelerAbiturFach.class);
             mapTablename2DTOClass.put("SchuelerFHR",Rev9DTOSchuelerFHR.class);
             mapTablename2DTOClass.put("SchuelerFHRFaecher",Rev9DTOSchuelerFHRFach.class);
             mapTablename2DTOClass.put("EigeneSchule_Abteilungen",Rev9DTOAbteilungen.class);
             mapTablename2DTOClass.put("EigeneSchule_Abt_Kl",Rev9DTOAbteilungsKlassen.class);
             mapTablename2DTOClass.put("Jahrgaenge_Keys",Rev9DTOAlleJahrgaengeKeys.class);
             mapTablename2DTOClass.put("Schulformen",Rev9DTOAlleSchulformen.class);
             mapTablename2DTOClass.put("AllgemeineMerkmaleKatalog_Keys",Rev9DTOAllgemeineMerkmaleKatalogKeys.class);
             mapTablename2DTOClass.put("Berufskolleg_Anlagen",Rev9DTOBerufskollegAnlagen.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen1",Rev9DTOBerufskollegBerufsebenen1.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen2",Rev9DTOBerufskollegBerufsebenen2.class);
             mapTablename2DTOClass.put("Berufskolleg_Berufsebenen3",Rev9DTOBerufskollegBerufsebenen3.class);
             mapTablename2DTOClass.put("Berufskolleg_Fachklassen_Keys",Rev9DTOBerufskollegFachklassenKeys.class);
             mapTablename2DTOClass.put("EigeneSchule",Rev9DTOEigeneSchule.class);
             mapTablename2DTOClass.put("EigeneSchule_KAoADaten",Rev9DTOEigeneSchuleKAoADaten.class);
             mapTablename2DTOClass.put("EinschulungsartKatalog_Keys",Rev9DTOEinschulungsartenKatalogKeys.class);
             mapTablename2DTOClass.put("Herkunft",Rev9DTOHerkunft.class);
             mapTablename2DTOClass.put("Herkunft_Schulformen",Rev9DTOHerkunftSchulformen.class);
             mapTablename2DTOClass.put("Herkunftsart",Rev9DTOHerkunftsart.class);
             mapTablename2DTOClass.put("Herkunftsart_Schulformen",Rev9DTOHerkunftsartSchulformen.class);
             mapTablename2DTOClass.put("EigeneSchule_Jahrgaenge",Rev9DTOJahrgang.class);
             mapTablename2DTOClass.put("EigeneSchule_Merkmale",Rev9DTOMerkmale.class);
             mapTablename2DTOClass.put("OrganisationsformenKatalog_Keys",Rev9DTOOrganisationsformenKatalogKeys.class);
             mapTablename2DTOClass.put("EigeneSchule_Schulformen",Rev9DTOSchulformen.class);
             mapTablename2DTOClass.put("Schuljahresabschnitte",Rev9DTOSchuljahresabschnitte.class);
             mapTablename2DTOClass.put("EigeneSchule_Texte",Rev9DTOSchultexte.class);
             mapTablename2DTOClass.put("Stundentafel",Rev9DTOStundentafel.class);
             mapTablename2DTOClass.put("Stundentafel_Faecher",Rev9DTOStundentafelFaecher.class);
             mapTablename2DTOClass.put("EigeneSchule_Teilstandorte",Rev9DTOTeilstandorte.class);
             mapTablename2DTOClass.put("Katalog_Pausenzeiten",Rev9DTOKatalogPausenzeit.class);
             mapTablename2DTOClass.put("Katalog_Zeitraster",Rev9DTOKatalogZeitraster.class);
             mapTablename2DTOClass.put("Stundenplan",Rev9DTOStundenplan.class);
             mapTablename2DTOClass.put("Stundenplan_Aufsichtsbereiche",Rev9DTOStundenplanAufsichtsbereich.class);
             mapTablename2DTOClass.put("Stundenplan_Pausenaufsichten",Rev9DTOStundenplanPausenaufsichten.class);
             mapTablename2DTOClass.put("Stundenplan_PausenaufsichtenBereich",Rev9DTOStundenplanPausenaufsichtenBereiche.class);
             mapTablename2DTOClass.put("Stundenplan_Pausenzeit",Rev9DTOStundenplanPausenzeit.class);
             mapTablename2DTOClass.put("Stundenplan_Raeume",Rev9DTOStundenplanRaum.class);
             mapTablename2DTOClass.put("Stundenplan_Unterricht",Rev9DTOStundenplanUnterricht.class);
             mapTablename2DTOClass.put("Stundenplan_UnterrichtLehrer",Rev9DTOStundenplanUnterrichtLehrer.class);
             mapTablename2DTOClass.put("Stundenplan_UnterrichtRaum",Rev9DTOStundenplanUnterrichtRaum.class);
             mapTablename2DTOClass.put("Stundenplan_Zeitraster",Rev9DTOStundenplanZeitraster.class);
             mapTablename2DTOClass.put("SchuelerStatus_Keys",Rev9DTOSchuelerStatus.class);
             mapTablename2DTOClass.put("Herkunft_Keys",Rev9DTOHerkunftKeys.class);
             mapTablename2DTOClass.put("Herkunftsart_Keys",Rev9DTOHerkunftsartKeys.class);
             mapTablename2DTOClass.put("KAoA_Anschlussoption_Keys",Rev9DTOKAoAAnschlussoptionKeys.class);
             mapTablename2DTOClass.put("KAoA_Berufsfeld_Keys",Rev9DTOKAoABerufsfeldKeys.class);
             mapTablename2DTOClass.put("KAoA_Kategorie_Keys",Rev9DTOKAoAKategorieKeys.class);
             mapTablename2DTOClass.put("KAoA_Merkmal_Keys",Rev9DTOKAoAMerkmalKeys.class);
             mapTablename2DTOClass.put("KAoA_SBO_Ebene4_Keys",Rev9DTOKAoASBOEB4Keys.class);
             mapTablename2DTOClass.put("KAoA_Zusatzmerkmal_Keys",Rev9DTOKAoAZusatzmerkmalKeys.class);
             mapTablename2DTOClass.put("Nationalitaeten_Keys",Rev9DTONationalitaetenKeys.class);
             mapTablename2DTOClass.put("Religionen_Keys",Rev9DTOReligionKeys.class);
             mapTablename2DTOClass.put("Credentials",Rev9DTOCredentials.class);
             mapTablename2DTOClass.put("CredentialsLernplattformen",Rev9DTOCredentialsLernplattformen.class);
             mapTablename2DTOClass.put("Lernplattformen",Rev9DTOLernplattformen.class);
             mapTablename2DTOClass.put("SchuleCredentials",Rev9DTOSchuleCredentials.class);
             mapTablename2DTOClass.put("SVWS_Client_Konfiguration_Benutzer",Rev9DTOClientKonfigurationBenutzer.class);
             mapTablename2DTOClass.put("SVWS_Client_Konfiguration_Global",Rev9DTOClientKonfigurationGlobal.class);
             mapTablename2DTOClass.put("DavRessources",Rev9DTODavRessource.class);
             mapTablename2DTOClass.put("DavRessourceCollections",Rev9DTODavRessourceCollection.class);
             mapTablename2DTOClass.put("DavRessourceCollectionsACL",Rev9DTODavRessourceCollectionsACL.class);
             mapTablename2DTOClass.put("DavSyncTokenLehrer",Rev9DTODavSyncTokenLehrer.class);
             mapTablename2DTOClass.put("DavSyncTokenSchueler",Rev9DTODavSyncTokenSchueler.class);
             mapTablename2DTOClass.put("SVWS_Core_Type_Versionen",Rev9DTOCoreTypeVersion.class);
             mapTablename2DTOClass.put("SVWS_DB_AutoInkremente",Rev9DTODBAutoInkremente.class);
             mapTablename2DTOClass.put("SVWS_DB_Version",Rev9DTODBVersion.class);
             mapTablename2DTOClass.put("EnmLeistungsdaten",Rev9DTOEnmLeistungsdaten.class);
             mapTablename2DTOClass.put("EnmLernabschnittsdaten",Rev9DTOEnmLernabschnittsdaten.class);
             mapTablename2DTOClass.put("V_Benutzer",Rev9DTOViewBenutzer.class);
             mapTablename2DTOClass.put("V_Benutzerkompetenzen",Rev9DTOViewBenutzerKompetenz.class);
             mapTablename2DTOClass.put("V_BenutzerDetails",Rev9DTOViewBenutzerdetails.class);
             mapTablename2DTOClass.put("V_Gost_Schueler_Abiturjahrgang",Rev9DTOViewGostSchuelerAbiturjahrgang.class);
         }
         return mapTablename2DTOClass;
     }


    /**
     * Gibt die DTO-Klasse mit dem angegebenen Tabellennamen zurück.
     *
     * @param name   der Tabellenname
     *
     * @return die DTO-Klasse
     */
    public static Class<? extends Object> getFromTableName(String name) {
    	return getMapTablename2DTOClass().get(name);
    }

}
