[# th:with="gefilterteKurse = ${GostBlockungsergebnis.kurseGefiltert()}, anzahlGefilterteKurse = ${#lists.size(gefilterteKurse)}"]
    [# th:if="${anzahlGefilterteKurse == 0}"]
        GOSt-Blockung-Kurs-Schueler
    [/]
    [# th:if="${anzahlGefilterteKurse != 0}"]
        [# th:each="kurs,iterState : ${gefilterteKurse}"]
            [# th:if="${iterState.first && (anzahlGefilterteKurse == 1)}"]
                GOSt-Blockung-Kurs-Schueler_[(${#strings.replace(kurs.gostHalbjahr().kuerzel, '.', '')})]_[(${#strings.replace(kurs.bezeichnung(), ' ', '_')})]_[(${#strings.replace(kurs.lehrkraefteAuflistung(), ',', '-')})]_Abi_[(${GostBlockungsergebnis.abiturjahr()})]
            [/]
            [# th:if="${iterState.first && (anzahlGefilterteKurse > 1)}"]
                GOSt-Blockung-Kurs-Schueler_[(${#strings.replace(kurs.gostHalbjahr().kuerzel, '.', '')})]_Abi_[(${GostBlockungsergebnis.abiturjahr()})]
            [/]
        [/]
    [/]
[/]
