plugins {
	id 'svws.gradle.node.plugin'
}

task assembleAdminClient(type: NpmRun) {
	dependsOn rootProject.npmPrepare
	dependsOn ':svws-openapi:assembleTranspiled'
	group = "build"
	args = ['build']
	inputs.files fileTree("$rootDir/svws-webclient/core").matching { exclude "build", "dist" },
				 fileTree("$rootDir/svws-webclient/ui").matching { exclude "build", "dist", ".histoire" },
				 fileTree("$projectDir").matching { exclude "build" }
	outputs.dir file("$buildDir/output")
}

assemble.dependsOn assembleAdminClient

task lint(type: NpmRun) {
	dependsOn assembleAdminClient
	group = "build"
	args = ["test:ts"]
}

task doZip(type: Zip) {
	dependsOn assembleAdminClient
	archiveFileName = "SVWS-Admin-Client.zip"
	destinationDirectory = file("$buildDir")
	from "$buildDir/output"
}

build.dependsOn lint
build.dependsOn doZip

task cleanAdminClient(type: Delete) {
	delete file("$buildDir/output")
}

clean.dependsOn cleanAdminClient
