import "./assets/styles/index.css";

// Regex: \ +(.*):.*'(.*)'\).*
// Replace: export { default as $1 } from "$2";
export type { AbschnittAuswahlProps, AbschnittAuswahlDaten } from "./components/abschnittauswahl/AbschnittAuswahlProps.ts";
export type { SchuelerLaufbahnplanungProps } from "./components/gost/laufbahnplanung/SSchuelerLaufbahnplanungProps";
export type { StundenplanAnsichtPlanungProps } from "./components/stundenplan/StundenplanAnsichtPlanungProps.ts";
export type { StundenplanAnsichtProps, StundenplanAnsichtDragData, StundenplanAnsichtDropZone } from "./components/stundenplan/StundenplanAnsichtProps.ts";
export type { StundenplanAuswahlProps } from "./components/stundenplan/StundenplanAuswahlProps.ts";
export type { StundenplanFachProps } from "./components/stundenplan/StundenplanFachProps.ts";
export type { StundenplanKlassenProps } from "./components/stundenplan/StundenplanKlassenProps";
export type { StundenplanLehrerProps } from "./components/stundenplan/StundenplanLehrerProps.ts";
export type { StundenplanRaumProps } from "./components/stundenplan/StundenplanRaumProps.ts";
export type { StundenplanSchuelerProps } from "./components/stundenplan/StundenplanSchuelerProps.ts";
export { default as AbschnittAuswahl } from "./components/abschnittauswahl/AbschnittAuswahl.vue";
export { default as DatenschutzModal } from "./components/modals/DatenschutzModal.vue";
export { default as FehlermeldungModal } from "./components/modals/FehlermeldungModal.vue";
export { default as LogBox } from "./components/logbox/LogBox.vue";
export { default as SLaufbahnplanungCardBeratung } from "./components/gost/laufbahnplanung/SLaufbahnplanungCardBeratung.vue";
export { default as SLaufbahnplanungCardPlanung } from "./components/gost/laufbahnplanung/SLaufbahnplanungCardPlanung.vue";
export { default as SLaufbahnplanungCardStatus } from "./components/gost/laufbahnplanung/SLaufbahnplanungCardStatus.vue";
export { default as SLaufbahnplanungFach } from "./components/gost/laufbahnplanung/SLaufbahnplanungFach.vue";
export { default as SLaufbahnplanungFachkombinationen } from "./components/gost/laufbahnplanung/SLaufbahnplanungFachkombinationen.vue";
export { default as SLaufbahnplanungFehler } from "./components/gost/laufbahnplanung/SLaufbahnplanungFehler.vue";
export { default as SLaufbahnplanungImportModal } from "./components/gost/laufbahnplanung/SLaufbahnplanungImportModal.vue";
export { default as SLaufbahnplanungInformationen } from "./components/gost/laufbahnplanung/SLaufbahnplanungInformationen.vue";
export { default as SLaufbahnplanungSprachpruefungen } from "./components/gost/laufbahnplanung/SLaufbahnplanungSprachpruefungen.vue";
export { default as SModalLaufbahnplanungAlleFachwahlenLoeschen } from "./components/gost/laufbahnplanung/SModalLaufbahnplanungAlleFachwahlenLoeschen.vue";
export { default as SModalLaufbahnplanungKurswahlenLoeschen } from "./components/gost/laufbahnplanung/SModalLaufbahnplanungKurswahlenLoeschen.vue";
export { default as SSchuelerLaufbahnplanung } from "./components/gost/laufbahnplanung/SSchuelerLaufbahnplanung.vue";
export { default as StundenplanAnsicht } from "./components/stundenplan/StundenplanAnsicht.vue";
export { default as StundenplanAnsichtPausenaufsichten } from "./components/stundenplan/StundenplanAnsichtPausenaufsichten.vue";
export { default as StundenplanAnsichtPlanung } from "./components/stundenplan/StundenplanAnsichtPlanung.vue";
export { default as StundenplanAuswahl } from "./components/stundenplan/StundenplanAuswahl.vue";
export { default as StundenplanFach } from "./components/stundenplan/StundenplanFach.vue";
export { default as StundenplanKlassen } from "./components/stundenplan/StundenplanKlassen.vue";
export { default as StundenplanLehrer } from "./components/stundenplan/StundenplanLehrer.vue";
export { default as StundenplanRaum } from "./components/stundenplan/StundenplanRaum.vue";
export { default as StundenplanSchueler } from "./components/stundenplan/StundenplanSchueler.vue";
export { default as StundenplanZeitrasterEinstellungen } from "./components/stundenplan/StundenplanZeitrasterEinstellungen.vue";
export { default as StundenplanZeitrasterJsonImportModal } from "./components/stundenplan/StundenplanZeitrasterJsonImportModal.vue";
export { default as EnmLeistungen } from "./components/enm/EnmLeistungen.vue";
export { default as EnmLeistungenAuswahl } from "./components/enm/EnmLeistungenAuswahl.vue";
export { default as EnmKlassenleitung } from "./components/enm/EnmKlassenleitung.vue";
export { default as EnmKlassenleitungAuswahl } from "./components/enm/EnmKlassenleitungAuswahl.vue";
export { default as EnmTeilleistungen } from "./components/enm/EnmTeilleistungen.vue";
export { default as EnmTeilleistungenAuswahl } from "./components/enm/EnmTeilleistungenAuswahl.vue";
export { default as SvwsUiAppLayout } from "./ui/layout/SvwsUiAppLayout.vue";
export { default as SvwsUiAvatar } from "./ui/SvwsUiAvatar.vue";
export { default as SvwsUiBadge } from "./ui/SvwsUiBadge.vue";
export { default as SvwsUiButton } from "./ui/controls/SvwsUiButton.vue";
export { default as SvwsUiButtonSelect } from "./ui/controls/SvwsUiButtonSelect.vue";
export { default as UiCard } from "./ui/layout/UiCard.vue";
export { default as SvwsUiCheckbox } from "./ui/controls/SvwsUiCheckbox.vue";
export { default as SvwsUiCheckpointModal } from "./ui/modal/SvwsUiCheckpointModal.vue";
export { default as SvwsUiContentCard } from "./ui/layout/SvwsUiContentCard.vue";
export { default as SvwsUiDashboardTile } from "./ui/layout/SvwsUiDashboardTile.vue";
export { default as SvwsUiDropdownList } from "./ui/controls/SvwsUiDropdownList.vue";
export { default as SvwsUiHeader } from "./ui/layout/SvwsUiHeader.vue";
export { default as SvwsUiInputNumber } from "./ui/controls/SvwsUiInputNumber.vue";
export { default as SvwsUiInputWrapper } from "./ui/layout/SvwsUiInputWrapper.vue";
export { default as SvwsUiMenu } from "./ui/nav/SvwsUiMenu.vue";
export { default as SvwsUiMenuHeader } from "./ui/nav/SvwsUiMenuHeader.vue";
export { default as SvwsUiMenuItem } from "./ui/nav/SvwsUiMenuItem.vue";
export { default as SvwsUiModal } from "./ui/modal/SvwsUiModal.vue";
export { default as SvwsUiModalHilfe } from "./ui/modal/SvwsUiModalHilfe.vue";
export { default as SvwsUiMultiSelect } from "./ui/controls/SvwsUiMultiSelect.vue";
export { default as SvwsUiNotification } from "./ui/SvwsUiNotification.vue";
export { default as SvwsUiNotifications } from "./ui/SvwsUiNotifications.vue";
export { default as SvwsUiRadioGroup } from "./ui/controls/SvwsUiRadioGroup.vue";
export { default as SvwsUiRadioOption } from "./ui/controls/SvwsUiRadioOption.vue";
export { default as SvwsUiSecondaryMenuNavigation } from "./ui/nav/SvwsUiSecondaryMenuNavigation.vue";
export { default as SvwsUiSelect } from "./ui/controls/SvwsUiSelect.vue";
export { default as UiSelect } from "./ui/controls/select/UiSelect.vue";
export { default as UiSelectMulti } from "./ui/controls/select/UiSelectMulti.vue";
export { default as SvwsUiSpacing } from "./ui/layout/SvwsUiSpacing.vue";
export { default as SvwsUiSpinner } from "./ui/SvwsUiSpinner.vue";
export { default as SvwsUiSubNav } from "./ui/nav/SvwsUiSubNav.vue";
export { default as SvwsUiTabBar } from "./ui/nav/SvwsUiTabBar.vue";
export { default as SvwsUiTabBarVertical } from "./ui/nav/SvwsUiTabBarVertical.vue";
export { default as SvwsUiTable } from "./ui/layout/SvwsUiTable.vue";
export { default as SvwsUiTextareaInput } from "./ui/controls/SvwsUiTextareaInput.vue";
export { default as SvwsUiTextInput } from "./ui/controls/SvwsUiTextInput.vue";
export { default as SvwsUiTodo } from "./ui/SvwsUiTodo.vue";
export { default as SvwsUiToggle } from "./ui/controls/SvwsUiToggle.vue";
export { default as SvwsUiTooltip } from "./ui/SvwsUiTooltip.vue";

// Use exports
export { useRegionSwitch } from "./ui/composables/useRegionSwitch";
export { usePaneSplitter } from "./ui/composables/usePaneSplitter";

// Type exorts
export type { DataTableColumn, SortByAndOrder } from "./types";
export type { TabData } from "./ui/nav/TabData";

// Class exports
export { Config, type ConfigSetter, ConfigElement } from "./utils/Config";
export { AppMenuManager } from "./ui/nav/AppMenuManager";
export { TabManager } from "./ui/nav/TabManager";
export { Checkpoint } from "./ui/modal/Checkpoint";
export { Color } from "./ui/Color";
export { LaufbahnplanungUiManager } from "./components/gost/laufbahnplanung/LaufbahnplanungUiManager";
export { SelectManager } from "./ui/controls/select/selectManager/SelectManager";
export { CoreTypeSelectManager } from "./ui/controls/select/selectManager/CoreTypeSelectManager";
export { GridManager } from "./ui/controls/tablegrid/GridManager";
export { GridInput } from "./ui/controls/tablegrid/GridInput";
export { GridInputInnerText } from "./ui/controls/tablegrid/GridInputInnerText";
export { GridInputAbiturNotenpunkte } from "./ui/controls/tablegrid/GridInputAbiturNotenpunkte";
export { GridInputAbiturPruefungsreihenfolge } from "./ui/controls/tablegrid/GridInputAbiturPruefungsreihenfolge";
export { GridInputToggle } from "./ui/controls/tablegrid/GridInputToggle";
export { PendingStateManager } from "./ui/wrapper/PendingStateManager";
export { StateManager } from "./ui/StateManager";
export { EnmManager } from "./components/enm/EnmManager";
export { EnmLerngruppenAuswahlListeManager } from "./components/enm/EnmLerngruppenAuswahlListeManager";
export { EnmKlassenleitungAuswahlListeManager } from "./components/enm/EnmKlassenleitungAuswahlListeManager";
export type { EnmLerngruppenAuswahlEintrag } from "./components/enm/EnmManager";
export type { EnmLeistungenProps } from "./components/enm/EnmLeistungenProps";
export type { EnmLeistungenAuswahlProps } from "./components/enm/EnmLeistungenAuswahlProps";
export type { EnmTeilleistungenProps } from "./components/enm/EnmTeilleistungenProps";
export type { EnmKlassenleitungProps } from "./components/enm/EnmKlassenleitungProps";

// Enums
export { AppMenuGroup } from "./ui/nav/AppMenuGroup";
export { ViewType } from "./ui/nav/ViewType";

// Managers
export { AuswahlManager } from "./ui/AuswahlManager";
export { TelefonArtListeManager } from "./ui/managers/telefonart/TelefonArtListeManager";
export { StundenplanListeManager } from "./ui/managers/stundenplan/StundenplanListeManager";
export { StundenplanUnterrichtListeManager } from "./ui/managers/stundenplan/StundenplanUnterrichtListeManager";
export { KatalogSchuleListeManager } from "./ui/managers/schule/KatalogSchuleListeManager";
export { SchuelerListeManager } from "./ui/managers/schueler/SchuelerListeManager";
export { SchuelerKAoAManager } from "./ui/managers/schueler/SchuelerKAoAManager";
export { ReligionenListeManager } from "./ui/managers/kataloge/religionen/ReligionenListeManager";
export { RaumListeManager } from "./ui/managers/raum/RaumListeManager";
export { LernplattformListeManager } from "./ui/managers/lernplattform/LernplattformListeManager";
export { LehrerListeManager } from "./ui/managers/lehrer/LehrerListeManager";
export { KursListeManager } from "./ui/managers/kurse/KursListeManager";
export { KlassenListeManager } from "./ui/managers/klassen/KlassenListeManager";
export { AbteilungenListeManager } from './ui/managers/kataloge/abteilungen/AbteilungenListeManager';
export { BeschaeftigungsartenListeManager } from './ui/managers/kataloge/beschaeftigungsarten/BeschaeftigungsartenListeManager';
export { EntlassgruendeListeManager } from './ui/managers/kataloge/entlassgruende/EntlassgruendeListeManager';
export { FahrschuelerartenListeManager } from './ui/managers/kataloge/fahrschuelerarten/FahrschuelerartenListeManager';
export { FoerderschwerpunkteListeManager } from './ui/managers/kataloge/foerderschwerpunkte/FoerderschwerpunkteListeManager';
export { HaltestellenListeManager } from './ui/managers/kataloge/haltestellen/HaltestellenListeManager';
export { JahrgaengeListeManager } from './ui/managers/kataloge/jahrgaenge/JahrgaengeListeManager';
export { KindergaertenListeManager } from './ui/managers/kataloge/kindergaerten/KindergaertenListeManager';
export { MerkmaleListeManager } from './ui/managers/kataloge/merkmale/MerkmaleListeManager';
export { SportbefreiungenListeManager } from './ui/managers/kataloge/sportbefreiungen/SportbefreiungenListeManager';
export { VermerkartenListeManager } from './ui/managers/kataloge/vermerkart/VermerkartenListeManager';
export { FachListeManager } from './ui/managers/fach/FachListeManager';
export { ErzieherartListeManager } from './ui/managers/erzieherart/ErzieherartListeManager';
export { EinwilligungsartenListeManager } from './ui/managers/einwilligungsart/EinwilligungsartenListeManager';
