package de.nrw.schule.svws.transpiler;

import java.util.List;
import java.util.Vector;

/**
 * The abstract super class of language plugins for the {@link Transpiler}. 
 */
public abstract class TranspilerLanguagePlugin {

	/** The internal reference to the transpiler using this language plugin */
	protected final Transpiler transpiler;
	
	/** a vector containing all the relative file names generated by this plugin */
	protected final Vector<String> outputFiles = new Vector<>();
	
	/**
	 * This constructor is invoked on creating an new language plugin for the 
	 * specified transpiler. The plugin is autmatically registered at the transpiler.
	 * 
	 * @param transpiler   the transpiler using this plugin instance
	 */
	protected TranspilerLanguagePlugin(Transpiler transpiler) {
		if (transpiler == null)
			throw new TranspilerException("Transpiler Error: A transpiler using the transpiler language plugin is required.");
		this.transpiler = transpiler;
		this.transpiler.addLanguagePlugin(this);
	}


	/**
	 * Returns the transpiler associated with this plugin
	 * 
	 * @return the transpiler object used by this plugin
	 */
	public Transpiler getTranspiler() {
		return this.transpiler;
	}
	

	/**
	 * This method is invoked by the transpiler to start the transpiling process
	 * for this language plugin. It must be implemented by the language plugin.
	 */
	public abstract void transpile();


	/**
	 * Returns a list containing all the relative file names generated by this plugin.
	 * 
	 * @return the filename list 
	 */
	public List<String> getOutputFiles() {
		return this.outputFiles;
	}
}
