import plugin from 'tailwindcss/plugin';

/**
 * Icons - Beispiel zur Verwendung in den vue-Dateien:
 *
 * <span class="icon icon-white i-ri-alert-line"/>
 */

const iconSize = {
	'xxs': '0.5rem',
	'xs': '0.75rem',
	'sm': '1rem',
	DEFAULT: '1.2rem',
	'lg': '1.5rem',
	'xl': '2rem',
	'xxl': '4rem',
}

const iconColors = {
	'white': 'invert(95%) sepia(100%) saturate(14%) hue-rotate(213deg) brightness(104%) contrast(104%);',
	'gray': 'invert(32%) sepia(97%) saturate(0%) hue-rotate(163deg) brightness(103%) contrast(104%);',
	'primary': 'invert(44%) sepia(52%) saturate(1260%) hue-rotate(173deg) brightness(91%) contrast(86%);',
	'light': 'invert(91%) sepia(3%) saturate(126%) hue-rotate(7deg) brightness(108%) contrast(94%);',
	'dark-20': 'invert(87%) sepia(7%) saturate(231%) hue-rotate(163deg) brightness(97%) contrast(87%);',
	'dark': 'invert(23%) sepia(18%) saturate(978%) hue-rotate(158deg) brightness(96%) contrast(91%);',
	'error': 'invert(22%) sepia(96%) saturate(2323%) hue-rotate(331deg) brightness(88%) contrast(103%);',
	'danger': 'invert(22%) sepia(96%) saturate(2323%) hue-rotate(331deg) brightness(88%) contrast(103%);',
	'warning': 'brightness(0) saturate(100%) invert(75%) sepia(17%) saturate(7311%) hue-rotate(11deg) brightness(97%) contrast(94%);',
	'caution': 'brightness(0) saturate(100%) invert(51%) sepia(100%) saturate(2298%) hue-rotate(355deg) brightness(101%) contrast(101%);',
	'success': 'invert(86%) sepia(40%) saturate(5221%) hue-rotate(37deg) brightness(101%) contrast(83%);',
	'highlight': 'invert(88%) sepia(25%) saturate(695%) hue-rotate(346deg) brightness(107%) contrast(106%);',
	'statistics': 'brightness(0) saturate(100%) invert(37%) sepia(71%) saturate(868%) hue-rotate(224deg) brightness(103%) contrast(93%);',
};

const iconPath = {
	'add-line': { path: 'System', icon: 'add-line' },
	'alert-fill': { path: 'System', icon: 'alert-fill' },
	'alert-line': { path: 'System', icon: 'alert-line' },
	'archive-line': { path: 'Business', icon: 'archive-line' },
	'archive-stack-line': { path: 'Business', icon: 'archive-stack-line' },
	'arrow-down-line': { path: 'Arrows', icon: 'arrow-down-line' },
	'arrow-down-s-line': { path: 'Arrows', icon: 'arrow-down-s-line' },
	'arrow-go-back-line': { path: 'Arrows', icon: 'arrow-go-back-line' },
	'arrow-left-s-line': { path: 'Arrows', icon: 'arrow-left-s-line' },
	'arrow-right-circle-line': { path: 'Arrows', icon: 'arrow-right-circle-line' },
	'arrow-right-s-line': { path: 'Arrows', icon: 'arrow-right-s-line' },
	'arrow-turn-back-line': { path: 'Arrows', icon: 'arrow-turn-back-line' },
	'arrow-up-down-line': { path: 'Arrows', icon: 'arrow-up-down-line' },
	'arrow-up-line': { path: 'Arrows', icon: 'arrow-up-line' },
	'arrow-up-s-line': { path: 'Arrows', icon: 'arrow-up-s-line' },
	'at-line': { path: 'Business', icon: 'at-line' },
	'bar-chart-2-line': { path: 'Business', icon: 'bar-chart-2-line' },
	'book-2-line': { path: 'Document', icon: 'book-2-line' },
	'box-3-line': { path: 'Others', icon: 'box-3-line' },
	'briefcase-line': { path: 'Business', icon: 'briefcase-line' },
	'bug-fill': { path: 'Development', icon: 'bug-fill' },
	'calculator-line': { path: 'Business', icon: 'calculator-line' },
	'calendar-2-line': { path: 'Business', icon: 'calendar-2-line' },
	'calendar-event-line': { path: 'Business', icon: 'calendar-event-line' },
	'camera-fill': { path: 'Media', icon: 'camera-fill' },
	'camera-line': { path: 'Media', icon: 'camera-line' },
	'camera-off-line': { path: 'Media', icon: 'camera-off-line' },
	'chat-1-line': { path: 'Communication', icon: 'chat-1-line' },
	'check-line': { path: 'System', icon: 'check-line' },
	'checkbox-blank-circle-line': { path: 'System', icon: 'checkbox-blank-circle-line' },
	'checkbox-circle-fill': { path: 'System', icon: 'checkbox-circle-fill' },
	'checkbox-circle-line': { path: 'System', icon: 'checkbox-circle-line' },
	'close-line': { path: 'System', icon: 'close-line' },
	'corner-right-up-line': { path: 'Arrows', icon: 'corner-right-up-line' },
	'cup-line': { path: 'Food', icon: 'cup-line' },
	'database-2-line': { path: 'Device', icon: 'database-2-line' },
	'delete-bin-fill': { path: 'System', icon: 'delete-bin-fill' },
	'delete-bin-line': { path: 'System', icon: 'delete-bin-line' },
	'device-recover-line': { path: 'Device', icon: 'device-recover-line' },
	'download-2-line': { path: 'System', icon: 'download-2-line' },
	'draft-line': { path: 'Document', icon: 'draft-line' },
	'draggable': { path: 'Editor', icon: 'draggable' },
	'edit-2-line': { path: 'Design', icon: 'edit-2-line' },
	'eraser-fill': { path: 'Design', icon: 'eraser-fill' },
	'eraser-line': { path: 'Design', icon: 'eraser-line' },
	'error-warning-fill': { path: 'System', icon: 'error-warning-fill' },
	'error-warning-line': { path: 'System', icon: 'error-warning-line' },
	'expand-height-line': { path: 'Arrows', icon: 'expand-height-line' },
	'expand-up-down-fill': { path: 'Arrows', icon: 'expand-up-down-fill' },
	'expand-up-down-line': { path: 'Arrows', icon: 'expand-up-down-line' },
	'eye-line': { path: 'System', icon: 'eye-line' },
	'file-close-line': { path: 'Document', icon: 'file-close-line' },
	'file-copy-line': { path: 'Document', icon: 'file-copy-line' },
	'file-damage-line': { path: 'Document', icon: 'file-damage-line' },
	'filter-fill': { path: 'System', icon: 'filter-fill' },
	'filter-line': { path: 'System', icon: 'filter-line' },
	'filter-off-line': { path: 'System', icon: 'filter-off-line' },
	'folder-open-line': { path: 'Document', icon: 'folder-open-line' },
	'forbid-fill': { path: 'System', icon: 'forbid-fill' },
	'forbid-line': { path: 'System', icon: 'forbid-line' },
	'fullscreen-line': { path: 'Media', icon: 'fullscreen-line' },
	'graduation-cap-line': { path: 'Others', icon: 'graduation-cap-line' },
	'group-line': { path: 'User%20&%20Faces', icon: 'group-line' },
	'headphone-line': { path: 'Media', icon: 'headphone-line' },
	'information-fill': { path: 'System', icon: 'information-fill' },
	'information-line': { path: 'System', icon: 'information-line' },
	'lightbulb-line': { path: 'Others', icon: 'lightbulb-line' },
	'link': { path: 'Editor', icon: 'link' },
	'loader-4-line': { path: 'System', icon: 'loader-4-line' },
	'lock-2-line': { path: 'System', icon: 'lock-2-line' },
	'lock-fill': { path: 'System', icon: 'lock-fill' },
	'lock-line': { path: 'System', icon: 'lock-line' },
	'lock-unlock-line': { path: 'System', icon: 'lock-unlock-line' },
	'login-circle-line': { path: 'System', icon: 'login-circle-line' },
	'logout-circle-line': { path: 'System', icon: 'logout-circle-line' },
	'loop-left-line': { path: 'System', icon: 'loop-left-line' },
	'loop-right-line': { path: 'System', icon: 'loop-right-line' },
	'mail-send-line': { path: 'Business', icon: 'mail-send-line' },
	'menu-fold-line': { path: 'System', icon: 'menu-fold-line' },
	'menu-line': { path: 'System', icon: 'menu-line' },
	'menu-unfold-line': { path: 'System', icon: 'menu-unfold-line' },
	'moon-line': { path: 'Weather', icon: 'moon-line' },
	'palette-line': { path: 'Design', icon: 'palette-line' },
	'phone-line': { path: 'Device', icon: 'phone-line' },
	'presentation-line': { path: 'Business', icon: 'presentation-line' },
	'printer-line': { path: 'Business', icon: 'printer-line' },
	'prohibited-fill': { path: 'System', icon: 'prohibited-fill' },
	'prohibited-line': { path: 'System', icon: 'prohibited-line' },
	'pushpin-fill': { path: 'Map', icon: 'pushpin-fill' },
	'pushpin-line': { path: 'Map', icon: 'pushpin-line' },
	'question-line': { path: 'System', icon: 'question-line' },
	'question-fill': { path: 'System', icon: 'question-fill' },
	'refresh-line': { path: 'System', icon: 'refresh-line' },
	'restart-line': { path: 'Device', icon: 'restart-line' },
	'save-3-line': { path: 'Device', icon: 'save-3-line' },
	'school-line': { path: 'Buildings', icon: 'school-line' },
	'search-line': { path: 'System', icon: 'search-line' },
	'send-plane-fill': { path: 'Business', icon: 'send-plane-fill' },
	'settings-2-line': { path: 'System', icon: 'settings-2-line' },
	'settings-3-line': { path: 'System', icon: 'settings-3-line' },
	'share-forward-2-line': { path: 'System', icon: 'share-forward-2-line' },
	'share-forward-line': { path: 'System', icon: 'share-forward-line' },
	'shield-star-line': { path: 'System', icon: 'shield-star-line' },
	'spam-3-line': { path: 'System', icon: 'spam-3-line' },
	'sparkling-line': { path: 'Weather', icon: 'sparkling-line' },
	'speak-line': { path: 'Communication', icon: 'speak-line' },
	'speed-line': { path: 'Media', icon: 'speed-line' },
	'subtract-line': { path: 'System', icon: 'subtract-line' },
	'sun-line': { path: 'Weather', icon: 'sun-line' },
	'table-line': { path: 'Design', icon: 'table-line' },
	'team-line': { path: 'User%20&%20Faces', icon: 'team-line' },
	'text': { path: 'Editor', icon: 'text' },
	'time-line': { path: 'System', icon: 'time-line' },
	'upload-2-line': { path: 'System', icon: 'upload-2-line' },
	'user-add-line': { path: 'User%20&%20Faces', icon: 'user-add-line' },
	'user-forbid-line': { path: 'User%20&%20Faces', icon: 'user-forbid-line' },
	'vidicon-line': { path: 'Media', icon: 'vidicon-line' },
	'zoom-in-line': { path: 'System', icon: 'zoom-in-line' },
	'zoom-out-line': { path: 'System', icon: 'zoom-out-line' },
	'play-line': { path: 'Media', icon: 'play-line' },
	'message-line': { path: 'Communication', icon: 'message-line' },
	'chat-new-line': { path: 'Communication', icon: 'chat-new-line' },
	'question-mark': { path: 'Editor', icon: 'question-mark' },
}

const iconPlugins = [
	// eslint-disable-next-line @typescript-eslint/unbound-method
	plugin(function({ matchUtilities, theme }) {
		matchUtilities({
			'i-ri': (value) => ({
				'background-image': `url(remixicon/icons/${value.path}/${value.icon}.svg)`,
				'background-repeat': 'no-repeat',
				'background-position': 'center',
			}),
		}, { values: theme('iconPath') })
	}),
	// eslint-disable-next-line @typescript-eslint/unbound-method
	plugin(function({ matchUtilities, theme }) {
		matchUtilities({
			'icon': (value) => ({
				'-webkit-filter': value,
				'filter': value,
			}),
		}, { values: theme('iconColors') })
	}),
	// eslint-disable-next-line @typescript-eslint/unbound-method
	plugin(function({ matchUtilities, theme }) {
		matchUtilities({
			'icon': (value) => ({
				'width': value,
				'height': value,
				'line-height': value,
			}),
		}, { values: theme('iconSize') })
	}),
];

export { iconSize, iconColors, iconPath, iconPlugins };
