import { palette } from "./tailwind.colors.palette";

/**
 * @param {string} cssVar
 * @returns {({opacityValue}: {opacityValue: string}) => string}
 */
function withOpacity(cssVar) {
	return ({ opacityValue }) => {
		if (opacityValue !== '') {
			return `rgba(var(${cssVar}), ${opacityValue})`;
		}
		return `rgb(var(${cssVar}))`;
	};
}

const colors = {
	transparent: "transparent",
	current: "currentColor",
	'svws': {
		'50': '#f1f7fe',
		'100': '#e3eefb',
		'200': '#c0dcf7',
		'300': '#88c0f1',
		'400': '#4ba1e7',
		'500': '#2285d5',
		DEFAULT: '#2285d5',
		'600': '#1467b5',
		'700': '#115393',
		'800': '#12477a',
		'900': '#153d65',
		'950': '#0e2743',
		'smoke': '#F6F5F4',
		'ash': '#B8CCC4',
		'olive': '#2B3B36',
		'night': '#141414',
	},
	white: withOpacity("--color-white"),
	black: withOpacity("--color-black"),
	gray: withOpacity("--color-gray"),
	primary: withOpacity("--color-primary"),
	light: withOpacity("--color-light"),
	"dark-20": withOpacity("--color-dark-20"),
	dark: withOpacity("--color-dark"),
	error: withOpacity("--color-error"),
	success: withOpacity("--color-success"),
	highlight: withOpacity("--color-highlight"),
	statistics: withOpacity("--color-statistics"),
	'palette': palette,
}

const backgroundColor = {
	'ui': {
		DEFAULT: 'var(--color-bg-ui)',
		'hover': 'var(--color-bg-ui-hover)',
		'brand': 'var(--color-bg-ui-brand)',
		'brand-hover': 'var(--color-bg-ui-brand-hover)',
		'brand-weak': 'var(--color-bg-ui-brand-weak)',
		'statistic': 'var(--color-bg-ui-statistic)',
		'statistic-hover': 'var(--color-bg-ui-statistic-hover)',
		'statistic-weak': 'var(--color-bg-ui-statistic-weak)',
		'selected': 'var(--color-bg-ui-selected)',
		'selected-hover': 'var(--color-bg-ui-selected-hover)',
		'danger': 'var(--color-bg-ui-danger)',
		'danger-hover': 'var(--color-bg-ui-danger-hover)',
		'danger-weak': 'var(--color-bg-ui-danger-weak)',
		'success': 'var(--color-bg-ui-success)',
		'success-hover': 'var(--color-bg-ui-success-hover)',
		'success-weak': 'var(--color-bg-ui-success-weak)',
		'warning': 'var(--color-bg-ui-warning)',
		'warning-hover': 'var(--color-bg-ui-warning-hover)',
		'warning-weak': 'var(--color-bg-ui-warning-weak)',
		'caution': 'var(--color-bg-ui-caution)',
		'caution-hover': 'var(--color-bg-ui-caution-hover)',
		'caution-weak': 'var(--color-bg-ui-caution-weak)',
		'neutral': 'var(--color-bg-ui-neutral)',
		'neutral-hover': 'var(--color-bg-ui-neutral-hover)',
		'neutral-weak': 'var(--color-bg-ui-neutral-weak)',
		'disabled': 'var(--color-bg-ui-disabled)',
		'inverted': 'var(--color-bg-ui-inverted)',
		'white': 'var(--color-bg-ui-white)',
		'black': 'var(--color-bg-ui-black)',
	},
}

const textColor = {
	'ui': {
		DEFAULT: 'var(--color-text-ui)',
		'hover': 'var(--color-text-ui-hover)',
		'secondary': 'var(--color-text-ui-secondary)',
		'secondary-hover': 'var(--color-text-ui-secondary-hover)',
		'brand': 'var(--color-text-ui-brand)',
		'brand-hover': 'var(--color-text-ui-brand-hover)',
		'brand-secondary': 'var(--color-text-ui-brand-secondary)',
		'brand-secondary-hover': 'var(--color-text-ui-brand-secondary-hover)',
		'statistic': 'var(--color-text-ui-statistic)',
		'statistic-hover': 'var(--color-text-ui-statistic-hover)',
		'statistic-secondary': 'var(--color-text-ui-statistic-secondary)',
		'statistic-secondary-hover': 'var(--color-text-ui-statistic-secondary-hover)',
		'selected': 'var(--color-text-ui-selected)',
		'selected-hover': 'var(--color-text-ui-selected-hover)',
		'selected-secondary': 'var(--color-text-ui-selected-secondary)',
		'selected-secondary-hover': 'var(--color-text-ui-selected-secondary-hover)',
		'danger': 'var(--color-text-ui-danger)',
		'danger-hover': 'var(--color-text-ui-danger-hover)',
		'danger-secondary': 'var(--color-text-ui-danger-secondary)',
		'danger-secondary-hover': 'var(--color-text-ui-danger-secondary-hover)',
		'success': 'var(--color-text-ui-success)',
		'success-hover': 'var(--color-text-ui-success-hover)',
		'success-secondary': 'var(--color-text-ui-success-secondary)',
		'success-secondary-hover': 'var(--color-text-ui-success-secondary-hover)',
		'warning': 'var(--color-text-ui-warning)',
		'warning-hover': 'var(--color-text-ui-warning-hover)',
		'warning-secondary': 'var(--color-text-ui-warning-secondary)',
		'warning-secondary-hover': 'var(--color-text-ui-warning-secondary-hover)',
		'caution': 'var(--color-text-ui-caution)',
		'caution-hover': 'var(--color-text-ui-caution-hover)',
		'caution-secondary': 'var(--color-text-ui-caution-secondary)',
		'caution-secondary-hover': 'var(--color-text-ui-caution-secondary-hover)',
		'neutral': 'var(--color-text-ui-neutral)',
		'neutral-hover': 'var(--color-text-ui-neutral-hover)',
		'neutral-secondary': 'var(--color-text-ui-neutral-secondary)',
		'neutral-secondary-hover': 'var(--color-text-ui-neutral-secondary-hover)',
		'disabled': 'var(--color-text-ui-disabled)',
		'disabled-secondary': 'var(--color-text-ui-disabled-secondary)',
		'onbrand': 'var(--color-text-ui-onbrand)',
		'onbrand-hover': 'var(--color-text-ui-onbrand-hover)',
		'onbrand-secondary': 'var(--color-text-ui-onbrand-secondary)',
		'onbrand-secondary-hover': 'var(--color-text-ui-onbrand-secondary-hover)',
		'onstatistic': 'var(--color-text-ui-onstatistic)',
		'onstatistic-hover': 'var(--color-text-ui-onstatistic-hover)',
		'onstatistic-secondary': 'var(--color-text-ui-onstatistic-secondary)',
		'onstatistic-secondary-hover': 'var(--color-text-ui-onstatistic-secondary-hover)',
		'onselected': 'var(--color-text-ui-onselected)',
		'onselected-hover': 'var(--color-text-ui-onselected-hover)',
		'onselected-secondary': 'var(--color-text-ui-onselected-secondary)',
		'onselected-secondary-hover': 'var(--color-text-ui-onselected-secondary-hover)',
		'ondanger': 'var(--color-text-ui-ondanger)',
		'ondanger-hover': 'var(--color-text-ui-ondanger-hover)',
		'ondanger-secondary': 'var(--color-text-ui-ondanger-secondary)',
		'ondanger-secondary-hover': 'var(--color-text-ui-ondanger-secondary-hover)',
		'onsuccess': 'var(--color-text-ui-onsuccess)',
		'onsuccess-hover': 'var(--color-text-ui-onsuccess-hover)',
		'onsuccess-secondary': 'var(--color-text-ui-onsuccess-secondary)',
		'onsuccess-secondary-hover': 'var(--color-text-ui-onsuccess-secondary-hover)',
		'onwarning': 'var(--color-text-ui-onwarning)',
		'onwarning-hover': 'var(--color-text-ui-onwarning-hover)',
		'onwarning-secondary': 'var(--color-text-ui-onwarning-secondary)',
		'onwarning-secondary-hover': 'var(--color-text-ui-onwarning-secondary-hover)',
		'oncaution': 'var(--color-text-ui-oncaution)',
		'oncaution-hover': 'var(--color-text-ui-oncaution-hover)',
		'oncaution-secondary': 'var(--color-text-ui-oncaution-secondary)',
		'oncaution-secondary-hover': 'var(--color-text-ui-oncaution-secondary-hover)',
		'onneutral': 'var(--color-text-ui-onneutral)',
		'onneutral-hover': 'var(--color-text-ui-onneutral-hover)',
		'onneutral-secondary': 'var(--color-text-ui-onneutral-secondary)',
		'onneutral-secondary-hover': 'var(--color-text-ui-onneutral-secondary-hover)',
		'ondisabled': 'var(--color-text-ui-ondisabled)',
		'ondisabled-secondary': 'var(--color-text-ui-ondisabled-secondary)',
		'white': 'var(--color-bg-ui-white)',
		'black': 'var(--color-bg-ui-black)',
	},
}

const borderColor = {
	'ui': {
		DEFAULT: 'var(--color-border-ui)',
		'hover': 'var(--color-border-ui-hover)',
		'secondary': 'var(--color-border-ui-secondary)',
		'secondary-hover': 'var(--color-border-ui-secondary-hover)',
		'brand': 'var(--color-border-ui-brand)',
		'brand-hover': 'var(--color-border-ui-brand-hover)',
		'brand-secondary': 'var(--color-border-ui-brand-secondary)',
		'brand-secondary-hover': 'var(--color-border-ui-brand-secondary-hover)',
		'statistic': 'var(--color-border-ui-statistic)',
		'statistic-hover': 'var(--color-border-ui-statistic-hover)',
		'statistic-secondary': 'var(--color-border-ui-statistic-secondary)',
		'statistic-secondary-hover': 'var(--color-border-ui-statistic-secondary-hover)',
		'selected': 'var(--color-border-ui-selected)',
		'selected-hover': 'var(--color-border-ui-selected-hover)',
		'selected-secondary': 'var(--color-border-ui-selected-secondary)',
		'selected-secondary-hover': 'var(--color-border-ui-selected-secondary-hover)',
		'danger': 'var(--color-border-ui-danger)',
		'danger-hover': 'var(--color-border-ui-danger-hover)',
		'danger-secondary': 'var(--color-border-ui-danger-secondary)',
		'danger-secondary-hover': 'var(--color-border-ui-danger-secondary-hover)',
		'success': 'var(--color-border-ui-success)',
		'success-hover': 'var(--color-border-ui-success-hover)',
		'success-secondary': 'var(--color-border-ui-success-secondary)',
		'success-secondary-hover': 'var(--color-border-ui-success-secondary-hover)',
		'warning': 'var(--color-border-ui-warning)',
		'warning-hover': 'var(--color-border-ui-warning-hover)',
		'warning-secondary': 'var(--color-border-ui-warning-secondary)',
		'warning-secondary-hover': 'var(--color-border-ui-warning-secondary-hover)',
		'caution': 'var(--color-border-ui-caution)',
		'caution-hover': 'var(--color-border-ui-caution-hover)',
		'caution-secondary': 'var(--color-border-ui-caution-secondary)',
		'caution-secondary-hover': 'var(--color-border-ui-caution-secondary-hover)',
		'neutral': 'var(--color-border-ui-neutral)',
		'neutral-hover': 'var(--color-border-ui-neutral-hover)',
		'neutral-secondary': 'var(--color-border-ui-neutral-secondary)',
		'neutral-secondary-hover': 'var(--color-border-ui-neutral-secondary-hover)',
		'disabled': 'var(--color-border-ui-disabled)',
		'disabled-secondary': 'var(--color-border-ui-disabled-secondary)',
		'onbrand': 'var(--color-border-ui-onbrand)',
		'onbrand-hover': 'var(--color-border-ui-onbrand-hover)',
		'onbrand-secondary': 'var(--color-border-ui-onbrand-secondary)',
		'onbrand-secondary-hover': 'var(--color-border-ui-onbrand-secondary-hover)',
		'onstatistic': 'var(--color-border-ui-onstatistic)',
		'onstatistic-hover': 'var(--color-border-ui-onstatistic-hover)',
		'onstatistic-secondary': 'var(--color-border-ui-onstatistic-secondary)',
		'onstatistic-secondary-hover': 'var(--color-border-ui-onstatistic-secondary-hover)',
		'onselected': 'var(--color-border-ui-onselected)',
		'onselected-hover': 'var(--color-border-ui-onselected-hover)',
		'onselected-secondary': 'var(--color-border-ui-onselected-secondary)',
		'onselected-secondary-hover': 'var(--color-border-ui-onselected-secondary-hover)',
		'ondanger': 'var(--color-border-ui-ondanger)',
		'ondanger-hover': 'var(--color-border-ui-ondanger-hover)',
		'ondanger-secondary': 'var(--color-border-ui-ondanger-secondary)',
		'ondanger-secondary-hover': 'var(--color-border-ui-ondanger-secondary-hover)',
		'onsuccess': 'var(--color-border-ui-onsuccess)',
		'onsuccess-hover': 'var(--color-border-ui-onsuccess-hover)',
		'onsuccess-secondary': 'var(--color-border-ui-onsuccess-secondary)',
		'onsuccess-secondary-hover': 'var(--color-border-ui-onsuccess-secondary-hover)',
		'onwarning': 'var(--color-border-ui-onwarning)',
		'onwarning-hover': 'var(--color-border-ui-onwarning-hover)',
		'onwarning-secondary': 'var(--color-border-ui-onwarning-secondary)',
		'onwarning-secondary-hover': 'var(--color-border-ui-onwarning-secondary-hover)',
		'oncaution': 'var(--color-border-ui-oncaution)',
		'oncaution-hover': 'var(--color-border-ui-oncaution-hover)',
		'oncaution-secondary': 'var(--color-border-ui-oncaution-secondary)',
		'oncaution-secondary-hover': 'var(--color-border-ui-oncaution-secondary-hover)',
		'onneutral': 'var(--color-border-ui-onneutral)',
		'onneutral-hover': 'var(--color-border-ui-onneutral-hover)',
		'onneutral-secondary': 'var(--color-border-ui-onneutral-secondary)',
		'onneutral-secondary-hover': 'var(--color-border-ui-onneutral-secondary-hover)',
		'ondisabled': 'var(--color-border-ui-ondisabled)',
		'ondisabled-secondary': 'var(--color-border-ui-ondisabled-secondary)',
		'white': 'var(--color-bg-ui-white)',
		'light-gray': 'var(--color-bg-ui-light-gray)',
		'gray': 'var(--color-bg-ui-gray)',
		'dark-gray': 'var(--color-bg-ui-dark-gray)',
		'black': 'var(--color-bg-ui-black)',
	},
}

const accentColor = {
	'ui': {
		DEFAULT: 'var(--color-accent-ui)',
		'brand': 'var(--color-accent-ui-brand)',
		'statistic': 'var(--color-accent-ui-statistic)',
		'danger': 'var(--color-accent-ui-danger)',
		'success': 'var(--color-accent-ui-success)',
		'warning': 'var(--color-accent-ui-warning)',
		'caution': 'var(--color-accent-ui-caution)',
		'neutral': 'var(--color-accent-ui-neutral)',
		'disabled': 'var(--color-accent-ui-disabled)',
		'onbrand': 'var(--color-accent-ui-onbrand)',
		'onstatistic': 'var(--color-accent-ui-onstatistic)',
		'onselected': 'var(--color-accent-ui-onselected)',
		'ondanger': 'var(--color-accent-ui-ondanger)',
		'onsuccess': 'var(--color-accent-ui-onsuccess)',
		'onwarning': 'var(--color-accent-ui-onwarning)',
		'oncaution': 'var(--color-accent-ui-oncaution)',
		'onneutral': 'var(--color-accent-ui-onneutral)',
		'ondisabled': 'var(--color-accent-ui-ondisabled)',
	},
}

const ringColor = {
	'ui': {
		DEFAULT: 'var(--color-ring-ui)',
		'brand': 'var(--color-ring-ui-brand)',
		'statistic': 'var(--color-ring-ui-statistic)',
		'danger': 'var(--color-ring-ui-danger)',
		'success': 'var(--color-ring-ui-success)',
		'warning': 'var(--color-ring-ui-warning)',
		'caution': 'var(--color-ring-ui-caution)',
		'neutral': 'var(--color-ring-ui-neutral)',
	},
}

const opacity = {
	92: "0.92",
}

export { colors, backgroundColor, textColor, borderColor, accentColor, ringColor, opacity };
