import typography from '@tailwindcss/typography'

/**
 * @param {string} cssVar
 * @returns {({opacityValue}: {opacityValue: string}) => string}
 */
function withOpacity(cssVar) {
	return ({opacityValue}) => {
		if (opacityValue !== undefined) {
			return `rgba(var(${cssVar}), ${opacityValue})`;
		}
		return `rgb(var(${cssVar}))`;
	};
}

export default {
	layers: ["components", "utilities"],
	safelist: ["theme-dark"],
	darkMode: 'class',
	theme: {
		fontSize: {
			'base': ['1rem', {
				lineHeight: '1.33',
				fontWeight: '500',
			}],
			'headline-sm': ['1rem', {
				lineHeight: '1.33',
				fontWeight: '700',
			}],
			'headline-md': ['1.125rem', {
				lineHeight: '1.33',
				fontWeight: '700',
			}],
			'headline': ['1.618rem', {
				lineHeight: '1.1',
				fontWeight: '700',
			}],
			'headline-xl': ['2.618rem', {
				lineHeight: '1.1',
				fontWeight: '700',
			}],
			'sm': ['0.833rem', {
				lineHeight: '1.1',
				fontWeight: '400',
			}],
			'sm-bold': ['0.833rem', {
				lineHeight: '1',
				fontWeight: '700',
			}],
			button: ['0.916rem', {
				lineHeight: '1',
				fontWeight: '700',
			}],
		},
		fontWeight: {
			normal: "400",
			medium: "500",
			bold: "700"
		},
		borderWidth: {
			0: '0px',
			DEFAULT: 'thin',
			2: '2px',
		},
		extend: {
			screens: {
				"3xl": "1920px",
				"4xl": "2160px"
			},
			colors: {
				transparent: "transparent",
				current: "currentColor",
				'svws': {
					'50': '#f1f7fe',
					'100': '#e3eefb',
					'200': '#c0dcf7',
					'300': '#88c0f1',
					'400': '#4ba1e7',
					'500': '#2285d5',
					DEFAULT: '#2285d5',
					'600': '#1467b5',
					'700': '#115393',
					'800': '#12477a',
					'900': '#153d65',
					'950': '#0e2743',
					'smoke': '#F6F5F4',
					'ash': '#B8CCC4',
					'olive': '#2B3B36',
					'night': '#141414',
				},
				white: withOpacity("--color-white"),
				black: withOpacity("--color-black"),
				gray: withOpacity("--color-gray"),
				primary: withOpacity("--color-primary"),
				light: withOpacity("--color-light"),
				"dark-20": withOpacity("--color-dark-20"),
				dark: withOpacity("--color-dark"),
				error: withOpacity("--color-error"),
				success: withOpacity("--color-success"),
				highlight: withOpacity("--color-highlight"),
				statistics: withOpacity("--color-statistics"),
				'palette': {
					'neutral': {
						'50': 'rgba(255, 255, 255, 0.9)',
						'100': 'rgba(255, 255, 255, 1)',
						'200': 'rgba(244, 244, 245, 1)',
						'300': 'rgba(234, 234, 236, 1)',
						'400': 'rgba(226, 226, 228, 1)',
						'500': 'rgba(213, 213, 216, 1)',
						'600': 'rgba(165, 165, 167, 1)',
						'700': 'rgba(91, 91, 93, 1)',
						'750': 'rgba(65, 65, 67, 1)',
						'800': 'rgba(38, 38, 39, 1)',
						'850': 'rgba(165, 165, 167, 0.2)',
						'900': 'rgba(0, 0, 0, 1)',
						'950': 'rgba(0, 0, 0, 0.8)',
					},
					'brand': {
						'50': 'rgba(27, 119, 193, 0.15)',
						'100': 'rgba(27, 119, 193, 0.5)',
						'200': 'rgba(166, 206, 247, 1)',
						'300': 'rgba(121, 180, 238, 1)',
						'400': 'rgba(66, 146, 217, 1)',
						'500': 'rgba(27, 119, 193, 1)',
						'600': 'rgba(0, 82, 144, 1)',
						'700': 'rgba(0, 70, 126, 1)',
						'800': 'rgba(0, 60, 109, 1)',
						'900': 'rgba(0, 42, 81, 1)',
					},
					'statistic': {
						'50': 'rgba(159, 55, 254, 0.15)',
						'100': 'rgba(159, 55, 254, 0.5)',
						'200': 'rgba(224, 188, 255, 1)',
						'300': 'rgba(208, 151, 255, 1)',
						'400': 'rgba(184, 101, 255, 1)',
						'500': 'rgba(159, 55, 254, 1)',
						'600': 'rgba(118, 8, 199, 1)',
						'700': 'rgba(102, 0, 174, 1)',
						'800': 'rgba(88, 0, 152, 1)',
						'900': 'rgba(63, 0, 112, 1)',
					},
					'success': {
						'50': 'rgba(43, 133, 0, 0.15)',
						'100': 'rgba(43, 133, 0, 0.5)',
						'200': 'rgba(189, 241, 136, 1)',
						'300': 'rgba(134, 226, 41, 1)',
						'400': 'rgba(91, 180, 0, 1)',
						'500': 'rgba(43, 133, 0, 1)',
						'600': 'rgba(0, 94, 0, 1)',
						'700': 'rgba(0, 69, 0, 1)',
						'900': 'rgba(0, 50, 0, 1)',
					},
					'danger': {
						'50': 'rgba(225, 28, 72, 0.15)',
						'100': 'rgba(225, 28, 72, 0.4)',
						'200': 'rgba(255, 200, 201, 1)',
						'300': 'rgba(255, 142, 150, 1)',
						'400': 'rgba(254, 87, 107, 1)',
						'500': 'rgba(225, 28, 72, 1)',
						'600': 'rgba(192, 0, 52, 1)',
						'700': 'rgba(165, 0, 40, 1)',
						'800': 'rgba(142, 0, 32, 1)',
						'900': 'rgba(106, 0, 20, 1)',
					},
					'warning': {
						'50': 'rgba(232, 191, 0, 0.15)',
						'100': 'rgba(232, 191, 0, 0.5)',
						'200': 'rgba(254, 235, 149, 1)',
						'300': 'rgba(246, 215, 76, 1)',
						'400': 'rgba(232, 191, 0, 1)',
						'500': 'rgba(208, 172, 7, 1)',
						'600': 'rgba(192, 158, 2, 1)',
						'700': 'rgba(167, 139, 6, 1)',
						'800': 'rgba(137, 114, 5, 1)',
						'900': 'rgba(82, 68, 3, 1)',
					},
					'caution': {
						'50': 'rgba(255, 247, 236, 1)',
						'100': 'rgba(255, 238, 211, 1)',
						'200': 'rgba(255, 217, 165, 1)',
						'300': 'rgba(255, 189, 109, 1)',
						'400': 'rgba(255, 150, 50, 1)',
						'500': 'rgba(255, 118, 10, 1)',
						'600': 'rgba(255, 93, 0, 1)',
						'700': 'rgba(204, 66, 2, 1)',
						'800': 'rgba(161, 51, 11, 1)',
						'900': 'rgba(130, 45, 12, 1)',
					},
				},
			},
			'backgroundColor': {
				'ui': {
					DEFAULT: 'var(--color-bg-ui)',
					'hover': 'var(--color-bg-ui-hover)',
					'brand': 'var(--color-bg-ui-brand)',
					'brand-hover': 'var(--color-bg-ui-brand-hover)',
					'brand-weak': 'var(--color-bg-ui-brand-weak)',
					'statistic': 'var(--color-bg-ui-statistic)',
					'statistic-hover': 'var(--color-bg-ui-statistic-hover)',
					'statistic-weak': 'var(--color-bg-ui-statistic-weak)',
					'selected': 'var(--color-bg-ui-selected)',
					'selected-hover': 'var(--color-bg-ui-selected-hover)',
					'danger': 'var(--color-bg-ui-danger)',
					'danger-hover': 'var(--color-bg-ui-danger-hover)',
					'danger-weak': 'var(--color-bg-ui-danger-weak)',
					'success': 'var(--color-bg-ui-success)',
					'success-hover': 'var(--color-bg-ui-success-hover)',
					'success-weak': 'var(--color-bg-ui-success-weak)',
					'warning': 'var(--color-bg-ui-warning)',
					'warning-hover': 'var(--color-bg-ui-warning-hover)',
					'warning-weak': 'var(--color-bg-ui-warning-weak)',
					'caution': 'var(--color-bg-ui-caution)',
					'caution-hover': 'var(--color-bg-ui-caution-hover)',
					'caution-weak': 'var(--color-bg-ui-caution-weak)',
					'neutral': 'var(--color-bg-ui-neutral)',
					'neutral-hover': 'var(--color-bg-ui-neutral-hover)',
					'neutral-weak': 'var(--color-bg-ui-neutral-weak)',
					'disabled': 'var(--color-bg-ui-disabled)',
					'inverted': 'var(--color-bg-ui-inverted)',
					'white': 'var(--color-bg-ui-white)',
					'black': 'var(--color-bg-ui-black)',
				}
			},
			'textColor': {
				'ui': {
					DEFAULT: 'var(--color-text-ui)',
					'hover': 'var(--color-text-ui-hover)',
					'secondary': 'var(--color-text-ui-secondary)',
					'secondary-hover': 'var(--color-text-ui-secondary-hover)',
					'brand': 'var(--color-text-ui-brand)',
					'brand-hover': 'var(--color-text-ui-brand-hover)',
					'brand-secondary': 'var(--color-text-ui-brand-secondary)',
					'brand-secondary-hover': 'var(--color-text-ui-brand-secondary-hover)',
					'statistic': 'var(--color-text-ui-statistic)',
					'statistic-hover': 'var(--color-text-ui-statistic-hover)',
					'statistic-secondary': 'var(--color-text-ui-statistic-secondary)',
					'statistic-secondary-hover': 'var(--color-text-ui-statistic-secondary-hover)',
					'selected': 'var(--color-text-ui-selected)',
					'selected-hover': 'var(--color-text-ui-selected-hover)',
					'selected-secondary': 'var(--color-text-ui-selected-secondary)',
					'selected-secondary-hover': 'var(--color-text-ui-selected-secondary-hover)',
					'danger': 'var(--color-text-ui-danger)',
					'danger-hover': 'var(--color-text-ui-danger-hover)',
					'danger-secondary': 'var(--color-text-ui-danger-secondary)',
					'danger-secondary-hover': 'var(--color-text-ui-danger-secondary-hover)',
					'success': 'var(--color-text-ui-success)',
					'success-hover': 'var(--color-text-ui-success-hover)',
					'success-secondary': 'var(--color-text-ui-success-secondary)',
					'success-secondary-hover': 'var(--color-text-ui-success-secondary-hover)',
					'warning': 'var(--color-text-ui-warning)',
					'warning-hover': 'var(--color-text-ui-warning-hover)',
					'warning-secondary': 'var(--color-text-ui-warning-secondary)',
					'warning-secondary-hover': 'var(--color-text-ui-warning-secondary-hover)',
					'caution': 'var(--color-text-ui-caution)',
					'caution-hover': 'var(--color-text-ui-caution-hover)',
					'caution-secondary': 'var(--color-text-ui-caution-secondary)',
					'caution-secondary-hover': 'var(--color-text-ui-caution-secondary-hover)',
					'neutral': 'var(--color-text-ui-neutral)',
					'neutral-hover': 'var(--color-text-ui-neutral-hover)',
					'neutral-secondary': 'var(--color-text-ui-neutral-secondary)',
					'neutral-secondary-hover': 'var(--color-text-ui-neutral-secondary-hover)',
					'disabled': 'var(--color-text-ui-disabled)',
					'disabled-secondary': 'var(--color-text-ui-disabled-secondary)',
					'onbrand': 'var(--color-text-ui-onbrand)',
					'onbrand-hover': 'var(--color-text-ui-onbrand-hover)',
					'onbrand-secondary': 'var(--color-text-ui-onbrand-secondary)',
					'onbrand-secondary-hover': 'var(--color-text-ui-onbrand-secondary-hover)',
					'onstatistic': 'var(--color-text-ui-onstatistic)',
					'onstatistic-hover': 'var(--color-text-ui-onstatistic-hover)',
					'onstatistic-secondary': 'var(--color-text-ui-onstatistic-secondary)',
					'onstatistic-secondary-hover': 'var(--color-text-ui-onstatistic-secondary-hover)',
					'onselected': 'var(--color-text-ui-onselected)',
					'onselected-hover': 'var(--color-text-ui-onselected-hover)',
					'onselected-secondary': 'var(--color-text-ui-onselected-secondary)',
					'onselected-secondary-hover': 'var(--color-text-ui-onselected-secondary-hover)',
					'ondanger': 'var(--color-text-ui-ondanger)',
					'ondanger-hover': 'var(--color-text-ui-ondanger-hover)',
					'ondanger-secondary': 'var(--color-text-ui-ondanger-secondary)',
					'ondanger-secondary-hover': 'var(--color-text-ui-ondanger-secondary-hover)',
					'onsuccess': 'var(--color-text-ui-onsuccess)',
					'onsuccess-hover': 'var(--color-text-ui-onsuccess-hover)',
					'onsuccess-secondary': 'var(--color-text-ui-onsuccess-secondary)',
					'onsuccess-secondary-hover': 'var(--color-text-ui-onsuccess-secondary-hover)',
					'onwarning': 'var(--color-text-ui-onwarning)',
					'onwarning-hover': 'var(--color-text-ui-onwarning-hover)',
					'onwarning-secondary': 'var(--color-text-ui-onwarning-secondary)',
					'onwarning-secondary-hover': 'var(--color-text-ui-onwarning-secondary-hover)',
					'oncaution': 'var(--color-text-ui-oncaution)',
					'oncaution-hover': 'var(--color-text-ui-oncaution-hover)',
					'oncaution-secondary': 'var(--color-text-ui-oncaution-secondary)',
					'oncaution-secondary-hover': 'var(--color-text-ui-oncaution-secondary-hover)',
					'onneutral': 'var(--color-text-ui-onneutral)',
					'onneutral-hover': 'var(--color-text-ui-onneutral-hover)',
					'onneutral-secondary': 'var(--color-text-ui-onneutral-secondary)',
					'onneutral-secondary-hover': 'var(--color-text-ui-onneutral-secondary-hover)',
					'ondisabled': 'var(--color-text-ui-ondisabled)',
					'ondisabled-secondary': 'var(--color-text-ui-ondisabled-secondary)',
					'white': 'var(--color-bg-ui-white)',
					'black': 'var(--color-bg-ui-black)',
				}
			},
			'borderColor': {
				'ui': {
					DEFAULT: 'var(--color-border-ui)',
					'hover': 'var(--color-border-ui-hover)',
					'secondary': 'var(--color-border-ui-secondary)',
					'secondary-hover': 'var(--color-border-ui-secondary-hover)',
					'brand': 'var(--color-border-ui-brand)',
					'brand-hover': 'var(--color-border-ui-brand-hover)',
					'brand-secondary': 'var(--color-border-ui-brand-secondary)',
					'brand-secondary-hover': 'var(--color-border-ui-brand-secondary-hover)',
					'statistic': 'var(--color-border-ui-statistic)',
					'statistic-hover': 'var(--color-border-ui-statistic-hover)',
					'statistic-secondary': 'var(--color-border-ui-statistic-secondary)',
					'statistic-secondary-hover': 'var(--color-border-ui-statistic-secondary-hover)',
					'selected': 'var(--color-border-ui-selected)',
					'selected-hover': 'var(--color-border-ui-selected-hover)',
					'selected-secondary': 'var(--color-border-ui-selected-secondary)',
					'selected-secondary-hover': 'var(--color-border-ui-selected-secondary-hover)',
					'danger': 'var(--color-border-ui-danger)',
					'danger-hover': 'var(--color-border-ui-danger-hover)',
					'danger-secondary': 'var(--color-border-ui-danger-secondary)',
					'danger-secondary-hover': 'var(--color-border-ui-danger-secondary-hover)',
					'success': 'var(--color-border-ui-success)',
					'success-hover': 'var(--color-border-ui-success-hover)',
					'success-secondary': 'var(--color-border-ui-success-secondary)',
					'success-secondary-hover': 'var(--color-border-ui-success-secondary-hover)',
					'warning': 'var(--color-border-ui-warning)',
					'warning-hover': 'var(--color-border-ui-warning-hover)',
					'warning-secondary': 'var(--color-border-ui-warning-secondary)',
					'warning-secondary-hover': 'var(--color-border-ui-warning-secondary-hover)',
					'caution': 'var(--color-border-ui-caution)',
					'caution-hover': 'var(--color-border-ui-caution-hover)',
					'caution-secondary': 'var(--color-border-ui-caution-secondary)',
					'caution-secondary-hover': 'var(--color-border-ui-caution-secondary-hover)',
					'neutral': 'var(--color-border-ui-neutral)',
					'neutral-hover': 'var(--color-border-ui-neutral-hover)',
					'neutral-secondary': 'var(--color-border-ui-neutral-secondary)',
					'neutral-secondary-hover': 'var(--color-border-ui-neutral-secondary-hover)',
					'disabled': 'var(--color-border-ui-disabled)',
					'disabled-secondary': 'var(--color-border-ui-disabled-secondary)',
					'onbrand': 'var(--color-border-ui-onbrand)',
					'onbrand-hover': 'var(--color-border-ui-onbrand-hover)',
					'onbrand-secondary': 'var(--color-border-ui-onbrand-secondary)',
					'onbrand-secondary-hover': 'var(--color-border-ui-onbrand-secondary-hover)',
					'onstatistic': 'var(--color-border-ui-onstatistic)',
					'onstatistic-hover': 'var(--color-border-ui-onstatistic-hover)',
					'onstatistic-secondary': 'var(--color-border-ui-onstatistic-secondary)',
					'onstatistic-secondary-hover': 'var(--color-border-ui-onstatistic-secondary-hover)',
					'onselected': 'var(--color-border-ui-onselected)',
					'onselected-hover': 'var(--color-border-ui-onselected-hover)',
					'onselected-secondary': 'var(--color-border-ui-onselected-secondary)',
					'onselected-secondary-hover': 'var(--color-border-ui-onselected-secondary-hover)',
					'ondanger': 'var(--color-border-ui-ondanger)',
					'ondanger-hover': 'var(--color-border-ui-ondanger-hover)',
					'ondanger-secondary': 'var(--color-border-ui-ondanger-secondary)',
					'ondanger-secondary-hover': 'var(--color-border-ui-ondanger-secondary-hover)',
					'onsuccess': 'var(--color-border-ui-onsuccess)',
					'onsuccess-hover': 'var(--color-border-ui-onsuccess-hover)',
					'onsuccess-secondary': 'var(--color-border-ui-onsuccess-secondary)',
					'onsuccess-secondary-hover': 'var(--color-border-ui-onsuccess-secondary-hover)',
					'onwarning': 'var(--color-border-ui-onwarning)',
					'onwarning-hover': 'var(--color-border-ui-onwarning-hover)',
					'onwarning-secondary': 'var(--color-border-ui-onwarning-secondary)',
					'onwarning-secondary-hover': 'var(--color-border-ui-onwarning-secondary-hover)',
					'oncaution': 'var(--color-border-ui-oncaution)',
					'oncaution-hover': 'var(--color-border-ui-oncaution-hover)',
					'oncaution-secondary': 'var(--color-border-ui-oncaution-secondary)',
					'oncaution-secondary-hover': 'var(--color-border-ui-oncaution-secondary-hover)',
					'onneutral': 'var(--color-border-ui-onneutral)',
					'onneutral-hover': 'var(--color-border-ui-onneutral-hover)',
					'onneutral-secondary': 'var(--color-border-ui-onneutral-secondary)',
					'onneutral-secondary-hover': 'var(--color-border-ui-onneutral-secondary-hover)',
					'ondisabled': 'var(--color-border-ui-ondisabled)',
					'ondisabled-secondary': 'var(--color-border-ui-ondisabled-secondary)',
					'white': 'var(--color-bg-ui-white)',
					'light-gray': 'var(--color-bg-ui-light-gray)',
					'gray': 'var(--color-bg-ui-gray)',
					'dark-gray': 'var(--color-bg-ui-dark-gray)',
					'black': 'var(--color-bg-ui-black)',
				}
			},
			'accentColor': {
				'ui': {
					DEFAULT: 'var(--color-accent-ui)',
					'brand': 'var(--color-accent-ui-brand)',
					'statistic': 'var(--color-accent-ui-statistic)',
					'danger': 'var(--color-accent-ui-danger)',
					'success': 'var(--color-accent-ui-success)',
					'warning': 'var(--color-accent-ui-warning)',
					'caution': 'var(--color-accent-ui-caution)',
					'neutral': 'var(--color-accent-ui-neutral)',
					'disabled': 'var(--color-accent-ui-disabled)',
					'onbrand': 'var(--color-accent-ui-onbrand)',
					'onstatistic': 'var(--color-accent-ui-onstatistic)',
					'onselected': 'var(--color-accent-ui-onselected)',
					'ondanger': 'var(--color-accent-ui-ondanger)',
					'onsuccess': 'var(--color-accent-ui-onsuccess)',
					'onwarning': 'var(--color-accent-ui-onwarning)',
					'oncaution': 'var(--color-accent-ui-oncaution)',
					'onneutral': 'var(--color-accent-ui-onneutral)',
					'ondisabled': 'var(--color-accent-ui-ondisabled)',
				}
			},
			'ringColor': {
				'ui': {
					DEFAULT: 'var(--color-ring-ui)',
					'brand': 'var(--color-ring-ui-brand)',
					'statistic': 'var(--color-ring-ui-statistic)',
					'danger': 'var(--color-ring-ui-danger)',
					'success': 'var(--color-ring-ui-success)',
					'warning': 'var(--color-ring-ui-warning)',
					'caution': 'var(--color-ring-ui-caution)',
					'neutral': 'var(--color-ring-ui-neutral)',
				}
			},
			opacity: {
				92: "0.92"
			},
			zIndex: {
				"-10": "-10",
				"-20": "-20"
			},
			maxWidth: {
				116: "29rem",
				"modal-sm": "28rem",
				"modal-md": "58rem",
				"modal-lg": "90rem",
				"modal-help": "47rem",
			},
			minWidth: {
				64: "16rem",
				84: "21rem"
			},
			boxShadow: {
				"border-t": "0 -2px 0 0 rgba(0, 0, 0, 1)",
				"border-b": "0 2px 0 0 rgba(0, 0, 0, 1)",
				"lg-up": "0 -10px 15px -3px rgb(0 0 0 / 0.1), 0 -4px 6px -4px rgb(0 0 0 / 0.1)"
			},
			spacing: {
				'68': '17rem',
				'72': '18rem',
				'76': '19rem',
				'80': '20rem',
				'84': '21rem',
				'88': '22rem',
				'92': '23rem',
				'96': '24rem',
				'100': '25rem',
				'104': '26rem',
				'108': '27rem',
				'112': '28rem',
				'116': '29rem',
				'120': '30rem',
				'124': '31rem',
				'128': '32rem',
				'132': '33rem',
				'136': '34rem',
				'140': '35rem',
				'144': '36rem',
			},
		}
	},
	variants: {
		extend: {}
	},
	plugins: [
		typography,
	],
};
