version: "3"
services:

    svws-server:
        image: svwsnrw/svws-server:0.7.1
        ports:
            - "8443:8443"
        environment:
            MariaDB_HOST: "${MariaDB_HOST}"
            MariaDB_ROOT_PASSWORD: "${MariaDB_ROOT_PASSWORD}"
            MariaDB_DATABASE: "${MariaDB_DATABASE}"
            MariaDB_USER: "${MariaDB_USER}"
            MariaDB_PASSWORD: "${MariaDB_PASSWORD}"
            SVWS_TLS_KEY_ALIAS: "${SVWS_TLS_KEY_ALIAS}"
            SVWS_TLS_KEYSTORE_PATH: "${SVWS_TLS_KEYSTORE_PATH}"
            SVWS_TLS_KEYSTORE_PASSWORD: "${SVWS_TLS_KEYSTORE_PASSWORD}"
        volumes:
            - ~/SVWS/SVWS-Server/deployment/docker/init-scripts:/etc/app/svws/init-scripts
            - ~/SVWS/svws-docker/keystore:${SVWS_TLS_KEYSTORE_PATH}
        env_file:
            - .env
