version: "3"
services:
  mariadb:
    build:
      context: mariadb
    restart: always
    environment:
      MariaDB_ROOT_PASSWORD: "${MariaDB_ROOT_PASSWORD}"
      MariaDB_DATABASE: "${MariaDB_DATABASE}"
      MariaDB_USER: "${MariaDB_USER}"
      MariaDB_PASSWORD: "${MariaDB_PASSWORD}"
    env_file:
      - .env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MariaDB_USER --password=$$MariaDB_PASSWORD
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 10
    mem_limit: '512m'
    volumes:
      - "./volume/mysql/data:${MARIADB_DATA_DIR}"
      - "./volume/mysql/logs:${MARIADB_LOG_DIR}"

  svws:
    build: svws
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    environment:
        - JAVA_OPTS=-Xmx2G -XX:MaxRAM=1073741824
    env_file:
      - .env
    ports:
      - "8443:8443"
    mem_limit: '2g'
    volumes:
      - ./volume/keystore:/etc/app/svws/keystore
      - ./init-scripts:/etc/app/svws/init-scripts
